"""initial schema: accounts, parental settings, rooms, results, room directory, hand journal (C-26)

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 04:22:06.162062
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hands',
    sa.Column('hand_id', sa.String(length=80), nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('epoch', sa.BigInteger(), nullable=False),
    sa.Column('commitment', sa.String(length=64), nullable=False),
    sa.Column('encrypted_seed', sa.Text(), nullable=True),
    sa.Column('server_seed', sa.String(length=64), nullable=True),
    sa.Column('client_seeds', sa.JSON(), nullable=True),
    sa.Column('substituted', sa.JSON(), nullable=True),
    sa.Column('chain_root', sa.String(length=64), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('match_state_digest', sa.String(length=64), nullable=True),
    sa.Column('randomness_version', sa.String(length=16), server_default=sa.text("'tz-rng-v1'"), nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hand_id')
    )
    op.create_index(op.f('ix_hands_room_code'), 'hands', ['room_code'], unique=False)
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=80), nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('epoch', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.String(length=40), nullable=False),
    sa.Column('effective_profile_hash', sa.String(length=64), nullable=False),
    sa.Column('engine_build_hash', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('totals', sa.JSON(), nullable=False),
    sa.Column('placements', sa.JSON(), nullable=True),
    sa.Column('players', sa.JSON(), nullable=False),
    sa.Column('bot_seats', sa.JSON(), nullable=False),
    sa.Column('sealed_hand_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=24), nullable=False),
    sa.Column('token_generation', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('reported_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_directory',
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('instance_id', sa.String(length=64), nullable=False),
    sa.Column('instance_url', sa.String(length=255), nullable=False),
    sa.Column('epoch', sa.BigInteger(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('room_code')
    )
    op.create_table('rooms',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('host_player_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=40), nullable=False),
    sa.Column('preset', sa.String(length=40), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('profile_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('blocks',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('blocked_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'blocked_id')
    )
    op.create_table('input_records',
    sa.Column('hand_id', sa.String(length=80), nullable=False),
    sa.Column('server_seq', sa.BigInteger(), nullable=False),
    sa.Column('epoch', sa.BigInteger(), nullable=False),
    sa.Column('intent_id', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.String(length=8), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['hand_id'], ['hands.hand_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hand_id', 'server_seq'),
    sa.UniqueConstraint('hand_id', 'actor', 'intent_id', name='uq_input_intent')
    )
    op.create_table('parental_settings',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('free_text_chat', sa.Boolean(), nullable=False),
    sa.Column('voice', sa.Boolean(), nullable=False),
    sa.Column('online_play', sa.Boolean(), nullable=False),
    sa.Column('pin_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_stats',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=40), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('interrupted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'profile_id')
    )
    op.create_table('room_seats',
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['room_code'], ['rooms.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_code', 'seat'),
    sa.UniqueConstraint('room_code', 'player_id')
    )
    # ### end Alembic commands ###
    # ownership epochs come from a sequence so they are strictly increasing (C-20)
    op.execute("CREATE SEQUENCE IF NOT EXISTS room_epoch_seq")
    # least privilege: the match server writes only its tables (03_PLATFORM.md §5.2)
    op.execute("""
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tz_match') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON room_directory TO tz_match;
    GRANT SELECT, INSERT, UPDATE ON hands TO tz_match;
    GRANT SELECT, INSERT ON input_records TO tz_match;
    GRANT USAGE, SELECT ON SEQUENCE room_epoch_seq TO tz_match;
  END IF;
END $$;""")


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS room_epoch_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_seats')
    op.drop_table('player_stats')
    op.drop_table('parental_settings')
    op.drop_table('input_records')
    op.drop_table('blocks')
    op.drop_table('rooms')
    op.drop_table('room_directory')
    op.drop_table('reports')
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_index(op.f('ix_hands_room_code'), table_name='hands')
    op.drop_table('hands')
    # ### end Alembic commands ###
