"""port v1 features

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23 15:01:46.125243
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # reports: integer id → UUID and new moderation columns. The database is created fresh, so recreate the table.
    op.drop_table('reports')
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('match_id', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('state', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolution_reason', sa.String(length=20), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.CheckConstraint("reason IN ('cheating','other','rude')", name='ck_reports_reason'),
    sa.CheckConstraint('reporter_id <> subject_id', name='ck_reports_not_self'),
    sa.CheckConstraint("state IN ('actioned','dismissed','open')", name='ck_reports_state'),
    sa.CheckConstraint("(state = 'open' AND resolved_at IS NULL AND resolution_reason IS NULL) OR (state <> 'open' AND resolved_at IS NOT NULL AND resolution_reason IS NOT NULL)", name='ck_reports_resolution'),
    sa.ForeignKeyConstraint(['reporter_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['players.id']),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_created_at', 'reports', ['created_at'])
    op.create_index('ix_reports_reporter_id', 'reports', ['reporter_id'])
    op.create_index('ix_reports_state_created_at', 'reports', ['state', 'created_at'])
    op.create_index('ix_reports_subject_state', 'reports', ['subject_id', 'state'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('profile_id', sa.String(length=40), nullable=True),
    sa.Column('match_id', sa.String(length=80), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('record', sa.JSON(), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('bug','idea','other','rules')", name='ck_feedback_category'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_player_id'), 'feedback', ['player_id'], unique=False)
    op.create_table('match_players',
    sa.Column('match_id', sa.String(length=80), nullable=False),
    sa.Column('seat', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('placement', sa.SmallInteger(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'bot' AND player_id IS NULL) OR (kind = 'human' AND player_id IS NOT NULL)", name='ck_match_players_kind_player'),
    sa.CheckConstraint("kind IN ('bot','human')", name='ck_match_players_kind'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'seat')
    )
    op.create_index('ix_match_players_player_created', 'match_players', ['player_id', 'created_at'], unique=False)
    op.create_table('matchmaking_tickets',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=40), nullable=False),
    sa.Column('seats', sa.SmallInteger(), nullable=False),
    sa.Column('state', sa.String(length=10), server_default='waiting', nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(state = 'matched' AND room_code IS NOT NULL) OR (state <> 'matched' AND room_code IS NULL)", name='ck_tickets_room_code'),
    sa.CheckConstraint("state IN ('cancelled','expired','matched','waiting')", name='ck_tickets_state'),
    sa.CheckConstraint('seats BETWEEN 3 AND 8', name='ck_tickets_seats'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index('ix_tickets_queue', 'matchmaking_tickets', ['state', 'profile_id', 'seats', 'created_at'], unique=False)
    op.create_index('ix_tickets_state_expires', 'matchmaking_tickets', ['state', 'expires_at'], unique=False)
    op.create_table('moderators',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='moderator', nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('admin','moderator')", name='ck_moderators_role'),
    sa.ForeignKeyConstraint(['granted_by'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_identities',
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('apple','google','play_games')", name='ck_player_identities_provider'),
    sa.CheckConstraint('length(subject) > 0', name='ck_player_identities_subject'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider', 'subject'),
    sa.UniqueConstraint('player_id', 'provider', name='uq_player_identities_player_id_provider')
    )
    op.create_table('player_progress',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('matches', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('wins', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('hands_played', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('first_out', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('times_bhabhi', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('best_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('badges', sa.JSON(), nullable=False),
    sa.Column('games', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('best_streak <= wins', name='ck_player_progress_best_streak'),
    sa.CheckConstraint('wins <= matches', name='ck_player_progress_wins'),
    sa.CheckConstraint('xp >= 0 AND matches >= 0 AND wins >= 0 AND hands_played >= 0 AND first_out >= 0 AND times_bhabhi >= 0 AND best_streak >= 0', name='ck_player_progress_non_negative'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('sanctions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('moderator_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('banned','chat_muted','online_suspended','warning')", name='ck_sanctions_kind'),
    sa.CheckConstraint("reason IN ('abuse','cheating','duplicate','no_evidence','not_a_violation','repeat_offender','retaliatory','spam')", name='ck_sanctions_reason'),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > created_at', name='ck_sanctions_expires_at'),
    sa.ForeignKeyConstraint(['moderator_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sanctions_subject_expires', 'sanctions', ['subject_id', 'expires_at'], unique=False)
    op.create_table('appeals',
    sa.Column('sanction_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decision_note', sa.String(length=500), nullable=True),
    sa.CheckConstraint("state IN ('granted','open','rejected')", name='ck_appeals_state'),
    sa.CheckConstraint('length(message) > 0', name='ck_appeals_message'),
    sa.ForeignKeyConstraint(['decided_by'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sanction_id'], ['sanctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sanction_id')
    )
    op.create_index(op.f('ix_appeals_player_id'), 'appeals', ['player_id'], unique=False)
    op.create_index('ix_appeals_state_created_at', 'appeals', ['state', 'created_at'], unique=False)
    op.create_table('moderation_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('sanction_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('appeal_decided','moderator_granted','moderator_revoked','report_actioned','report_dismissed','sanction_created','sanction_revoked')", name='ck_moderation_audit_action'),
    sa.ForeignKeyConstraint(['actor_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sanction_id'], ['sanctions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_audit_created_at'), 'moderation_audit', ['created_at'], unique=False)
    op.create_index('ix_moderation_audit_subject_created', 'moderation_audit', ['subject_id', 'created_at'], unique=False)
    op.create_table('report_evidence',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_report_evidence_created_at'), 'report_evidence', ['created_at'], unique=False)
    op.create_table('room_kicks',
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('kicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_code'], ['rooms.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_code', 'player_id')
    )
    op.create_table('sanction_reports',
    sa.Column('sanction_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sanction_id'], ['sanctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sanction_id', 'report_id')
    )
    op.create_index(op.f('ix_sanction_reports_report_id'), 'sanction_reports', ['report_id'], unique=False)
    op.add_column('blocks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_blocks_blocked_id', 'blocks', ['blocked_id'], unique=False)
    op.create_foreign_key('fk_blocks_blocked_id', 'blocks', 'players', ['blocked_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_matches_room_code'), 'matches', ['room_code'], unique=False)
    op.add_column('parental_settings', sa.Column('same_wifi', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('parental_settings', sa.Column('quick_messages', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('parental_settings', sa.Column('reactions', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('parental_settings', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('players', sa.Column('avatar_id', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('players', sa.Column('protected', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('players', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('players', 'display_name',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.add_column('room_seats', sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key('fk_room_seats_player_id', 'room_seats', 'players', ['player_id'], ['id'])
    op.add_column('rooms', sa.Column('seats', sa.SmallInteger(), server_default=sa.text('4'), nullable=False))
    op.add_column('rooms', sa.Column('origin', sa.String(length=12), server_default='code', nullable=False))
    op.add_column('rooms', sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rooms', sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('rooms', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.create_index('ix_rooms_status_changed', 'rooms', ['status', 'status_changed_at'], unique=False)
    op.create_index('ix_rooms_status_expires_at', 'rooms', ['status', 'expires_at'], unique=False)
    op.create_foreign_key('fk_rooms_host_player_id', 'rooms', 'players', ['host_player_id'], ['id'])
    # ### end Alembic commands ###

    # v1 defaults and CHECK constraints on tables that already existed in 0001
    op.execute("UPDATE rooms SET status = 'open' WHERE status = 'lobby'")
    op.execute("UPDATE rooms SET status = 'finished' WHERE status = 'ended'")
    op.alter_column('rooms', 'status', server_default='open')
    op.create_check_constraint('ck_rooms_status', 'rooms', "status IN ('expired','finished','open','playing')")
    op.create_check_constraint('ck_rooms_origin', 'rooms', "origin IN ('code','quick_match')")
    op.create_check_constraint('ck_rooms_seats', 'rooms', 'seats BETWEEN 3 AND 8')
    op.create_check_constraint('ck_room_seats_seat', 'room_seats', 'seat BETWEEN 0 AND 7')
    op.create_check_constraint('ck_blocks_not_self', 'blocks', 'player_id <> blocked_id')
    # owner decision 17 Sep 2026: typed chat and voice default on (Parent Settings can turn them off)
    for col in ('free_text_chat', 'voice', 'online_play'):
        op.alter_column('parental_settings', col, server_default=sa.text('true'))
    op.execute("GRANT SELECT ON rooms, room_seats TO tz_match")  # read-only; results still go through /internal



def downgrade() -> None:
    for fk, t in (('fk_blocks_blocked_id', 'blocks'), ('fk_room_seats_player_id', 'room_seats'), ('fk_rooms_host_player_id', 'rooms')):
        op.drop_constraint(fk, t, type_='foreignkey')
    for c, t in (('ck_blocks_not_self', 'blocks'), ('ck_room_seats_seat', 'room_seats'), ('ck_rooms_seats', 'rooms'),
                 ('ck_rooms_origin', 'rooms'), ('ck_rooms_status', 'rooms')):
        op.drop_constraint(c, t, type_='check')
    for t in ('sanction_reports', 'room_kicks', 'report_evidence', 'moderation_audit', 'appeals', 'sanctions', 'player_progress',
              'player_identities', 'moderators', 'matchmaking_tickets', 'match_players', 'feedback', 'reports'):
        op.drop_table(t)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('reported_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('match_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'))
    for t, cols in (('rooms', ('seats', 'origin', 'expires_at', 'status_changed_at')), ('room_seats', ('joined_at',)),
                    ('players', ('avatar_id', 'protected', 'last_seen_at')), ('parental_settings', ('same_wifi', 'quick_messages', 'reactions', 'updated_at')),
                    ('blocks', ('created_at',))):
        for c in cols:
            op.drop_column(t, c)
