import { localized } from "../../i18n";

type Rank = "ustad" | "player" | "rising" | "novice";
const rankFor = (wins: number): Rank => (wins >= 50 ? "ustad" : wins >= 20 ? "player" : wins >= 5 ? "rising" : "novice");

export const T = localized("me", {
  en: {
    title: "You",
    table: "Table",
    edit: "Edit",
    changeAvatar: "Change avatar",
    defaultName: "Player",
    noHands: "No hands yet",
    summary: (matches: number, avatar: string) => `${matches} match${matches === 1 ? "" : "es"} · ${avatar}`,
    emptyTitle: "Nothing on the record yet",
    emptyBody: "Play a hand and it lands here: matches, wins and the games you have tried.",
    deal: "Deal a hand",
    browse: "Browse the games",
    allTime: "All time",
    won: (pct: number) => `${pct}% won`,
    matches: "Matches", wins: "Wins", streak: "Streak", bhabhi: "Bhabhi",
    recent: "Recent games",
    recentHint: "Games you played most recently, newest first",
    localOnly: "Your record lives on this phone only. Nothing is uploaded, and clearing the app's data clears it.",
    passport: "Mehfil passport",
    onDevice: "On this phone",
    ranks: { ustad: "Mehfil Ustad", player: "Mehfil Player", rising: "Rising Cardist", novice: "Shagird (Novice)" },
    rankFor,
    streakLine: (n: number) => `Win streak: ${n} matches in a row`,
    sheet: {
      title: "Your avatar",
      body: "Drawn marks, not photographs: there are no pictures of people anywhere in TashZone.",
      nameLabel: "Your name",
      namePlaceholder: "Type a name",
      done: "Done",
    },
  } as const,
  ur: {
    title: "آپ",
    table: "میز",
    edit: "ترمیم",
    changeAvatar: "اوتار بدلیں",
    defaultName: "کھلاڑی",
    noHands: "ابھی کوئی بازی نہیں",
    summary: (matches: number, avatar: string) => `${matches} میچ · ${avatar}`,
    emptyTitle: "ابھی ریکارڈ خالی ہے",
    emptyBody: "ایک بازی کھیلیں اور وہ یہاں آ جائے گی: میچ، جیتیں اور وہ کھیل جو آپ نے آزمائے۔",
    deal: "پتے بانٹیں",
    browse: "کھیل دیکھیں",
    allTime: "اب تک",
    won: (pct: number) => `${pct}% جیتے`,
    matches: "میچ", wins: "جیتیں", streak: "لگاتار", bhabhi: "Bhabhi",
    recent: "حالیہ کھیل",
    recentHint: "جو کھیل آپ نے حال ہی میں کھیلے، نئے پہلے",
    localOnly: "آپ کا ریکارڈ صرف اسی فون پر ہے۔ کچھ بھی اپ لوڈ نہیں ہوتا، اور ایپ کا ڈیٹا صاف کرنے سے یہ بھی مٹ جاتا ہے۔",
    passport: "محفل پاسپورٹ",
    onDevice: "اسی فون پر",
    ranks: { ustad: "محفل کے استاد", player: "محفل کے کھلاڑی", rising: "ابھرتے کھلاڑی", novice: "شاگرد" },
    rankFor,
    streakLine: (n: number) => `جیت کا سلسلہ: لگاتار ${n} میچ`,
    sheet: {
      title: "آپ کا اوتار",
      body: "ہاتھ سے بنے نشان، تصویریں نہیں: TashZone میں کہیں بھی لوگوں کی تصویریں نہیں ہیں۔",
      nameLabel: "آپ کا نام",
      namePlaceholder: "نام لکھیں",
      done: "ہو گیا",
    },
  },
  hi: {
    title: "आप",
    table: "मेज़",
    edit: "बदलें",
    changeAvatar: "अवतार बदलें",
    defaultName: "खिलाड़ी",
    noHands: "अभी कोई बाज़ी नहीं",
    summary: (matches: number, avatar: string) => `${matches} मैच · ${avatar}`,
    emptyTitle: "अभी रिकॉर्ड खाली है",
    emptyBody: "एक बाज़ी खेलें, वह यहाँ दिखेगी: मैच, जीत और वे खेल जो आपने आज़माए।",
    deal: "पत्ते बाँटें",
    browse: "खेल देखें",
    allTime: "अब तक",
    won: (pct: number) => `${pct}% जीते`,
    matches: "मैच", wins: "जीत", streak: "लगातार", bhabhi: "Bhabhi",
    recent: "हाल के खेल",
    recentHint: "हाल ही में खेले गए खेल, नए पहले",
    localOnly: "आपका रिकॉर्ड सिर्फ़ इसी फ़ोन पर है। कुछ भी अपलोड नहीं होता, और ऐप का डेटा साफ़ करने से यह भी मिट जाता है।",
    passport: "महफ़िल पासपोर्ट",
    onDevice: "इसी फ़ोन पर",
    ranks: { ustad: "महफ़िल के उस्ताद", player: "महफ़िल के खिलाड़ी", rising: "उभरते खिलाड़ी", novice: "शागिर्द" },
    rankFor,
    streakLine: (n: number) => `जीत का सिलसिला: लगातार ${n} मैच`,
    sheet: {
      title: "आपका अवतार",
      body: "हाथ से बने निशान, फ़ोटो नहीं: TashZone में कहीं भी लोगों की तस्वीरें नहीं हैं।",
      nameLabel: "आपका नाम",
      namePlaceholder: "नाम लिखें",
      done: "हो गया",
    },
  },
  ne: {
    title: "तपाईं",
    table: "टेबल",
    edit: "सम्पादन",
    changeAvatar: "अवतार बदल्नुहोस्",
    defaultName: "खेलाडी",
    noHands: "अहिलेसम्म कुनै बाजी छैन",
    summary: (matches: number, avatar: string) => `${matches} म्याच · ${avatar}`,
    emptyTitle: "अहिलेसम्म रेकर्ड खाली छ",
    emptyBody: "एउटा बाजी खेल्नुहोस्, यहाँ देखिन्छ: म्याच, जित र तपाईंले खेलेका खेलहरू।",
    deal: "पत्ती बाँड्नुहोस्",
    browse: "खेलहरू हेर्नुहोस्",
    allTime: "हालसम्म",
    won: (pct: number) => `${pct}% जित`,
    matches: "म्याच", wins: "जित", streak: "लगातार", bhabhi: "Bhabhi",
    recent: "हालका खेलहरू",
    recentHint: "भर्खरै खेलेका खेलहरू, नयाँ पहिले",
    localOnly: "तपाईंको रेकर्ड यही फोनमा मात्र छ। केही पनि अपलोड हुँदैन, र एपको डेटा मेटाउँदा यो पनि मेटिन्छ।",
    passport: "महफिल पासपोर्ट",
    onDevice: "यही फोनमा",
    ranks: { ustad: "महफिलका उस्ताद", player: "महफिलका खेलाडी", rising: "उदाउँदो खेलाडी", novice: "सिकारु" },
    rankFor,
    streakLine: (n: number) => `जितको लहर: लगातार ${n} म्याच`,
    sheet: {
      title: "तपाईंको अवतार",
      body: "हातले कोरिएका चिन्ह, फोटो होइन: TashZone मा कतै पनि मानिसका तस्बिर छैनन्।",
      nameLabel: "तपाईंको नाम",
      namePlaceholder: "नाम लेख्नुहोस्",
      done: "भयो",
    },
  },
  bn: {
    title: "আপনি",
    table: "টেবিল",
    edit: "সম্পাদনা",
    changeAvatar: "অবতার বদলান",
    defaultName: "খেলোয়াড়",
    noHands: "এখনো কোনো দান নেই",
    summary: (matches: number, avatar: string) => `${matches}টি ম্যাচ · ${avatar}`,
    emptyTitle: "এখনো রেকর্ডে কিছু নেই",
    emptyBody: "একটি দান খেলুন, এখানে দেখা যাবে: ম্যাচ, জয় আর যে খেলাগুলো খেলেছেন।",
    deal: "তাস বাঁটুন",
    browse: "খেলাগুলো দেখুন",
    allTime: "এ পর্যন্ত",
    won: (pct: number) => `${pct}% জয়`,
    matches: "ম্যাচ", wins: "জয়", streak: "টানা", bhabhi: "Bhabhi",
    recent: "সাম্প্রতিক খেলা",
    recentHint: "সম্প্রতি খেলা খেলাগুলো, নতুনগুলো আগে",
    localOnly: "আপনার রেকর্ড শুধু এই ফোনেই থাকে। কিছুই আপলোড হয় না, আর অ্যাপের ডেটা মুছলে এটিও মুছে যায়।",
    passport: "মেহফিল পাসপোর্ট",
    onDevice: "এই ফোনে",
    ranks: { ustad: "মেহফিলের ওস্তাদ", player: "মেহফিলের খেলোয়াড়", rising: "উঠতি খেলোয়াড়", novice: "শাগরেদ" },
    rankFor,
    streakLine: (n: number) => `জয়ের ধারা: টানা ${n}টি ম্যাচ`,
    sheet: {
      title: "আপনার অবতার",
      body: "আঁকা চিহ্ন, ছবি নয়: TashZone-এ কোথাও মানুষের ছবি নেই।",
      nameLabel: "আপনার নাম",
      namePlaceholder: "একটি নাম লিখুন",
      done: "হয়ে গেছে",
    },
  },
});
