import { localized } from "../../i18n";

export const A = localized("accountAuth", {
  en: {
    signInTitle: "Sign in", createTitle: "Create account", forgotTitle: "Reset password", changeTitle: "Change password",
    email: "Email", password: "Password", newPassword: "New password", currentPassword: "Current password", code: "6-digit code",
    emailPh: "you@example.com", passwordRule: "At least 8 characters, with a letter and a number.",
    signIn: "Sign in", useCode: "Email me a code instead", usePassword: "Use my password", sendCode: "Send code", resend: "Send a new code",
    codeSent: (email: string) => `We sent a code to ${email}. It works for 10 minutes.`,
    create: "Create account", forgot: "Forgot password?", toCreate: "New here? Create an account", toSignIn: "Have an account? Sign in",
    save: "Save", or: "or", show: "Show", hide: "Hide",
    replaceNote: "Signing in replaces this phone's record with your account's.",
    keepNote: "Your name and record on this phone move into the new account.",
    errEmail: "Enter a valid email.", errPassword: "Use at least 8 characters with a letter and a number.", errCode: "Enter the 6 digits from the email.",
    errInvalidCode: "That code is wrong or has expired.", errCredentials: "Email or password is wrong.", errCurrent: "Current password is wrong.",
    errTaken: "That email already has an account. Sign in instead.", errExists: "This profile already has an account.",
    errProtected: "A parent must set up sign-in for this profile.", errRate: "Too many tries. Wait a minute.", errOffline: "No connection. Try again.",
    errUnavailable: "Email sign-in isn't available right now.", errBanned: "This account can't sign in right now.", errExpired: "Please sign in again.",
    errFailed: "Something went wrong. Try again.",
    welcome: "Signed in.", created: "Account created. Your record is backed up.", passwordSaved: "Password changed.",
    devicesTitle: "Your devices", devicesHint: "See where you are signed in", thisPhone: "This phone",
    unknownDevice: "Unknown device", activeToday: "Active today", lastActive: (date: string) => `Last active ${date}`,
    signOutDeviceTitle: "Sign out this device?", signOutDeviceBody: "It will need to sign in again to use your account.", signOutDeviceDo: "Sign out",
    deviceSignedOut: "Device signed out.", noOthers: "No other devices are signed in.",
  },
  ur: {
    signInTitle: "سائن اِن", createTitle: "اکاؤنٹ بنائیں", forgotTitle: "پاس ورڈ نیا بنائیں", changeTitle: "پاس ورڈ بدلیں",
    email: "ای میل", password: "پاس ورڈ", newPassword: "نیا پاس ورڈ", currentPassword: "موجودہ پاس ورڈ", code: "6 ہندسوں کا کوڈ",
    emailPh: "you@example.com", passwordRule: "کم از کم 8 حروف، ایک حرف اور ایک ہندسہ ضرور۔",
    signIn: "سائن اِن", useCode: "اس کے بجائے ای میل پر کوڈ بھیجیں", usePassword: "پاس ورڈ سے", sendCode: "کوڈ بھیجیں", resend: "نیا کوڈ بھیجیں",
    codeSent: (email: string) => `ہم نے ${email} پر کوڈ بھیجا ہے۔ یہ 10 منٹ چلے گا۔`,
    create: "اکاؤنٹ بنائیں", forgot: "پاس ورڈ بھول گئے؟", toCreate: "نئے ہیں؟ اکاؤنٹ بنائیں", toSignIn: "اکاؤنٹ ہے؟ سائن اِن کریں",
    save: "محفوظ کریں", or: "یا", show: "دکھائیں", hide: "چھپائیں",
    replaceNote: "سائن اِن کرنے سے اس فون کا ریکارڈ آپ کے اکاؤنٹ والے ریکارڈ سے بدل جائے گا۔",
    keepNote: "اس فون پر آپ کا نام اور ریکارڈ نئے اکاؤنٹ میں چلا جائے گا۔",
    errEmail: "درست ای میل لکھیں۔", errPassword: "کم از کم 8 حروف، ایک حرف اور ایک ہندسہ۔", errCode: "ای میل والے 6 ہندسے لکھیں۔",
    errInvalidCode: "کوڈ غلط ہے یا ختم ہو گیا۔", errCredentials: "ای میل یا پاس ورڈ غلط ہے۔", errCurrent: "موجودہ پاس ورڈ غلط ہے۔",
    errTaken: "اس ای میل کا اکاؤنٹ پہلے سے ہے۔ سائن اِن کریں۔", errExists: "اس پروفائل کا اکاؤنٹ پہلے سے ہے۔",
    errProtected: "اس پروفائل کا سائن اِن والدین ہی بنا سکتے ہیں۔", errRate: "بہت کوششیں ہو گئیں۔ ایک منٹ رکیں۔", errOffline: "انٹرنیٹ نہیں۔ دوبارہ کوشش کریں۔",
    errUnavailable: "ای میل سے سائن اِن ابھی دستیاب نہیں۔", errBanned: "یہ اکاؤنٹ ابھی سائن اِن نہیں کر سکتا۔", errExpired: "دوبارہ سائن اِن کریں۔",
    errFailed: "کچھ گڑبڑ ہو گئی۔ دوبارہ کوشش کریں۔",
    welcome: "سائن اِن ہو گیا۔", created: "اکاؤنٹ بن گیا۔ آپ کا ریکارڈ محفوظ ہے۔", passwordSaved: "پاس ورڈ بدل گیا۔",
    devicesTitle: "آپ کے آلات", devicesHint: "دیکھیں کہاں سائن اِن ہے", thisPhone: "یہ فون",
    unknownDevice: "نامعلوم آلہ", activeToday: "آج فعال", lastActive: (date: string) => `آخری بار فعال ${date}`,
    signOutDeviceTitle: "اس آلے سے سائن آؤٹ کریں؟", signOutDeviceBody: "اکاؤنٹ استعمال کرنے کے لیے اسے دوبارہ سائن اِن کرنا ہو گا۔", signOutDeviceDo: "سائن آؤٹ",
    deviceSignedOut: "آلے سے سائن آؤٹ ہو گیا۔", noOthers: "کوئی اور آلہ سائن اِن نہیں۔",
  },
  hi: {
    signInTitle: "साइन-इन", createTitle: "खाता बनाएँ", forgotTitle: "पासवर्ड बदलें", changeTitle: "पासवर्ड बदलें",
    email: "ईमेल", password: "पासवर्ड", newPassword: "नया पासवर्ड", currentPassword: "मौजूदा पासवर्ड", code: "6 अंकों का कोड",
    emailPh: "you@example.com", passwordRule: "कम से कम 8 अक्षर, एक अक्षर और एक अंक ज़रूरी।",
    signIn: "साइन-इन", useCode: "इसके बजाय ईमेल पर कोड भेजें", usePassword: "पासवर्ड से", sendCode: "कोड भेजें", resend: "नया कोड भेजें",
    codeSent: (email: string) => `हमने ${email} पर कोड भेजा है। यह 10 मिनट चलेगा।`,
    create: "खाता बनाएँ", forgot: "पासवर्ड भूल गए?", toCreate: "नए हैं? खाता बनाएँ", toSignIn: "खाता है? साइन-इन करें",
    save: "सहेजें", or: "या", show: "दिखाएँ", hide: "छिपाएँ",
    replaceNote: "साइन-इन करने पर इस फ़ोन का रिकॉर्ड आपके खाते वाले रिकॉर्ड से बदल जाएगा।",
    keepNote: "इस फ़ोन पर आपका नाम और रिकॉर्ड नए खाते में चला जाएगा।",
    errEmail: "सही ईमेल लिखें।", errPassword: "कम से कम 8 अक्षर, एक अक्षर और एक अंक।", errCode: "ईमेल वाले 6 अंक लिखें।",
    errInvalidCode: "कोड गलत है या ख़त्म हो गया।", errCredentials: "ईमेल या पासवर्ड गलत है।", errCurrent: "मौजूदा पासवर्ड गलत है।",
    errTaken: "इस ईमेल का खाता पहले से है। साइन-इन करें।", errExists: "इस प्रोफ़ाइल का खाता पहले से है।",
    errProtected: "इस प्रोफ़ाइल का साइन-इन माता-पिता ही बना सकते हैं।", errRate: "बहुत कोशिशें हो गईं। एक मिनट रुकें।", errOffline: "इंटरनेट नहीं। फिर कोशिश करें।",
    errUnavailable: "ईमेल से साइन-इन अभी उपलब्ध नहीं।", errBanned: "यह खाता अभी साइन-इन नहीं कर सकता।", errExpired: "फिर से साइन-इन करें।",
    errFailed: "कुछ गड़बड़ हो गई। फिर कोशिश करें।",
    welcome: "साइन-इन हो गया।", created: "खाता बन गया। आपका रिकॉर्ड सुरक्षित है।", passwordSaved: "पासवर्ड बदल गया।",
    devicesTitle: "आपके डिवाइस", devicesHint: "देखें कहाँ साइन-इन है", thisPhone: "यह फ़ोन",
    unknownDevice: "अनजान डिवाइस", activeToday: "आज सक्रिय", lastActive: (date: string) => `आख़िरी बार सक्रिय ${date}`,
    signOutDeviceTitle: "इस डिवाइस से साइन-आउट करें?", signOutDeviceBody: "खाता इस्तेमाल करने के लिए इसे फिर से साइन-इन करना होगा।", signOutDeviceDo: "साइन-आउट",
    deviceSignedOut: "डिवाइस से साइन-आउट हो गया।", noOthers: "कोई और डिवाइस साइन-इन नहीं है।",
  },
  ne: {
    signInTitle: "साइन-इन", createTitle: "खाता बनाउनुहोस्", forgotTitle: "पासवर्ड नयाँ बनाउनुहोस्", changeTitle: "पासवर्ड बदल्नुहोस्",
    email: "इमेल", password: "पासवर्ड", newPassword: "नयाँ पासवर्ड", currentPassword: "हालको पासवर्ड", code: "६ अङ्कको कोड",
    emailPh: "you@example.com", passwordRule: "कम्तीमा ८ अक्षर, एउटा अक्षर र एउटा अङ्क चाहिन्छ।",
    signIn: "साइन-इन", useCode: "बरु इमेलमा कोड पठाउनुहोस्", usePassword: "पासवर्डबाट", sendCode: "कोड पठाउनुहोस्", resend: "नयाँ कोड पठाउनुहोस्",
    codeSent: (email: string) => `हामीले ${email} मा कोड पठायौँ। यो १० मिनेट चल्छ।`,
    create: "खाता बनाउनुहोस्", forgot: "पासवर्ड बिर्सनुभयो?", toCreate: "नयाँ हुनुहुन्छ? खाता बनाउनुहोस्", toSignIn: "खाता छ? साइन-इन गर्नुहोस्",
    save: "सेभ गर्नुहोस्", or: "वा", show: "देखाउनुहोस्", hide: "लुकाउनुहोस्",
    replaceNote: "साइन-इन गर्दा यो फोनको रेकर्ड तपाईंको खाताको रेकर्डले बदलिन्छ।",
    keepNote: "यो फोनमा भएको तपाईंको नाम र रेकर्ड नयाँ खातामा जान्छ।",
    errEmail: "सही इमेल लेख्नुहोस्।", errPassword: "कम्तीमा ८ अक्षर, एउटा अक्षर र एउटा अङ्क।", errCode: "इमेलमा आएका ६ अङ्क लेख्नुहोस्।",
    errInvalidCode: "कोड गलत छ वा सकियो।", errCredentials: "इमेल वा पासवर्ड गलत छ।", errCurrent: "हालको पासवर्ड गलत छ।",
    errTaken: "यो इमेलको खाता पहिल्यै छ। साइन-इन गर्नुहोस्।", errExists: "यो प्रोफाइलको खाता पहिल्यै छ।",
    errProtected: "यो प्रोफाइलको साइन-इन अभिभावकले मात्र बनाउन सक्नुहुन्छ।", errRate: "धेरै प्रयास भयो। एक मिनेट पर्खनुहोस्।", errOffline: "इन्टरनेट छैन। फेरि प्रयास गर्नुहोस्।",
    errUnavailable: "इमेलबाट साइन-इन अहिले उपलब्ध छैन।", errBanned: "यो खाताले अहिले साइन-इन गर्न सक्दैन।", errExpired: "फेरि साइन-इन गर्नुहोस्।",
    errFailed: "केही गडबड भयो। फेरि प्रयास गर्नुहोस्।",
    welcome: "साइन-इन भयो।", created: "खाता बन्यो। तपाईंको रेकर्ड सुरक्षित छ।", passwordSaved: "पासवर्ड बदलियो।",
    devicesTitle: "तपाईंका डिभाइस", devicesHint: "कहाँ साइन-इन छ हेर्नुहोस्", thisPhone: "यो फोन",
    unknownDevice: "अज्ञात डिभाइस", activeToday: "आज सक्रिय", lastActive: (date: string) => `अन्तिम पटक सक्रिय ${date}`,
    signOutDeviceTitle: "यो डिभाइसबाट साइन-आउट गर्ने?", signOutDeviceBody: "खाता चलाउन यसलाई फेरि साइन-इन गर्नुपर्छ।", signOutDeviceDo: "साइन-आउट",
    deviceSignedOut: "डिभाइसबाट साइन-आउट भयो।", noOthers: "अरू कुनै डिभाइस साइन-इन छैन।",
  },
  bn: {
    signInTitle: "সাইন-ইন", createTitle: "অ্যাকাউন্ট খুলুন", forgotTitle: "পাসওয়ার্ড নতুন করুন", changeTitle: "পাসওয়ার্ড বদলান",
    email: "ইমেল", password: "পাসওয়ার্ড", newPassword: "নতুন পাসওয়ার্ড", currentPassword: "বর্তমান পাসওয়ার্ড", code: "৬ অঙ্কের কোড",
    emailPh: "you@example.com", passwordRule: "অন্তত ৮ অক্ষর, একটি অক্ষর ও একটি সংখ্যা লাগবে।",
    signIn: "সাইন-ইন", useCode: "বরং ইমেলে কোড পাঠান", usePassword: "পাসওয়ার্ড দিয়ে", sendCode: "কোড পাঠান", resend: "নতুন কোড পাঠান",
    codeSent: (email: string) => `আমরা ${email}-এ কোড পাঠিয়েছি। এটি ১০ মিনিট কাজ করবে।`,
    create: "অ্যাকাউন্ট খুলুন", forgot: "পাসওয়ার্ড ভুলে গেছেন?", toCreate: "নতুন? অ্যাকাউন্ট খুলুন", toSignIn: "অ্যাকাউন্ট আছে? সাইন-ইন করুন",
    save: "সেভ করুন", or: "বা", show: "দেখান", hide: "লুকান",
    replaceNote: "সাইন-ইন করলে এই ফোনের রেকর্ড আপনার অ্যাকাউন্টের রেকর্ডে বদলে যাবে।",
    keepNote: "এই ফোনের আপনার নাম ও রেকর্ড নতুন অ্যাকাউন্টে চলে যাবে।",
    errEmail: "সঠিক ইমেল লিখুন।", errPassword: "অন্তত ৮ অক্ষর, একটি অক্ষর ও একটি সংখ্যা।", errCode: "ইমেলের ৬টি অঙ্ক লিখুন।",
    errInvalidCode: "কোড ভুল বা মেয়াদ শেষ।", errCredentials: "ইমেল বা পাসওয়ার্ড ভুল।", errCurrent: "বর্তমান পাসওয়ার্ড ভুল।",
    errTaken: "এই ইমেলে আগেই অ্যাকাউন্ট আছে। সাইন-ইন করুন।", errExists: "এই প্রোফাইলে আগেই অ্যাকাউন্ট আছে।",
    errProtected: "এই প্রোফাইলের সাইন-ইন শুধু অভিভাবক চালু করতে পারেন।", errRate: "অনেক চেষ্টা হয়েছে। এক মিনিট অপেক্ষা করুন।", errOffline: "ইন্টারনেট নেই। আবার চেষ্টা করুন।",
    errUnavailable: "ইমেল দিয়ে সাইন-ইন এখন পাওয়া যাচ্ছে না।", errBanned: "এই অ্যাকাউন্ট এখন সাইন-ইন করতে পারবে না।", errExpired: "আবার সাইন-ইন করুন।",
    errFailed: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
    welcome: "সাইন-ইন হয়েছে।", created: "অ্যাকাউন্ট খোলা হয়েছে। আপনার রেকর্ড সুরক্ষিত।", passwordSaved: "পাসওয়ার্ড বদলানো হয়েছে।",
    devicesTitle: "আপনার ডিভাইস", devicesHint: "কোথায় সাইন-ইন আছে দেখুন", thisPhone: "এই ফোন",
    unknownDevice: "অজানা ডিভাইস", activeToday: "আজ সক্রিয়", lastActive: (date: string) => `শেষ সক্রিয় ${date}`,
    signOutDeviceTitle: "এই ডিভাইস থেকে সাইন-আউট করবেন?", signOutDeviceBody: "অ্যাকাউন্ট ব্যবহার করতে এটিকে আবার সাইন-ইন করতে হবে।", signOutDeviceDo: "সাইন-আউট",
    deviceSignedOut: "ডিভাইস থেকে সাইন-আউট হয়েছে।", noOthers: "আর কোনো ডিভাইস সাইন-ইন নেই।",
  },
});
