/** All player-facing text for the settings screens, kept together (English only for now). */
export const T = {
  settings: {
    title: "Settings",
    looks: "How it looks", playing: "Playing", sound: "Sound and feel", language: "Language", parent: "Parent controls",
    howto: "How to play", howtoHint: "Rules in brief, and a teaching hand", rules: "Rules and terms", rulesHint: "Every game, every word",
    account: "Account and data", accountHint: "On this phone only", reset: "Start again", resetHint: "Deletes your profile from this phone",
    pinSet: "PIN set", pinNone: "No PIN yet",
    on: "on", off: "off", hints: "Hints", clock: "clock", haptics: "haptics", silent: "Silent", soundOn: "Sound on",
    themes: { system: "System", light: "Light", dark: "Dark" },
    langNames: { en: "English", ur: "Urdu", hi: "Hindi", ne: "Nepali", bn: "Bangla" },
    aboutTitle: "About",
    version: (v: string) => `TashZone ${v}`,
    nameAvatar: "Your name and avatar",
  },
  looks: {
    title: "How it looks",
    theme: "Theme", themeHint: "System follows your phone's light or dark setting",
    cards: "Cards",
    four: "Four-colour deck", fourHint: "Diamonds blue, clubs green",
    large: "Large cards", largeHint: "Bigger faces, fewer in a row",
    motion: "Reduced motion", motionHint: "Cards move without flourish",
    designs: "Table designs", designsHint: "Preview the cloths, coming soon",
  },
  play: {
    title: "Playing",
    hints: "Highlight playable cards", hintsHint: "Legal cards rise, the rest step back",
    timer: "Turn clock", timerHint: "When time runs out a card is played for you",
    easy: "Easy mode", easyHint: "Bigger cards, four colours, hints on, no clock",
  },
  sound: {
    title: "Sound and feel",
    master: "Table sound", masterHint: "Cards, sweeps and the thulla slam",
    effects: "Sound effects", effectsHint: "Short sounds for moves",
    haptics: "Haptics", hapticsHint: "A short buzz when a card lands",
    note: "These switches are saved now. Audio and haptic playback are not built into the app yet, so nothing will sound or buzz until they are.",
  },
  parent: {
    title: "Parent controls",
    noPinTitle: "No PIN set", noPinBody: "Without a PIN anyone using this phone can change these switches.",
    text: "Free-text chat", textHint: "Quick-chat phrases stay available either way",
    online: "Online play", onlineHint: "Rooms and matches over the internet",
    wifi: "Wi-Fi tables", wifiHint: "Host or join a table on the same network",
    installTitle: "These settings belong to this app install.",
    installBody: "If TashZone is reinstalled, or its data cleared, they go back to their defaults.",
    setPin: "Set a PIN", changePin: "Change the PIN", removePin: "Remove the PIN",
    lockedTitle: "Parent controls are locked", enterPin: "Enter the parent PIN",
    lockedFor: (s: number) => `Too many wrong tries. Try again in ${s} s.`,
    wrong: (left: number) => `That PIN is not right. ${left} ${left === 1 ? "try" : "tries"} left.`,
    unlock: "Unlock",
  },
  pin: {
    title: "Parent PIN",
    intro: "Four digits. It protects the parent switches, nothing else.",
    current: "Enter the current PIN", fresh: "Choose a new PIN", confirm: "Enter it again to confirm",
    mismatch: "The two PINs did not match. Start again.",
    saved: "PIN saved",
    checking: "Checking",
  },
  account: {
    title: "Account and data",
    noAccountTitle: "No account, nothing leaves this phone",
    noAccountBody: "TashZone has no sign-in and no cloud copy. Your name, stats and settings are stored on this device only. Uninstalling the app or clearing its data removes them, and they cannot be recovered. Use the backup below to keep a copy yourself.",
    backup: "Share a backup", backupHint: "Name, avatar, stats and settings as text (no PIN)",
    restore: "Restore from a backup", restoreHint: "Paste text you saved earlier",
    restoreTitle: "Restore from a backup", restoreBody: "Paste the backup text. It replaces your name, avatar, stats and play settings. Parent controls are kept as they are.",
    restorePlaceholder: "Paste backup text here", restoreDo: "Restore", restoreBad: "That is not a TashZone backup.", restored: "Backup restored",
    wipe: "Delete everything", wipeHint: "Starts again from the first screen",
    wipeTitle: "Delete everything?", wipeBody: "Your name, avatar, stats and settings are removed from this phone. This cannot be undone.",
    wipePin: "Enter the parent PIN to delete everything", wipeDo: "Delete", cancel: "Cancel", close: "Close",
    protectedOn: "Protected Mode is on. Typing to other players is turned off.", protectedOff: "Protected Mode is off.",
    shareMsgTitle: "TashZone backup",
  },
  themes: {
    title: "Table designs",
    intro: "Cloths from across the region. A design changes the felt only, never the cards and never what you can see.",
    soon: "Coming soon",
    note: "The table still uses the standard green felt. These are previews of what is planned; choosing one is not possible yet.",
  },
} as const;
