import { localized } from "../../i18n";

export const T = localized("settings", {
  en: {
    settings: {
      title: "Settings",
      looks: "Appearance", playing: "Gameplay", sound: "Sound and feel", language: "Language", parent: "Parent controls",
      howto: "How to play", howtoHint: "Quick rules and a practice hand", rules: "Rules and terms", rulesHint: "Every game, every term",
      account: "Account and data", accountHint: "On this phone only", reset: "Start again", resetHint: "Erases your profile from this phone",
      pinSet: "PIN set", pinNone: "No PIN yet",
      on: "on", off: "off", hints: "Hints", clock: "timer", haptics: "haptics", silent: "Silent", soundOn: "Sound on",
      playLine: (hints: boolean, clock: boolean) => `Hints ${hints ? "on" : "off"} · timer ${clock ? "on" : "off"}`,
      soundLine: (sound: boolean, haptics: boolean) => `${sound ? "Sound on" : "Silent"} · haptics ${haptics ? "on" : "off"}`,
      groupLook: "Look, play and sound", groupFamily: "Family and data", groupHelp: "Help",
      fourColor: "four-colour deck", calm: "reduced motion", pinBadge: "PIN SET", player: "Player",
      profileLabel: (name: string) => `${name || "Your profile"}. Edit name and avatar`,
      statsLine: (matches: number, wins: number) => `${matches} ${matches === 1 ? "match" : "matches"} · ${wins} ${wins === 1 ? "win" : "wins"}`,
      about: "About TashZone", aboutHint: "Fair deals, privacy, credits",
      langNames: { en: "English", ur: "Urdu", hi: "Hindi", ne: "Nepali", bn: "Bangla" },
      aboutTitle: "About",
      version: (v: string) => `TashZone ${v}`,
      nameAvatar: "Name and avatar",
    },
    about: {
      share: "Share TashZone",
      shareMsg: (ready: number, more: number) => `Play South Asian card games on TashZone: ${ready} ready now, ${more} on the way. Fair deals, works offline.`,
      version: (v: string, room: string) => `Version ${v} · ${room} room`,
      sep: ", ",
      fairT: "Fair deals", fairB: "Every shuffle uses secure randomness. No difficulty tuning, no rigged cards, no house edge.",
      privateT: "Private by design", privateB: "No account, no trackers, no ads. Your profile, record and settings stay on this phone.",
      gamesT: "Regional games",
      gamesB: (n: number, names: string, more: number) => `${n} ${n === 1 ? "game" : "games"} ready to play: ${names}. ${more} more on the way.`,
      creditsT: "Credits", creditsB: "Fonts Jost, Cormorant Garamond, Bodoni Moda and Noto Nastaliq Urdu, used under the SIL Open Font License 1.1.",
    },
    looks: {
      title: "Appearance",
      room: "Room",
      festival: "Festival room",
      until: (date: string) => `Until ${date}`,
      cards: "Cards",
      four: "Four-colour deck", fourHint: "Blue diamonds, green clubs",
      large: "Large cards", largeHint: "Bigger faces, fewer per row",
      motion: "Reduced motion", motionHint: "Fades instead of movement. Also follows your phone's setting",
      orientation: "Screen", orientAuto: "Rotate", orientPortrait: "Portrait", orientLandscape: "Landscape",
      designs: "Table designs", designsHint: "Cloth previews, coming soon",
    },
    play: {
      title: "Gameplay",
      hints: "Highlight playable cards", hintsHint: "Legal cards rise, the rest dim",
      timer: "Turn timer", timerHint: "When time runs out, a card is played for you",
      easy: "Easy mode", easyHint: "Bigger cards, four colours, hints on, no timer",
    },
    sound: {
      title: "Sound and feel",
      master: "Sound", masterHint: "Every sound in the app",
      effects: "Table sounds", effectsHint: "Each room has its own: tabla, brass or arcade",
      haptics: "Haptics", hapticsHint: "A light tap when a card lands",
      volume: "Volume",
      strength: "Haptic strength", strengthHint: "Soft in Mehfil, firmer in Darbar and Arcade",
      hapticOff: "Off", hapticGentle: "Gentle", hapticCrisp: "Crisp", hapticFirm: "Firm",
    },
    parent: {
      title: "Parent controls",
      noPinTitle: "No PIN set", noPinBody: "Without a PIN, anyone on this phone can change these switches.",
      text: "Typed chat", textHint: "Quick-chat phrases always stay on",
      online: "Online play", onlineHint: "Rooms and matches over the internet",
      wifi: "Wi-Fi tables", wifiHint: "Host or join a table on the same network",
      installTitle: "These settings belong to this install.",
      installBody: "Reinstalling TashZone or clearing its data resets them.",
      setPin: "Set PIN", changePin: "Change PIN", removePin: "Remove PIN",
      lockedTitle: "Parent controls locked", enterPin: "Enter parent PIN",
      lockedFor: (s: number) => `Too many wrong tries. Try again in ${s} s.`,
      wrong: (left: number) => `Wrong PIN. ${left} ${left === 1 ? "try" : "tries"} left.`,
      unlock: "Unlock",
    },
    pin: {
      title: "Parent PIN",
      intro: "Four digits. It guards only the parent switches.",
      current: "Enter current PIN", fresh: "Choose a new PIN", confirm: "Enter it again",
      mismatch: "PINs didn't match. Try again.",
      saved: "PIN saved",
      checking: "Checking",
    },
    account: {
      title: "Account and data",
      noAccountTitle: "Your profile lives on this phone.",
      noAccountBody: "Nothing leaves this phone unless you play online or sign in. Sign in to get your name and record back on a new phone. We keep only an account ID, never your email or name.",
      signInTitle: "Sign in (optional)", google: "Sign in with Google", playGames: "Sign in with Play Games",
      linked: "Linked", unlink: "Unlink", signedIn: "Signed in. Your record is backed up.",
      restoredMsg: "Profile restored.", takenTitle: "Profile found", takenBody: "This account already has a TashZone profile. Switch to it? This phone's record will be replaced.",
      switchDo: "Switch", pinToSignIn: "Enter parent PIN to sign in", askParent: "Ask a parent to set a PIN, then sign in.",
      errNoAccount: "No Google account on this phone.", errUnavailable: "Sign-in isn't available right now.", errInvalid: "Couldn't verify that sign-in. Try again.",
      errOffline: "No connection. Try again.", errOther: "A different account is already linked.", errFailed: "Sign-in failed. Try again.",
      signedInAs: (email: string) => `Signed in as ${email}`, signOut: "Sign out", signOutHint: "This phone goes back to a guest profile",
      signOutAll: "Sign out on other phones", signOutAllHint: "Keeps this phone signed in", signOutAllDone: "Other phones are signed out.",
      signOutTitle: "Sign out?", signOutBody: "Your record stays in your account. This phone starts again as a guest.", signOutDo: "Sign out",
      passwordHint: "Needs your current password",
      backup: "Share a backup", backupHint: "Name, avatar, record and settings as text (no PIN)",
      restore: "Restore a backup", restoreHint: "Paste text you saved earlier",
      restoreTitle: "Restore a backup", restoreBody: "Paste your backup text. It replaces your name, avatar, record and play settings. Parent controls stay as they are.",
      restorePlaceholder: "Paste backup text here", restoreDo: "Restore", restoreBad: "That's not a TashZone backup.", restored: "Backup restored",
      wipe: "Delete everything", wipeHint: "Back to the first screen",
      wipeTitle: "Delete everything?", wipeBody: "Your name, avatar, record and settings will be removed from this phone. This can't be undone.",
      wipePin: "Enter parent PIN to delete everything", wipeDo: "Delete", cancel: "Cancel", close: "Close",
      protectedOn: "Protected Mode is on. Typed chat is off.", protectedOff: "Protected Mode is off.",
      shareMsgTitle: "TashZone backup",
    },
    themes: {
      title: "Table designs",
      intro: "Cloths from across the region. A design changes only the felt, never the cards or what you can see.",
      soon: "Coming soon",
      note: "The table still uses plain green felt. These are previews; you can't pick one yet.",
      designs: [
        "Truck art", "Ajrak", "Multani blue", "Phulkari", "Chiniot wood", "Balochi mirror", "Sindhi rilli", "Camel lamp", "Warli", "Bandhani",
        "Jaipur print", "Kalamkari", "Nakshi kantha", "Jamdani", "Rickshaw art", "Terracotta", "Mithila", "Newari window", "Dhaka fabric",
      ],
    },
    parentExtra: {
      lockedFor: (s: number) => `Too many wrong tries. Try again in ${s >= 60 ? `${Math.ceil(s / 60)} min` : `${s} s`}.`,
      checkFailed: "Couldn't check the PIN. Try again.",
      saveFailed: "Couldn't save the PIN. Try again.",
      removeTitle: "Remove parent PIN?",
      removeFacts: [
        { mark: "1", title: "Anyone can change these switches", body: "Without a PIN, anyone on this phone can turn chat, online play and Wi-Fi tables on or off." },
        { mark: "2", title: "Set a new PIN any time", body: "Parent controls keep their current settings." },
      ],
      removeDo: "Remove PIN",
      keep: "Keep PIN",
    },
  } as const,
  ur: {
    settings: {
      title: "ترتیبات",
      looks: "انداز", playing: "کھیل", sound: "آواز اور وائبریشن", language: "زبان", parent: "والدین کے کنٹرول",
      howto: "کیسے کھیلیں", howtoHint: "مختصر قوانین اور مشق کی بازی", rules: "قوانین اور اصطلاحات", rulesHint: "ہر کھیل، ہر اصطلاح",
      account: "اکاؤنٹ اور ڈیٹا", accountHint: "صرف اسی فون پر", reset: "نئے سرے سے شروع", resetHint: "اس فون سے آپ کی پروفائل مٹ جائے گی",
      pinSet: "PIN لگا ہے", pinNone: "ابھی PIN نہیں",
      on: "آن", off: "آف", hints: "مشورے", clock: "ٹائمر", haptics: "وائبریشن", silent: "خاموش", soundOn: "آواز آن",
      playLine: (hints: boolean, clock: boolean) => `مشورے ${hints ? "آن" : "آف"} · ٹائمر ${clock ? "آن" : "آف"}`,
      soundLine: (sound: boolean, haptics: boolean) => `${sound ? "آواز آن" : "خاموش"} · وائبریشن ${haptics ? "آن" : "آف"}`,
      groupLook: "انداز، کھیل اور آواز", groupFamily: "خاندان اور ڈیٹا", groupHelp: "مدد",
      fourColor: "چار رنگوں والی گڈی", calm: "کم حرکت", pinBadge: "PIN لگا ہے", player: "کھلاڑی",
      profileLabel: (name: string) => `${name || "آپ کی پروفائل"}۔ نام اور اوتار بدلیں`,
      statsLine: (matches: number, wins: number) => `${matches} میچ · ${wins} جیت`,
      about: "TashZone کے بارے میں", aboutHint: "منصفانہ بانٹ، پرائیویسی، کریڈٹس",
      langNames: { en: "انگریزی", ur: "اردو", hi: "ہندی", ne: "نیپالی", bn: "بنگلہ" },
      aboutTitle: "تعارف",
      version: (v: string) => `TashZone ${v}`,
      nameAvatar: "نام اور اوتار",
    },
    about: {
      share: "TashZone شیئر کریں",
      shareMsg: (ready: number, more: number) => `TashZone پر جنوبی ایشیا کے تاش کے کھیل کھیلیں: ${ready} تیار، ${more} مزید آ رہے ہیں۔ منصفانہ بانٹ، انٹرنیٹ کے بغیر بھی۔`,
      version: (v: string, room: string) => `ورژن ${v} · ${room} روم`,
      sep: "، ",
      fairT: "منصفانہ بانٹ", fairB: "ہر بار پتے محفوظ طریقے سے بے ترتیب پھینٹے جاتے ہیں۔ نہ مشکل میں ردوبدل، نہ پتوں میں ہیرا پھیری، نہ ایپ کا کوئی فائدہ۔",
      privateT: "ہر لحاظ سے نجی", privateB: "نہ اکاؤنٹ، نہ ٹریکر، نہ اشتہار۔ آپ کی پروفائل، ریکارڈ اور ترتیبات اسی فون پر رہتی ہیں۔",
      gamesT: "علاقائی کھیل",
      gamesB: (n: number, names: string, more: number) => `${n} کھیل ابھی کھیلنے کو تیار: ${names}۔ ${more} مزید آ رہے ہیں۔`,
      creditsT: "کریڈٹس", creditsB: "فونٹس Jost، Cormorant Garamond، Bodoni Moda اور Noto Nastaliq Urdu، SIL Open Font License 1.1 کے تحت۔",
    },
    looks: {
      title: "انداز",
      room: "روم",
      festival: "تہوار کا روم",
      until: (date: string) => `${date} تک`,
      cards: "پتے",
      four: "چار رنگوں والی گڈی", fourHint: "اینٹ نیلی، چڑیا سبز",
      large: "بڑے پتے", largeHint: "بڑی شکلیں، قطار میں کم پتے",
      motion: "کم حرکت", motionHint: "حرکت کی جگہ ہلکا سا فیڈ۔ فون کی ترتیب بھی مانتا ہے",
      orientation: "اسکرین", orientAuto: "خودکار", orientPortrait: "عمودی", orientLandscape: "افقی",
      designs: "میز کے ڈیزائن", designsHint: "کپڑوں کی جھلک، جلد آ رہے ہیں",
    },
    play: {
      title: "کھیل",
      hints: "چلنے والے پتے نمایاں کریں", hintsHint: "جائز پتے اوپر، باقی مدھم",
      timer: "باری کا ٹائمر", timerHint: "وقت ختم ہو تو آپ کی جگہ پتا چل دیا جاتا ہے",
      easy: "آسان موڈ", easyHint: "بڑے پتے، چار رنگ، مشورے آن، ٹائمر نہیں",
    },
    sound: {
      title: "آواز اور وائبریشن",
      master: "آواز", masterHint: "ایپ کی ہر آواز",
      effects: "میز کی آوازیں", effectsHint: "ہر روم کی اپنی: طبلہ، پیتل یا آرکیڈ",
      haptics: "وائبریشن", hapticsHint: "پتا گرنے پر ہلکی سی تھرتھراہٹ",
      volume: "والیوم",
      strength: "وائبریشن کی شدت", strengthHint: "محفل میں ہلکی، دربار اور آرکیڈ میں تیز",
      hapticOff: "آف", hapticGentle: "ہلکی", hapticCrisp: "واضح", hapticFirm: "تیز",
    },
    parent: {
      title: "والدین کے کنٹرول",
      noPinTitle: "PIN نہیں لگا", noPinBody: "PIN کے بغیر اس فون پر کوئی بھی یہ سوئچ بدل سکتا ہے۔",
      text: "لکھ کر چیٹ", textHint: "فوری چیٹ کے جملے ہر حال میں آن رہتے ہیں",
      online: "آن لائن کھیل", onlineHint: "انٹرنیٹ پر روم اور میچ",
      wifi: "Wi-Fi میزیں", wifiHint: "ایک ہی نیٹ ورک پر میز لگائیں یا شامل ہوں",
      installTitle: "یہ ترتیبات صرف اسی انسٹال کی ہیں۔",
      installBody: "TashZone دوبارہ انسٹال کرنے یا ڈیٹا صاف کرنے پر یہ پہلے جیسی ہو جاتی ہیں۔",
      setPin: "PIN لگائیں", changePin: "PIN بدلیں", removePin: "PIN ہٹائیں",
      lockedTitle: "والدین کے کنٹرول لاک ہیں", enterPin: "والدین کا PIN درج کریں",
      lockedFor: (s: number) => `بہت سی غلط کوششیں۔ ${s} سیکنڈ بعد دوبارہ کوشش کریں۔`,
      wrong: (left: number) => `غلط PIN۔ ${left} ${left === 1 ? "کوشش" : "کوششیں"} باقی۔`,
      unlock: "کھولیں",
    },
    pin: {
      title: "والدین کا PIN",
      intro: "چار ہندسے۔ یہ صرف والدین کے سوئچ محفوظ رکھتا ہے۔",
      current: "موجودہ PIN درج کریں", fresh: "نیا PIN چنیں", confirm: "دوبارہ درج کریں",
      mismatch: "دونوں PIN ایک جیسے نہیں۔ دوبارہ کوشش کریں۔",
      saved: "PIN محفوظ ہو گیا",
      checking: "جانچ ہو رہی ہے",
    },
    account: {
      title: "اکاؤنٹ اور ڈیٹا",
      noAccountTitle: "آپ کی پروفائل اسی فون پر ہے۔",
      noAccountBody: "آن لائن کھیلے یا سائن اِن کیے بغیر کچھ بھی فون سے باہر نہیں جاتا۔ سائن اِن کریں تو نئے فون پر آپ کا نام اور ریکارڈ واپس مل جائے گا۔ ہم صرف اکاؤنٹ ID رکھتے ہیں، ای میل یا نام کبھی نہیں۔",
      signInTitle: "سائن اِن (اختیاری)", google: "Google سے سائن اِن", playGames: "Play Games سے سائن اِن",
      linked: "جڑا ہوا", unlink: "الگ کریں", signedIn: "سائن اِن ہو گیا۔ آپ کا ریکارڈ محفوظ ہے۔",
      restoredMsg: "پروفائل واپس آ گئی۔", takenTitle: "پروفائل مل گئی", takenBody: "اس اکاؤنٹ کی پہلے سے TashZone پروفائل ہے۔ اس پر جائیں؟ اس فون کا ریکارڈ بدل جائے گا۔",
      switchDo: "اس پر جائیں", pinToSignIn: "سائن اِن کے لیے والدین کا PIN ڈالیں", askParent: "والدین سے PIN بنوائیں، پھر سائن اِن کریں۔",
      errNoAccount: "اس فون پر کوئی Google اکاؤنٹ نہیں۔", errUnavailable: "ابھی سائن اِن دستیاب نہیں۔", errInvalid: "سائن اِن کی تصدیق نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
      errOffline: "انٹرنیٹ نہیں۔ دوبارہ کوشش کریں۔", errOther: "ایک اور اکاؤنٹ پہلے سے جڑا ہے۔", errFailed: "سائن اِن نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
      signedInAs: (email: string) => `${email} سے سائن اِن`, signOut: "سائن آؤٹ", signOutHint: "یہ فون مہمان پروفائل پر واپس آ جائے گا",
      signOutAll: "دوسرے فونز سے سائن آؤٹ", signOutAllHint: "یہ فون سائن اِن رہے گا", signOutAllDone: "دوسرے فونز سے سائن آؤٹ ہو گیا۔",
      signOutTitle: "سائن آؤٹ کریں؟", signOutBody: "آپ کا ریکارڈ اکاؤنٹ میں محفوظ رہے گا۔ یہ فون مہمان کے طور پر نئے سرے سے شروع ہو گا۔", signOutDo: "سائن آؤٹ",
      passwordHint: "موجودہ پاس ورڈ چاہیے",
      backup: "بیک اپ شیئر کریں", backupHint: "نام، اوتار، ریکارڈ اور ترتیبات بطور متن (PIN کے بغیر)",
      restore: "بیک اپ بحال کریں", restoreHint: "پہلے محفوظ کیا متن پیسٹ کریں",
      restoreTitle: "بیک اپ بحال کریں", restoreBody: "بیک اپ کا متن پیسٹ کریں۔ اس سے آپ کا نام، اوتار، ریکارڈ اور کھیل کی ترتیبات بدل جائیں گی۔ والدین کے کنٹرول ویسے ہی رہیں گے۔",
      restorePlaceholder: "بیک اپ کا متن یہاں پیسٹ کریں", restoreDo: "بحال کریں", restoreBad: "یہ TashZone کا بیک اپ نہیں۔", restored: "بیک اپ بحال ہو گیا",
      wipe: "سب کچھ مٹائیں", wipeHint: "پہلی اسکرین سے نئی شروعات",
      wipeTitle: "سب کچھ مٹا دیں؟", wipeBody: "آپ کا نام، اوتار، ریکارڈ اور ترتیبات اس فون سے مٹ جائیں گی۔ یہ واپس نہیں ہو سکتا۔",
      wipePin: "سب کچھ مٹانے کے لیے والدین کا PIN درج کریں", wipeDo: "مٹائیں", cancel: "منسوخ", close: "بند کریں",
      protectedOn: "محفوظ موڈ آن ہے۔ لکھ کر چیٹ بند ہے۔", protectedOff: "محفوظ موڈ آف ہے۔",
      shareMsgTitle: "TashZone بیک اپ",
    },
    themes: {
      title: "میز کے ڈیزائن",
      intro: "پورے خطے کے کپڑے۔ ڈیزائن صرف میز کا کپڑا بدلتا ہے، پتے یا باقی کچھ نہیں۔",
      soon: "جلد آ رہا ہے",
      note: "میز پر ابھی سادہ سبز کپڑا ہی ہے۔ یہ صرف جھلک ہے؛ ابھی کوئی چن نہیں سکتے۔",
      designs: [
        "ٹرک آرٹ", "اجرک", "ملتانی نیلا", "پھلکاری", "چنیوٹی لکڑی", "بلوچی شیشہ کاری", "سندھی رِلی", "اونٹ کھال لیمپ", "وارلی", "باندھنی",
        "جے پوری چھاپہ", "قلم کاری", "نقشی کانتھا", "جامدانی", "رکشہ آرٹ", "ٹیراکوٹا", "مِتھلا", "نیواری کھڑکی", "ڈھاکہ کا کپڑا",
      ],
    },
    parentExtra: {
      lockedFor: (s: number) => `بہت سی غلط کوششیں۔ ${s >= 60 ? `${Math.ceil(s / 60)} منٹ` : `${s} سیکنڈ`} بعد دوبارہ کوشش کریں۔`,
      checkFailed: "PIN جانچا نہیں جا سکا۔ دوبارہ کوشش کریں۔",
      saveFailed: "PIN محفوظ نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
      removeTitle: "والدین کا PIN ہٹا دیں؟",
      removeFacts: [
        { mark: "1", title: "کوئی بھی یہ سوئچ بدل سکے گا", body: "PIN کے بغیر اس فون پر کوئی بھی چیٹ، آن لائن کھیل اور Wi-Fi میزیں آن یا آف کر سکتا ہے۔" },
        { mark: "2", title: "نیا PIN کبھی بھی لگا سکتے ہیں", body: "والدین کے کنٹرول کی موجودہ ترتیبات برقرار رہیں گی۔" },
      ],
      removeDo: "PIN ہٹائیں",
      keep: "PIN رہنے دیں",
    },
  },
  hi: {
    settings: {
      title: "सेटिंग्स",
      looks: "दिखावट", playing: "खेल", sound: "आवाज़ और वाइब्रेशन", language: "भाषा", parent: "पैरेंट कंट्रोल",
      howto: "कैसे खेलें", howtoHint: "छोटे नियम और एक अभ्यास बाज़ी", rules: "नियम और शब्द", rulesHint: "हर खेल, हर शब्द",
      account: "खाता और डेटा", accountHint: "सिर्फ़ इसी फ़ोन पर", reset: "फिर से शुरू करें", resetHint: "इस फ़ोन से आपकी प्रोफ़ाइल मिट जाएगी",
      pinSet: "PIN लगा है", pinNone: "अभी PIN नहीं",
      on: "चालू", off: "बंद", hints: "सुझाव", clock: "टाइमर", haptics: "वाइब्रेशन", silent: "म्यूट", soundOn: "आवाज़ चालू",
      playLine: (hints: boolean, clock: boolean) => `सुझाव ${hints ? "चालू" : "बंद"} · टाइमर ${clock ? "चालू" : "बंद"}`,
      soundLine: (sound: boolean, haptics: boolean) => `${sound ? "आवाज़ चालू" : "म्यूट"} · वाइब्रेशन ${haptics ? "चालू" : "बंद"}`,
      groupLook: "दिखावट, खेल और आवाज़", groupFamily: "परिवार और डेटा", groupHelp: "मदद",
      fourColor: "चार रंगों वाली गड्डी", calm: "कम हलचल", pinBadge: "PIN लगा है", player: "खिलाड़ी",
      profileLabel: (name: string) => `${name || "आपकी प्रोफ़ाइल"}. नाम और अवतार बदलें`,
      statsLine: (matches: number, wins: number) => `${matches} मैच · ${wins} जीत`,
      about: "TashZone के बारे में", aboutHint: "निष्पक्ष बँटाई, प्राइवेसी, क्रेडिट",
      langNames: { en: "अंग्रेज़ी", ur: "उर्दू", hi: "हिन्दी", ne: "नेपाली", bn: "बांग्ला" },
      aboutTitle: "परिचय",
      version: (v: string) => `TashZone ${v}`,
      nameAvatar: "नाम और अवतार",
    },
    about: {
      share: "TashZone शेयर करें",
      shareMsg: (ready: number, more: number) => `TashZone पर दक्षिण एशिया के ताश के खेल खेलें: ${ready} तैयार, ${more} और आ रहे हैं। निष्पक्ष बँटाई, बिना इंटरनेट भी।`,
      version: (v: string, room: string) => `वर्ज़न ${v} · ${room} रूम`,
      sep: ", ",
      fairT: "निष्पक्ष बँटाई", fairB: "हर बार पत्ते सुरक्षित रैंडम तरीके से फेंटे जाते हैं। न मुश्किल में हेरफेर, न पत्तों में धांधली, न ऐप का कोई फ़ायदा।",
      privateT: "पूरी तरह निजी", privateB: "न खाता, न ट्रैकर, न विज्ञापन। आपकी प्रोफ़ाइल, रिकॉर्ड और सेटिंग्स इसी फ़ोन पर रहती हैं।",
      gamesT: "क्षेत्रीय खेल",
      gamesB: (n: number, names: string, more: number) => `${n} खेल अभी खेलने को तैयार: ${names}। ${more} और आ रहे हैं।`,
      creditsT: "क्रेडिट", creditsB: "फ़ॉन्ट Jost, Cormorant Garamond, Bodoni Moda और Noto Nastaliq Urdu, SIL Open Font License 1.1 के तहत।",
    },
    looks: {
      title: "दिखावट",
      room: "रूम",
      festival: "त्योहार रूम",
      until: (date: string) => `${date} तक`,
      cards: "पत्ते",
      four: "चार रंगों वाली गड्डी", fourHint: "ईंट नीली, चिड़ी हरी",
      large: "बड़े पत्ते", largeHint: "बड़े चित्र, एक पंक्ति में कम पत्ते",
      motion: "कम हलचल", motionHint: "हिलने की जगह हल्का फ़ेड। फ़ोन की सेटिंग भी मानता है",
      orientation: "स्क्रीन", orientAuto: "ऑटो", orientPortrait: "खड़ी", orientLandscape: "आड़ी",
      designs: "टेबल के डिज़ाइन", designsHint: "कपड़ों की झलक, जल्द आ रहे हैं",
    },
    play: {
      title: "खेल",
      hints: "चलने लायक पत्ते दिखाएँ", hintsHint: "सही पत्ते ऊपर, बाकी फीके",
      timer: "बारी का टाइमर", timerHint: "समय खत्म होने पर आपकी जगह पत्ता चल दिया जाता है",
      easy: "आसान मोड", easyHint: "बड़े पत्ते, चार रंग, सुझाव चालू, टाइमर बंद",
    },
    sound: {
      title: "आवाज़ और वाइब्रेशन",
      master: "आवाज़", masterHint: "ऐप की हर आवाज़",
      effects: "टेबल की आवाज़ें", effectsHint: "हर रूम की अपनी: तबला, पीतल या आर्केड",
      haptics: "वाइब्रेशन", hapticsHint: "पत्ता गिरने पर हल्का झटका",
      volume: "वॉल्यूम",
      strength: "वाइब्रेशन की तेज़ी", strengthHint: "महफ़िल में हल्का, दरबार और आर्केड में तेज़",
      hapticOff: "बंद", hapticGentle: "हल्का", hapticCrisp: "साफ़", hapticFirm: "तेज़",
    },
    parent: {
      title: "पैरेंट कंट्रोल",
      noPinTitle: "PIN नहीं लगा", noPinBody: "PIN के बिना इस फ़ोन पर कोई भी ये स्विच बदल सकता है।",
      text: "लिखकर चैट", textHint: "झटपट चैट वाले वाक्य हमेशा चालू रहते हैं",
      online: "ऑनलाइन खेल", onlineHint: "इंटरनेट पर रूम और मैच",
      wifi: "Wi-Fi टेबल", wifiHint: "एक ही नेटवर्क पर टेबल खोलें या जुड़ें",
      installTitle: "ये सेटिंग्स सिर्फ़ इसी इंस्टॉल की हैं।",
      installBody: "TashZone दोबारा इंस्टॉल करने या डेटा साफ़ करने पर ये पहले जैसी हो जाती हैं।",
      setPin: "PIN लगाएँ", changePin: "PIN बदलें", removePin: "PIN हटाएँ",
      lockedTitle: "पैरेंट कंट्रोल लॉक हैं", enterPin: "पैरेंट PIN डालें",
      lockedFor: (s: number) => `बहुत बार गलत PIN। ${s} सेकंड बाद फिर कोशिश करें।`,
      wrong: (left: number) => `गलत PIN। ${left} ${left === 1 ? "कोशिश" : "कोशिशें"} बाकी।`,
      unlock: "खोलें",
    },
    pin: {
      title: "पैरेंट PIN",
      intro: "चार अंक। यह सिर्फ़ पैरेंट कंट्रोल को सुरक्षित रखता है।",
      current: "मौजूदा PIN डालें", fresh: "नया PIN चुनें", confirm: "दोबारा डालें",
      mismatch: "दोनों PIN मेल नहीं खाए। फिर कोशिश करें।",
      saved: "PIN सेव हो गया",
      checking: "जाँच हो रही है",
    },
    account: {
      title: "खाता और डेटा",
      noAccountTitle: "आपकी प्रोफ़ाइल इसी फ़ोन पर है।",
      noAccountBody: "ऑनलाइन खेले या साइन-इन किए बिना कुछ भी फ़ोन से बाहर नहीं जाता। साइन-इन करें तो नए फ़ोन पर आपका नाम और रिकॉर्ड वापस मिल जाएगा। हम सिर्फ़ खाता ID रखते हैं, ईमेल या नाम कभी नहीं।",
      signInTitle: "साइन-इन (वैकल्पिक)", google: "Google से साइन-इन", playGames: "Play Games से साइन-इन",
      linked: "जुड़ा है", unlink: "हटाएँ", signedIn: "साइन-इन हो गया। आपका रिकॉर्ड सुरक्षित है।",
      restoredMsg: "प्रोफ़ाइल वापस आ गई।", takenTitle: "प्रोफ़ाइल मिली", takenBody: "इस खाते की पहले से TashZone प्रोफ़ाइल है। उस पर जाएँ? इस फ़ोन का रिकॉर्ड बदल जाएगा।",
      switchDo: "उस पर जाएँ", pinToSignIn: "साइन-इन के लिए माता-पिता का PIN डालें", askParent: "माता-पिता से PIN बनवाएँ, फिर साइन-इन करें।",
      errNoAccount: "इस फ़ोन पर कोई Google खाता नहीं।", errUnavailable: "अभी साइन-इन उपलब्ध नहीं।", errInvalid: "साइन-इन की पुष्टि नहीं हुई। फिर कोशिश करें।",
      errOffline: "इंटरनेट नहीं। फिर कोशिश करें।", errOther: "कोई दूसरा खाता पहले से जुड़ा है।", errFailed: "साइन-इन नहीं हुआ। फिर कोशिश करें।",
      signedInAs: (email: string) => `${email} से साइन-इन`, signOut: "साइन-आउट", signOutHint: "यह फ़ोन मेहमान प्रोफ़ाइल पर लौट आएगा",
      signOutAll: "दूसरे फ़ोन से साइन-आउट", signOutAllHint: "यह फ़ोन साइन-इन रहेगा", signOutAllDone: "दूसरे फ़ोन से साइन-आउट हो गया।",
      signOutTitle: "साइन-आउट करें?", signOutBody: "आपका रिकॉर्ड खाते में सुरक्षित रहेगा। यह फ़ोन मेहमान के रूप में फिर से शुरू होगा।", signOutDo: "साइन-आउट",
      passwordHint: "मौजूदा पासवर्ड चाहिए",
      backup: "बैकअप शेयर करें", backupHint: "नाम, अवतार, रिकॉर्ड और सेटिंग्स टेक्स्ट में (PIN नहीं)",
      restore: "बैकअप वापस लाएँ", restoreHint: "पहले सेव किया टेक्स्ट पेस्ट करें",
      restoreTitle: "बैकअप वापस लाएँ", restoreBody: "बैकअप टेक्स्ट पेस्ट करें। इससे आपका नाम, अवतार, रिकॉर्ड और खेल की सेटिंग्स बदल जाएँगी। पैरेंट कंट्रोल वैसे ही रहेंगे।",
      restorePlaceholder: "बैकअप टेक्स्ट यहाँ पेस्ट करें", restoreDo: "वापस लाएँ", restoreBad: "यह TashZone का बैकअप नहीं है।", restored: "बैकअप वापस आ गया",
      wipe: "सब कुछ मिटाएँ", wipeHint: "पहली स्क्रीन से नई शुरुआत",
      wipeTitle: "सब कुछ मिटा दें?", wipeBody: "आपका नाम, अवतार, रिकॉर्ड और सेटिंग्स इस फ़ोन से मिट जाएँगे। यह वापस नहीं होगा।",
      wipePin: "सब कुछ मिटाने के लिए पैरेंट PIN डालें", wipeDo: "मिटाएँ", cancel: "रद्द करें", close: "बंद करें",
      protectedOn: "सुरक्षित मोड चालू है। लिखकर चैट बंद है।", protectedOff: "सुरक्षित मोड बंद है।",
      shareMsgTitle: "TashZone बैकअप",
    },
    themes: {
      title: "टेबल के डिज़ाइन",
      intro: "पूरे इलाके के कपड़े। डिज़ाइन सिर्फ़ टेबल का कपड़ा बदलता है, पत्ते या बाकी कुछ नहीं।",
      soon: "जल्द आ रहा है",
      note: "टेबल पर अभी सादा हरा कपड़ा ही है। ये सिर्फ़ झलक हैं; अभी कोई चुना नहीं जा सकता।",
      designs: [
        "ट्रक आर्ट", "अजरक", "मुल्तानी नीला", "फुलकारी", "चिनियोटी लकड़ी", "बलूची शीशा-कारी", "सिंधी रल्ली", "ऊँट-खाल लैंप", "वारली", "बांधनी",
        "जयपुरी छपाई", "कलमकारी", "नक्शी कांथा", "जामदानी", "रिक्शा आर्ट", "टेराकोटा", "मिथिला", "नेवारी खिड़की", "ढाका कपड़ा",
      ],
    },
    parentExtra: {
      lockedFor: (s: number) => `बहुत बार गलत PIN। ${s >= 60 ? `${Math.ceil(s / 60)} मिनट` : `${s} सेकंड`} बाद फिर कोशिश करें।`,
      checkFailed: "PIN जाँचा नहीं जा सका। फिर कोशिश करें।",
      saveFailed: "PIN सेव नहीं हो सका। फिर कोशिश करें।",
      removeTitle: "पैरेंट PIN हटाएँ?",
      removeFacts: [
        { mark: "1", title: "कोई भी ये स्विच बदल सकेगा", body: "PIN के बिना इस फ़ोन पर कोई भी चैट, ऑनलाइन खेल और Wi-Fi टेबल चालू या बंद कर सकता है।" },
        { mark: "2", title: "नया PIN कभी भी लगा सकते हैं", body: "पैरेंट कंट्रोल की मौजूदा सेटिंग्स बनी रहेंगी।" },
      ],
      removeDo: "PIN हटाएँ",
      keep: "PIN रहने दें",
    },
  },
  ne: {
    settings: {
      title: "सेटिङ",
      looks: "रूपरङ", playing: "खेल", sound: "आवाज र कम्पन", language: "भाषा", parent: "अभिभावक नियन्त्रण",
      howto: "कसरी खेल्ने", howtoHint: "छोटो नियम र अभ्यासको बाजी", rules: "नियम र शब्द", rulesHint: "हरेक खेल, हरेक शब्द",
      account: "खाता र डेटा", accountHint: "यही फोनमा मात्र", reset: "फेरि सुरु गर्नुहोस्", resetHint: "यो फोनबाट तपाईंको प्रोफाइल मेटिन्छ",
      pinSet: "PIN राखिएको छ", pinNone: "अहिलेसम्म PIN छैन",
      on: "अन", off: "अफ", hints: "सुझाव", clock: "टाइमर", haptics: "कम्पन", silent: "मौन", soundOn: "आवाज अन",
      playLine: (hints: boolean, clock: boolean) => `सुझाव ${hints ? "अन" : "अफ"} · टाइमर ${clock ? "अन" : "अफ"}`,
      soundLine: (sound: boolean, haptics: boolean) => `${sound ? "आवाज अन" : "मौन"} · कम्पन ${haptics ? "अन" : "अफ"}`,
      groupLook: "रूप, खेल र आवाज", groupFamily: "परिवार र डेटा", groupHelp: "सहायता",
      fourColor: "चार रङको गड्डी", calm: "कम हलचल", pinBadge: "PIN राखिएको", player: "खेलाडी",
      profileLabel: (name: string) => `${name || "तपाईंको प्रोफाइल"}। नाम र अवतार बदल्नुहोस्`,
      statsLine: (matches: number, wins: number) => `${matches} म्याच · ${wins} जित`,
      about: "TashZone बारे", aboutHint: "इमानदार बाँडाइ, गोपनीयता, आभार",
      langNames: { en: "अङ्ग्रेजी", ur: "उर्दू", hi: "हिन्दी", ne: "नेपाली", bn: "बङ्गाली" },
      aboutTitle: "परिचय",
      version: (v: string) => `TashZone ${v}`,
      nameAvatar: "नाम र अवतार",
    },
    about: {
      share: "TashZone सेयर गर्नुहोस्",
      shareMsg: (ready: number, more: number) => `TashZone मा दक्षिण एसियाका तास खेल खेल्नुहोस्: ${ready} तयार, थप ${more} आउँदै छन्। इमानदार बाँडाइ, इन्टरनेटबिना पनि।`,
      version: (v: string, room: string) => `संस्करण ${v} · ${room} रुम`,
      sep: ", ",
      fairT: "इमानदार बाँडाइ", fairB: "हरेक पटक पत्ती सुरक्षित र्‍यान्डम तरिकाले फिटिन्छ। न कठिनाइ मिलाइन्छ, न पत्ती मिलाइन्छ, न एपलाई कुनै फाइदा।",
      privateT: "पूर्ण रूपमा गोप्य", privateB: "न खाता, न ट्र्याकर, न विज्ञापन। तपाईंको प्रोफाइल, रेकर्ड र सेटिङ यही फोनमा रहन्छन्।",
      gamesT: "क्षेत्रीय खेल",
      gamesB: (n: number, names: string, more: number) => `अहिले खेल्न मिल्ने ${n} खेल: ${names}। थप ${more} आउँदै छन्।`,
      creditsT: "आभार", creditsB: "Jost, Cormorant Garamond, Bodoni Moda र Noto Nastaliq Urdu फन्ट, SIL Open Font License 1.1 अन्तर्गत।",
    },
    looks: {
      title: "रूपरङ",
      room: "रुम",
      festival: "चाडपर्व रुम",
      until: (date: string) => `${date} सम्म`,
      cards: "पत्ती",
      four: "चार रङको गड्डी", fourHint: "इँट नीलो, चिडी हरियो",
      large: "ठूला पत्ती", largeHint: "ठूला चित्र, एक लहरमा कम पत्ती",
      motion: "कम हलचल", motionHint: "चलाउनुको सट्टा बिस्तारै देखिन्छ। फोनको सेटिङ पनि मान्छ",
      orientation: "स्क्रिन", orientAuto: "अटो", orientPortrait: "ठाडो", orientLandscape: "तेर्सो",
      designs: "टेबलका डिजाइन", designsHint: "कपडाको झलक, छिट्टै आउँदै",
    },
    play: {
      title: "खेल",
      hints: "खेल्न मिल्ने पत्ती देखाउनुहोस्", hintsHint: "मिल्ने पत्ती माथि, अरू धमिलो",
      timer: "पालोको टाइमर", timerHint: "समय सकिए तपाईंको सट्टा पत्ती खेलिन्छ",
      easy: "सजिलो मोड", easyHint: "ठूला पत्ती, चार रङ, सुझाव अन, टाइमर छैन",
    },
    sound: {
      title: "आवाज र कम्पन",
      master: "आवाज", masterHint: "एपका सबै आवाज",
      effects: "टेबलका आवाज", effectsHint: "हरेक रुमको आफ्नै: तबला, पित्तल वा आर्केड",
      haptics: "कम्पन", hapticsHint: "पत्ती खस्दा हल्का धक्का",
      volume: "भोल्युम",
      strength: "कम्पनको बल", strengthHint: "महफिलमा नरम, दरबार र आर्केडमा बलियो",
      hapticOff: "अफ", hapticGentle: "हल्का", hapticCrisp: "स्पष्ट", hapticFirm: "बलियो",
    },
    parent: {
      title: "अभिभावक नियन्त्रण",
      noPinTitle: "PIN राखिएको छैन", noPinBody: "PIN नभए यो फोन चलाउने जोसुकैले यी स्विच बदल्न सक्छ।",
      text: "लेखेर च्याट", textHint: "छिटो च्याटका वाक्य सधैँ खुला रहन्छन्",
      online: "अनलाइन खेल", onlineHint: "इन्टरनेटमा रुम र म्याच",
      wifi: "Wi-Fi टेबल", wifiHint: "एउटै नेटवर्कमा टेबल खोल्नुहोस् वा जोडिनुहोस्",
      installTitle: "यी सेटिङ यही इन्स्टलका लागि मात्र हुन्।",
      installBody: "TashZone फेरि इन्स्टल गर्दा वा डेटा मेटाउँदा यी पहिलेकै अवस्थामा फर्कन्छन्।",
      setPin: "PIN राख्नुहोस्", changePin: "PIN बदल्नुहोस्", removePin: "PIN हटाउनुहोस्",
      lockedTitle: "अभिभावक नियन्त्रण लक छ", enterPin: "अभिभावकको PIN हाल्नुहोस्",
      lockedFor: (s: number) => `धेरै पटक गलत भयो। ${s} सेकेन्डपछि फेरि प्रयास गर्नुहोस्।`,
      wrong: (left: number) => `गलत PIN। अझै ${left} पटक बाँकी।`,
      unlock: "खोल्नुहोस्",
    },
    pin: {
      title: "अभिभावकको PIN",
      intro: "चार अङ्क। यसले अभिभावकका स्विच मात्र सुरक्षित राख्छ।",
      current: "हालको PIN हाल्नुहोस्", fresh: "नयाँ PIN छान्नुहोस्", confirm: "फेरि हाल्नुहोस्",
      mismatch: "दुवै PIN मिलेनन्। फेरि प्रयास गर्नुहोस्।",
      saved: "PIN सेभ भयो",
      checking: "जाँच हुँदै छ",
    },
    account: {
      title: "खाता र डेटा",
      noAccountTitle: "तपाईंको प्रोफाइल यही फोनमा छ।",
      noAccountBody: "अनलाइन नखेली वा साइन-इन नगरी केही पनि फोनबाहिर जाँदैन। साइन-इन गर्नुभयो भने नयाँ फोनमा तपाईंको नाम र रेकर्ड फिर्ता आउँछ। हामी खाता ID मात्र राख्छौँ, इमेल वा नाम कहिल्यै होइन।",
      signInTitle: "साइन-इन (ऐच्छिक)", google: "Google बाट साइन-इन", playGames: "Play Games बाट साइन-इन",
      linked: "जोडिएको", unlink: "हटाउनुहोस्", signedIn: "साइन-इन भयो। तपाईंको रेकर्ड सुरक्षित छ।",
      restoredMsg: "प्रोफाइल फिर्ता आयो।", takenTitle: "प्रोफाइल भेटियो", takenBody: "यो खातामा पहिल्यै TashZone प्रोफाइल छ। त्यसमा जाने? यो फोनको रेकर्ड बदलिन्छ।",
      switchDo: "त्यसमा जानुहोस्", pinToSignIn: "साइन-इन गर्न अभिभावकको PIN हाल्नुहोस्", askParent: "अभिभावकलाई PIN बनाउन भन्नुहोस्, अनि साइन-इन गर्नुहोस्।",
      errNoAccount: "यो फोनमा Google खाता छैन।", errUnavailable: "अहिले साइन-इन उपलब्ध छैन।", errInvalid: "साइन-इन पुष्टि भएन। फेरि प्रयास गर्नुहोस्।",
      errOffline: "इन्टरनेट छैन। फेरि प्रयास गर्नुहोस्।", errOther: "अर्को खाता पहिल्यै जोडिएको छ।", errFailed: "साइन-इन भएन। फेरि प्रयास गर्नुहोस्।",
      signedInAs: (email: string) => `${email} बाट साइन-इन`, signOut: "साइन-आउट", signOutHint: "यो फोन पाहुना प्रोफाइलमा फर्किन्छ",
      signOutAll: "अरू फोनबाट साइन-आउट", signOutAllHint: "यो फोन साइन-इन रहन्छ", signOutAllDone: "अरू फोनबाट साइन-आउट भयो।",
      signOutTitle: "साइन-आउट गर्ने?", signOutBody: "तपाईंको रेकर्ड खातामा सुरक्षित रहन्छ। यो फोन पाहुनाको रूपमा फेरि सुरु हुन्छ।", signOutDo: "साइन-आउट",
      passwordHint: "हालको पासवर्ड चाहिन्छ",
      backup: "ब्याकअप सेयर गर्नुहोस्", backupHint: "नाम, अवतार, रेकर्ड र सेटिङ पाठका रूपमा (PIN बाहेक)",
      restore: "ब्याकअप फर्काउनुहोस्", restoreHint: "पहिले सेभ गरेको पाठ टाँस्नुहोस्",
      restoreTitle: "ब्याकअप फर्काउनुहोस्", restoreBody: "ब्याकअपको पाठ टाँस्नुहोस्। यसले तपाईंको नाम, अवतार, रेकर्ड र खेलका सेटिङ बदल्छ। अभिभावक नियन्त्रण जस्ताको तस्तै रहन्छ।",
      restorePlaceholder: "ब्याकअपको पाठ यहाँ टाँस्नुहोस्", restoreDo: "फर्काउनुहोस्", restoreBad: "यो TashZone को ब्याकअप होइन।", restored: "ब्याकअप फर्कियो",
      wipe: "सबै मेटाउनुहोस्", wipeHint: "पहिलो स्क्रिनबाट फेरि सुरु",
      wipeTitle: "सबै मेटाउने?", wipeBody: "तपाईंको नाम, अवतार, रेकर्ड र सेटिङ यो फोनबाट मेटिनेछन्। यो फिर्ता हुँदैन।",
      wipePin: "सबै मेटाउन अभिभावकको PIN हाल्नुहोस्", wipeDo: "मेटाउनुहोस्", cancel: "रद्द गर्नुहोस्", close: "बन्द गर्नुहोस्",
      protectedOn: "सुरक्षित मोड अन छ। लेखेर च्याट बन्द छ।", protectedOff: "सुरक्षित मोड अफ छ।",
      shareMsgTitle: "TashZone ब्याकअप",
    },
    themes: {
      title: "टेबलका डिजाइन",
      intro: "पूरै क्षेत्रका कपडा। डिजाइनले टेबलको कपडा मात्र बदल्छ, पत्ती वा अरू केही होइन।",
      soon: "छिट्टै आउँदै",
      note: "टेबलमा अझै सादा हरियो कपडा नै छ। यी झलक मात्र हुन्; अहिले छान्न मिल्दैन।",
      designs: [
        "ट्रक आर्ट", "अजरक", "मुल्तानी नीलो", "फुलकारी", "चिनियोटी काठ", "बलुची ऐना-कला", "सिन्धी रल्ली", "ऊँटको छालाको बत्ती", "वार्ली", "बाँधनी",
        "जयपुरी छापा", "कलमकारी", "नक्शी कान्था", "जामदानी", "रिक्सा आर्ट", "टेराकोटा", "मिथिला", "नेवारी झ्याल", "ढाका कपडा",
      ],
    },
    parentExtra: {
      lockedFor: (s: number) => `धेरै पटक गलत भयो। ${s >= 60 ? `${Math.ceil(s / 60)} मिनेट` : `${s} सेकेन्ड`}पछि फेरि प्रयास गर्नुहोस्।`,
      checkFailed: "PIN जाँच्न सकिएन। फेरि प्रयास गर्नुहोस्।",
      saveFailed: "PIN सेभ गर्न सकिएन। फेरि प्रयास गर्नुहोस्।",
      removeTitle: "अभिभावकको PIN हटाउने?",
      removeFacts: [
        { mark: "1", title: "जोसुकैले यी स्विच बदल्न सक्छ", body: "PIN नभए यो फोन चलाउने जोसुकैले च्याट, अनलाइन खेल र Wi-Fi टेबल अन वा अफ गर्न सक्छ।" },
        { mark: "2", title: "जुनसुकै बेला नयाँ PIN राख्न सकिन्छ", body: "अभिभावक नियन्त्रणको हालको सेटिङ रहिरहन्छ।" },
      ],
      removeDo: "PIN हटाउनुहोस्",
      keep: "PIN रहन दिनुहोस्",
    },
  },
  bn: {
    settings: {
      title: "সেটিংস",
      looks: "চেহারা", playing: "খেলা", sound: "শব্দ ও ভাইব্রেশন", language: "ভাষা", parent: "প্যারেন্ট কন্ট্রোল",
      howto: "কীভাবে খেলবেন", howtoHint: "সংক্ষেপে নিয়ম, সাথে অনুশীলনের দান", rules: "নিয়ম ও পরিভাষা", rulesHint: "প্রতিটি খেলা, প্রতিটি শব্দ",
      account: "অ্যাকাউন্ট ও ডেটা", accountHint: "শুধু এই ফোনে", reset: "আবার শুরু করুন", resetHint: "এই ফোন থেকে আপনার প্রোফাইল মুছে যাবে",
      pinSet: "PIN দেওয়া আছে", pinNone: "এখনো PIN নেই",
      on: "চালু", off: "বন্ধ", hints: "পরামর্শ", clock: "টাইমার", haptics: "ভাইব্রেশন", silent: "নীরব", soundOn: "শব্দ চালু",
      playLine: (hints: boolean, clock: boolean) => `পরামর্শ ${hints ? "চালু" : "বন্ধ"} · টাইমার ${clock ? "চালু" : "বন্ধ"}`,
      soundLine: (sound: boolean, haptics: boolean) => `${sound ? "শব্দ চালু" : "নীরব"} · ভাইব্রেশন ${haptics ? "চালু" : "বন্ধ"}`,
      groupLook: "চেহারা, খেলা ও শব্দ", groupFamily: "পরিবার ও ডেটা", groupHelp: "সাহায্য",
      fourColor: "চার রঙের তাস", calm: "কম নড়াচড়া", pinBadge: "PIN দেওয়া", player: "খেলোয়াড়",
      profileLabel: (name: string) => `${name || "আপনার প্রোফাইল"}। নাম ও অবতার বদলান`,
      statsLine: (matches: number, wins: number) => `${matches}টি ম্যাচ · ${wins}টি জয়`,
      about: "TashZone সম্পর্কে", aboutHint: "ন্যায্য বাঁটা, গোপনীয়তা, কৃতজ্ঞতা",
      langNames: { en: "ইংরেজি", ur: "উর্দু", hi: "হিন্দি", ne: "নেপালি", bn: "বাংলা" },
      aboutTitle: "পরিচিতি",
      version: (v: string) => `TashZone ${v}`,
      nameAvatar: "নাম ও অবতার",
    },
    about: {
      share: "TashZone শেয়ার করুন",
      shareMsg: (ready: number, more: number) => `TashZone-এ দক্ষিণ এশিয়ার তাসের খেলা খেলুন: ${ready}টি তৈরি, আরও ${more}টি আসছে। ন্যায্য বাঁটা, ইন্টারনেট ছাড়াও।`,
      version: (v: string, room: string) => `সংস্করণ ${v} · ${room} রুম`,
      sep: ", ",
      fairT: "ন্যায্য বাঁটা", fairB: "প্রতিবার তাস নিরাপদ র‍্যান্ডম পদ্ধতিতে ফেটানো হয়। কঠিনতা বদলানো, তাস সাজানো বা অ্যাপের বাড়তি সুবিধা নেই।",
      privateT: "পুরোপুরি ব্যক্তিগত", privateB: "অ্যাকাউন্ট নেই, ট্র্যাকার নেই, বিজ্ঞাপন নেই। আপনার প্রোফাইল, রেকর্ড ও সেটিংস এই ফোনেই থাকে।",
      gamesT: "আঞ্চলিক খেলা",
      gamesB: (n: number, names: string, more: number) => `এখনই খেলা যায় ${n}টি খেলা: ${names}। আরও ${more}টি আসছে।`,
      creditsT: "কৃতজ্ঞতা", creditsB: "Jost, Cormorant Garamond, Bodoni Moda ও Noto Nastaliq Urdu ফন্ট, SIL Open Font License 1.1-এর অধীনে।",
    },
    looks: {
      title: "চেহারা",
      room: "রুম",
      festival: "উৎসবের রুম",
      until: (date: string) => `${date} পর্যন্ত`,
      cards: "তাস",
      four: "চার রঙের তাস", fourHint: "রুইতন নীল, চিড়িতন সবুজ",
      large: "বড় তাস", largeHint: "বড় ছবি, এক সারিতে কম তাস",
      motion: "কম নড়াচড়া", motionHint: "নড়াচড়ার বদলে হালকা ফেড। ফোনের সেটিংও মানে",
      orientation: "স্ক্রিন", orientAuto: "অটো", orientPortrait: "খাড়া", orientLandscape: "আড়াআড়ি",
      designs: "টেবিলের নকশা", designsHint: "কাপড়ের ঝলক, শিগগিরই আসছে",
    },
    play: {
      title: "খেলা",
      hints: "খেলার মতো তাস দেখান", hintsHint: "বৈধ তাস উঠে আসে, বাকিগুলো ফিকে",
      timer: "পালার টাইমার", timerHint: "সময় ফুরোলে আপনার হয়ে তাস খেলা হয়",
      easy: "সহজ মোড", easyHint: "বড় তাস, চার রং, পরামর্শ চালু, টাইমার নেই",
    },
    sound: {
      title: "শব্দ ও ভাইব্রেশন",
      master: "শব্দ", masterHint: "অ্যাপের সব শব্দ",
      effects: "টেবিলের আওয়াজ", effectsHint: "প্রতিটি রুমের নিজস্ব: তবলা, পিতল বা আর্কেড",
      haptics: "ভাইব্রেশন", hapticsHint: "তাস পড়লে হালকা ঝাঁকুনি",
      volume: "ভলিউম",
      strength: "ভাইব্রেশনের জোর", strengthHint: "মেহফিলে মৃদু, দরবার ও আর্কেডে জোরালো",
      hapticOff: "বন্ধ", hapticGentle: "মৃদু", hapticCrisp: "স্পষ্ট", hapticFirm: "জোরালো",
    },
    parent: {
      title: "প্যারেন্ট কন্ট্রোল",
      noPinTitle: "PIN দেওয়া নেই", noPinBody: "PIN না থাকলে এই ফোনে যে কেউ এই সুইচগুলো বদলাতে পারবে।",
      text: "লিখে চ্যাট", textHint: "দ্রুত চ্যাটের বাক্য সবসময় চালু থাকে",
      online: "অনলাইন খেলা", onlineHint: "ইন্টারনেটে রুম ও ম্যাচ",
      wifi: "Wi-Fi টেবিল", wifiHint: "একই নেটওয়ার্কে টেবিল খুলুন বা যোগ দিন",
      installTitle: "এই সেটিংস শুধু এই ইনস্টলের জন্য।",
      installBody: "TashZone আবার ইনস্টল করলে বা ডেটা মুছলে এগুলো আগের মতো হয়ে যায়।",
      setPin: "PIN দিন", changePin: "PIN বদলান", removePin: "PIN সরান",
      lockedTitle: "প্যারেন্ট কন্ট্রোল লক করা", enterPin: "অভিভাবকের PIN দিন",
      lockedFor: (s: number) => `অনেকবার ভুল হয়েছে। ${s} সেকেন্ড পরে আবার চেষ্টা করুন।`,
      wrong: (left: number) => `ভুল PIN। আর ${left} বার চেষ্টা করা যাবে।`,
      unlock: "খুলুন",
    },
    pin: {
      title: "অভিভাবকের PIN",
      intro: "চার অঙ্ক। এটি শুধু প্যারেন্ট কন্ট্রোল রক্ষা করে।",
      current: "বর্তমান PIN দিন", fresh: "নতুন PIN বেছে নিন", confirm: "আবার দিন",
      mismatch: "দুটি PIN মেলেনি। আবার চেষ্টা করুন।",
      saved: "PIN সেভ হয়েছে",
      checking: "যাচাই হচ্ছে",
    },
    account: {
      title: "অ্যাকাউন্ট ও ডেটা",
      noAccountTitle: "আপনার প্রোফাইল এই ফোনেই আছে।",
      noAccountBody: "অনলাইনে না খেললে বা সাইন-ইন না করলে কিছুই ফোনের বাইরে যায় না। সাইন-ইন করলে নতুন ফোনে আপনার নাম ও রেকর্ড ফিরে পাবেন। আমরা শুধু অ্যাকাউন্ট ID রাখি, ইমেল বা নাম কখনো না।",
      signInTitle: "সাইন-ইন (ঐচ্ছিক)", google: "Google দিয়ে সাইন-ইন", playGames: "Play Games দিয়ে সাইন-ইন",
      linked: "যুক্ত", unlink: "সরান", signedIn: "সাইন-ইন হয়েছে। আপনার রেকর্ড সুরক্ষিত।",
      restoredMsg: "প্রোফাইল ফিরে এসেছে।", takenTitle: "প্রোফাইল পাওয়া গেছে", takenBody: "এই অ্যাকাউন্টে আগে থেকেই TashZone প্রোফাইল আছে। সেটিতে যাবেন? এই ফোনের রেকর্ড বদলে যাবে।",
      switchDo: "সেটিতে যান", pinToSignIn: "সাইন-ইন করতে অভিভাবকের PIN দিন", askParent: "অভিভাবককে PIN বানাতে বলুন, তারপর সাইন-ইন করুন।",
      errNoAccount: "এই ফোনে কোনো Google অ্যাকাউন্ট নেই।", errUnavailable: "এখন সাইন-ইন পাওয়া যাচ্ছে না।", errInvalid: "সাইন-ইন যাচাই করা যায়নি। আবার চেষ্টা করুন।",
      errOffline: "ইন্টারনেট নেই। আবার চেষ্টা করুন।", errOther: "অন্য একটি অ্যাকাউন্ট আগে থেকেই যুক্ত।", errFailed: "সাইন-ইন হয়নি। আবার চেষ্টা করুন।",
      signedInAs: (email: string) => `${email} দিয়ে সাইন-ইন`, signOut: "সাইন-আউট", signOutHint: "এই ফোন অতিথি প্রোফাইলে ফিরে যাবে",
      signOutAll: "অন্য ফোন থেকে সাইন-আউট", signOutAllHint: "এই ফোন সাইন-ইন থাকবে", signOutAllDone: "অন্য ফোন থেকে সাইন-আউট হয়েছে।",
      signOutTitle: "সাইন-আউট করবেন?", signOutBody: "আপনার রেকর্ড অ্যাকাউন্টে থাকবে। এই ফোন অতিথি হিসেবে আবার শুরু হবে।", signOutDo: "সাইন-আউট",
      passwordHint: "বর্তমান পাসওয়ার্ড লাগবে",
      backup: "ব্যাকআপ শেয়ার করুন", backupHint: "নাম, অবতার, রেকর্ড ও সেটিংস লেখা হিসেবে (PIN ছাড়া)",
      restore: "ব্যাকআপ ফেরান", restoreHint: "আগে সেভ করা লেখা পেস্ট করুন",
      restoreTitle: "ব্যাকআপ ফেরান", restoreBody: "ব্যাকআপের লেখা পেস্ট করুন। এতে আপনার নাম, অবতার, রেকর্ড ও খেলার সেটিংস বদলে যাবে। প্যারেন্ট কন্ট্রোল যেমন আছে তেমনই থাকবে।",
      restorePlaceholder: "ব্যাকআপের লেখা এখানে পেস্ট করুন", restoreDo: "ফেরান", restoreBad: "এটি TashZone-এর ব্যাকআপ নয়।", restored: "ব্যাকআপ ফেরানো হয়েছে",
      wipe: "সব মুছুন", wipeHint: "প্রথম স্ক্রিন থেকে নতুন শুরু",
      wipeTitle: "সব মুছে ফেলবেন?", wipeBody: "আপনার নাম, অবতার, রেকর্ড ও সেটিংস এই ফোন থেকে মুছে যাবে। এটি আর ফেরানো যাবে না।",
      wipePin: "সব মুছতে অভিভাবকের PIN দিন", wipeDo: "মুছুন", cancel: "বাতিল", close: "বন্ধ করুন",
      protectedOn: "সুরক্ষিত মোড চালু। লিখে চ্যাট বন্ধ।", protectedOff: "সুরক্ষিত মোড বন্ধ।",
      shareMsgTitle: "TashZone ব্যাকআপ",
    },
    themes: {
      title: "টেবিলের নকশা",
      intro: "পুরো অঞ্চলের কাপড়। নকশা শুধু টেবিলের কাপড় বদলায়, তাস বা অন্য কিছু নয়।",
      soon: "শিগগিরই আসছে",
      note: "টেবিলে এখনো সাধারণ সবুজ কাপড়ই আছে। এগুলো শুধু ঝলক; এখনই বেছে নেওয়া যাবে না।",
      designs: [
        "ট্রাক আর্ট", "আজরাক", "মুলতানি নীল", "ফুলকারি", "চিনিওটি কাঠ", "বেলুচি আয়নার কাজ", "সিন্ধি রিল্লি", "উটের চামড়ার বাতি", "ওয়ারলি", "বাঁধনি",
        "জয়পুরি ছাপা", "কলমকারি", "নকশিকাঁথা", "জামদানি", "রিকশা আর্ট", "পোড়ামাটি", "মিথিলা", "নেওয়ারি জানালা", "ঢাকাই কাপড়",
      ],
    },
    parentExtra: {
      lockedFor: (s: number) => `অনেকবার ভুল হয়েছে। ${s >= 60 ? `${Math.ceil(s / 60)} মিনিট` : `${s} সেকেন্ড`} পরে আবার চেষ্টা করুন।`,
      checkFailed: "PIN যাচাই করা যায়নি। আবার চেষ্টা করুন।",
      saveFailed: "PIN সেভ করা যায়নি। আবার চেষ্টা করুন।",
      removeTitle: "অভিভাবকের PIN সরাবেন?",
      removeFacts: [
        { mark: "1", title: "যে কেউ এই সুইচগুলো বদলাতে পারবে", body: "PIN না থাকলে এই ফোনে যে কেউ চ্যাট, অনলাইন খেলা ও Wi-Fi টেবিল চালু বা বন্ধ করতে পারবে।" },
        { mark: "2", title: "যেকোনো সময় নতুন PIN দিতে পারবেন", body: "প্যারেন্ট কন্ট্রোলের বর্তমান সেটিংস থেকে যাবে।" },
      ],
      removeDo: "PIN সরান",
      keep: "PIN রাখুন",
    },
  },
});
