import { localized } from "../../../i18n";

const EN_ORD = ["1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th"];
const UR_ORD = ["پہلا", "دوسرا", "تیسرا", "چوتھا", "پانچواں", "چھٹا", "ساتواں", "آٹھواں"];
const HI_ORD = ["पहला", "दूसरा", "तीसरा", "चौथा", "पाँचवाँ", "छठा", "सातवाँ", "आठवाँ"];
const NE_ORD = ["पहिलो", "दोस्रो", "तेस्रो", "चौथो", "पाँचौँ", "छैटौँ", "सातौँ", "आठौँ"];
const BN_ORD = ["প্রথম", "দ্বিতীয়", "তৃতীয়", "চতুর্থ", "পঞ্চম", "ষষ্ঠ", "সপ্তম", "অষ্টম"];

export const CARD = localized("play.cards", {
  en: {
    ranks: { A: "Ace", K: "King", Q: "Queen", J: "Jack", T: "10" },
    suits: { S: "Spades", H: "Hearts", D: "Diamonds", C: "Clubs" },
    card: (rank: string, suit: string, _queen: boolean) => `${rank} of ${suit}`,
    playable: (label: string, ok: boolean) => `${label}, ${ok ? "playable" : "not playable"}`,
    ord: (n: number) => EN_ORD[n - 1] ?? `${n}th`,
  },
  ur: {
    ranks: { A: "اِکا", K: "بادشاہ", Q: "بیگم", J: "غلام", T: "10" },
    suits: { S: "حکم", H: "پان", D: "اینٹ", C: "چڑیا" },
    card: (rank: string, suit: string, queen: boolean) => `${suit} ${queen ? "کی" : "کا"} ${rank}`,
    playable: (label: string, ok: boolean) => `${label}، ${ok ? "چل سکتے ہیں" : "نہیں چل سکتے"}`,
    ord: (n: number) => UR_ORD[n - 1] ?? `${n}واں`,
  },
  hi: {
    ranks: { A: "इक्का", K: "बादशाह", Q: "बेगम", J: "गुलाम", T: "10" },
    suits: { S: "हुकुम", H: "पान", D: "ईंट", C: "चिड़ी" },
    card: (rank: string, suit: string, queen: boolean) => `${suit} ${queen ? "की" : "का"} ${rank}`,
    playable: (label: string, ok: boolean) => `${label}, ${ok ? "चल सकते हैं" : "नहीं चल सकते"}`,
    ord: (n: number) => HI_ORD[n - 1] ?? `${n}वाँ`,
  },
  ne: {
    ranks: { A: "एक्का", K: "बादशाह", Q: "बेगम", J: "गुलाम", T: "10" },
    suits: { S: "हुकुम", H: "पान", D: "ईंट", C: "चिड़ी" },
    card: (rank: string, suit: string, queen: boolean) => `${suit}${queen ? "की" : "को"} ${rank}`,
    playable: (label: string, ok: boolean) => `${label}, ${ok ? "खेल्न मिल्छ" : "खेल्न मिल्दैन"}`,
    ord: (n: number) => NE_ORD[n - 1] ?? `${n}औँ`,
  },
  bn: {
    ranks: { A: "টেক্কা", K: "সাহেব", Q: "বিবি", J: "গোলাম", T: "10" },
    suits: { S: "ইস্কাপন", H: "হরতন", D: "রুইতন", C: "চিড়িতন" },
    card: (rank: string, suit: string, _queen: boolean) => `${suit}ের ${rank}`,
    playable: (label: string, ok: boolean) => `${label}, ${ok ? "খেলা যাবে" : "খেলা যাবে না"}`,
    ord: (n: number) => BN_ORD[n - 1] ?? `${n}তম`,
  },
});

export const T = localized("play.table", {
  en: {
    sep: ", ",
    seat: (n: number) => `Seat ${n}`,
    cards: (n: number) => (n === 1 ? "1 card" : `${n} cards`),
    model: {
      notChosen: "not chosen yet",
      spokenCall: (call: number, won: number) => `called ${call}, won ${won}`,
      teamBadge: (team: string, tricks: number) => `Team ${team} · ${tricks}`,
      teamSpoken: (team: string, tricks: number) => `team ${team}, ${tricks} ${tricks === 1 ? "trick" : "tricks"}`,
      awayBadge: (place: string) => `Away ${place}`,
      awaySpoken: (place: string) => `got away ${place}`,
      annulled: (reason: string) => `Hand annulled (${reason}). Same dealer deals again.`,
      reasons: { redeal_request: "redeal request", low_call_sum: "low call sum", guard: "guard" },
      handOf: (n: number, of: number) => `Hand ${n} of ${of}`,
      shuffling: "Shuffling",
      trumpAlways: (suit: string, glyph: string) => `${suit} are trump ${glyph}`,
      sir: (double: boolean, target: number) => `${double ? "Double" : "Single"} Sir · to ${target}`,
      pointsAB: (a: number, b: number) => `Points A ${a} · B ${b}`,
      trumpIs: (suit: string) => `Trump: ${suit}`,
      pile: (n: number) => `Pile ${n}`,
      waitingTrump: "Waiting for trump to be chosen",
      pickedUpTrick: (name: string) => `${name} picked up the trick`,
      trickAside: "Trick put aside",
      pts: (n: number) => `${n} pts`,
      timesBhabhi: (n: number) => `${n}× Bhabhi`,
    },
    say: {
      matchOver: "Match over",
      dealingFull: "Shuffling and dealing",
      handOver: "Hand over",
      weakHand: "Weak hand? Ask for a redeal",
      redealOpen: "Redeal window open",
      chooseCall: "Pick how many tricks you'll win",
      isCalling: (name: string) => `${name} is calling`,
      youNameTrump: "You name trump",
      mayTake: "You can take the next player's cards",
      isPlaying: (name: string) => `${name} is playing`,
      leadAceSpades: "Lead the Ace of Spades",
      lead: "Your lead: play any card",
      leadShort: "play any card",
      follow: (glyph: string, suit: string) => `Follow ${glyph} ${suit}`,
      noSuitBreaks: (glyph: string) => `No ${glyph}: any card breaks the suit`,
      noSuitTrump: (glyph: string) => `No ${glyph}: play a trump or any card`,
      yourTurn: (what: string) => `Your turn: ${what.replace(/^\w/, (x) => x.toLowerCase())}`,
      dealing: "Dealing",
      redealWindow: "Redeal window",
      waiting: "Waiting",
      breakWarn: (glyph: string, name: string, n: number) => `You have no ${glyph}: whatever you play, ${name} picks up ${n} cards`,
      voidTag: (glyph: string) => `no ${glyph}`,
      nobodyTook: "Nobody took it.",
      took: (name: string) => `${name} took it.`,
      pickedUpBroken: (name: string) => `${name} picked it up: suit broken.`,
      putAside: (name: string) => `Put aside. ${name} leads again.`,
    },
    phase: {
      over: "match over",
      dealing: "dealing",
      handOver: "hand over",
      window: "redeal window",
      calling: "calling",
      trump: "choosing trump",
      following: (glyph: string) => `following ${glyph}`,
      open: "open lead",
    },
    hint: {
      none: "Nothing to play right now",
      noneWhy: "Hints appear when it is your turn.",
      steadyLead: "A steady lead from this hand.",
      follows: "Follows suit without wasting a high card.",
      trumpWins: "You can't follow, so a trump can win it.",
      shed: "You can't follow; this sheds your least useful card.",
      least: "You can't follow; this gives up the least.",
      call: (n: number) => `Call ${n}`,
      callWhy: "Based on the strength of your cards.",
      trump: (glyph: string, suit: string) => `${glyph} ${suit} as trump`,
      trumpWhy: "Your longest, strongest suit.",
      take: "Take the next player's cards",
      takeWhy: "They get away; you keep the tempo.",
      redeal: "Ask for a redeal",
      redealWhy: "Your hand is weak enough to redeal.",
    },
    rules: {
      trump: "Trump",
      trumpText: (suit: string, glyph: string) => `${suit} ${glyph} are always trump.`,
      calls: "Calls",
      callsText: (min: number, max: number) => `Call ${min} to ${max} tricks.`,
      mustBeat: "Beat the trick when you can",
      mustBeatOn: "If you can win the trick, you must.",
      mustBeatOff: "Follow suit with any card.",
      trumpIfWinning: "Trump when you cannot follow",
      trumpIfWinningOn: "Can't follow? You must trump if it wins.",
      trumpIfWinningOff: "Can't follow? Play anything.",
      overtrick: "Extra tricks score",
      overtrickOn: "Each trick above your call adds 0.1.",
      overtrickOff: "Tricks above your call add nothing.",
      redeal: "Redeal on request",
      redealOn: "A weak hand may ask for a redeal.",
      redealOff: "No redeal requests.",
      noSpade: "Hand without a spade",
      noSpadeOn: "The same dealer redeals automatically.",
      noSpadeOff: "Played as dealt.",
      firstLead: "First lead",
      firstLeadNoTrump: "The first lead of a hand may not be a spade.",
      firstLeadAny: "Any card may open the hand.",
      direction: "Direction",
      clockwise: "Play runs clockwise.",
      counter: "Play runs counter-clockwise.",
      length: "Length",
      hands: (n: number) => (n === 1 ? "1 hand." : `${n} hands.`),
      rounds: (n: number) => (n === 1 ? "1 round." : `${n} rounds.`),
      variant: "Variant",
      double: "Double Sir: win two tricks in a row to collect the pile.",
      single: "Single Sir: first team to seven tricks wins the hand.",
      aces: "Aces block a collect",
      acesOn: "Two aces in a row do not collect the pile.",
      acesOff: "Aces count like any other card.",
      target: "Points to win",
      targetText: (n: number) => `First to ${n}.`,
      handCourt: "Hand and court",
      handCourtText: (hand: number, court: number) => `A hand is worth ${hand}, a court ${court}.`,
      nextDealer: "Next dealer",
      pagat: "The losing side deals next.",
      rotate: "The deal moves one seat each hand.",
      thulla: "Thulla ends the trick",
      thullaOn: "An off-suit card ends the trick at once.",
      thullaOff: "Everyone plays, then the pickup.",
      firstAside: "First trick is put aside",
      firstAsideOn: "The ace-of-spades trick is always put aside.",
      firstAsideOff: "The first trick can be picked up.",
      lastCard: "Last card",
      empty: {
        drawFromWaste: "Win with your last card and you draw from the pile.",
        drawFromNext: "Win with your last card and you draw from the next player.",
        escapeIfThreePlus: "Win with your last card and you get away if three or more remain.",
        passToNext: "Win with your last card and the lead passes on.",
      },
      takeHand: "Take the hand",
      takeHandOn: "Before a trick you may take the next player's cards.",
      takeHandOff: "Hands cannot be taken.",
      twoLeft: "Two players left",
      twoLeftOn: "A card drawn from the pile is led and cut.",
      twoLeftOff: "Played out like any other trick.",
      decks: "Decks",
      twoDecks: "Two decks; identical cards: the first played wins.",
      oneDeck: "One deck.",
      upTo: (rounds: number, limit: number) => `Up to ${rounds} hands, or until someone is Bhabhi ${limit} times.`,
      deal: "Deal",
      even: "Even deal.",
      extra: (n: number) => `You start with ${n} extra cards.`,
    },
    screen: {
      menu: "Table menu",
      tracker: "What has gone",
      undo: "Undo your last card",
      last: "The last trick",
      hint: "Hint",
      inTrick: (list: string) => `In the trick: ${list}`,
      trickEmpty: "No cards in the trick",
      waitingDeal: "Waiting to deal",
      tableInfo: "Table info",
      leaveTitle: "Leave this match?",
      leave: "Leave the match",
      stay: "Stay at the table",
      inHand: (n: number) => `${n} in hand`,
      seats: (n: number) => `${n} seats`,
      endsTitle: "This game ends here",
      endsBody: "Bot games aren't kept open: leaving closes the table.",
      droppedTitle: "The hand in progress is dropped",
      droppedBody: "It won't be recorded, and the running score is lost.",
      idleTitle: "Nothing is in progress",
      idleBody: "You lose nothing by leaving.",
    },
    controls: {
      chooseCall: "Choose your call",
      makeCall: "Make your call",
      suggested: (what: string) => `Suggested: ${what}`,
      callN: (n: number, suggested: boolean) => `Call ${n}${suggested ? ", suggested" : ""}`,
      suitSuggested: (suit: string, suggested: boolean) => `${suit}${suggested ? ", suggested" : ""}`,
      redealRequested: "Redeal requested. Waiting…",
      redealOpen: "Redeal window open",
      requestRedeal: "Request redeal",
      chooseTrump: "Choose trump",
      takeLine: "Take the next player's cards? They get away.",
      takeSpoken: "Take the next player's cards",
      takeCards: "Take cards",
    },
    seatUi: {
      bot: "Bot",
      auto: "Auto-playing",
      offline: "Offline",
      theirTurn: "their turn",
      yourTurn: "YOUR TURN",
      inHand: (n: number) => (n === 1 ? "1 card in hand" : `${n} cards in hand`),
      timeLeft: (s: number) => (s === 1 ? "Time left: 1 second" : `Time left: ${s} seconds`),
      hand: (n: number) => (n === 1 ? "Your hand, 1 card" : `Your hand, ${n} cards`),
      faceDown: "face-down card",
      tapAgain: "Tap again to play it",
      tapToRaise: "Tap to raise, tap again to play",
    },
    sheets: {
      done: "Done",
      close: "Close",
      backToGame: "Back to the game",
      arrange: "Arrange my cards",
      layout: "Layout",
      fan: "Fan",
      spread: "Spread",
      spreadHint: "Every card whole, in rows.",
      fanHint: "Classic overlap; playable cards lift.",
      order: "Order",
      bySuit: "By suit",
      byRank: "By rank",
      rankHint: "Highest first, any suit.",
      suitHint: "Grouped by suit, colours alternating.",
      suggestion: "A suggestion",
      hintNote: "Hints see only what you see, never anyone's hand.",
      lastTrick: "The last trick",
      houseRules: "House rules",
      rulesFixed: "Fixed for this match. Start a new table to change them.",
      on: "On",
      off: "Off",
      table: "Table",
      leaveMatch: "Leave this match",
      rulesCaption: "What this table plays",
      arrangeCaption: "Fan or spread, by suit or by rank",
      tracker: "What has gone",
      trackerCaption: "Cards already played this hand",
      lastCaption: "Who played what",
      tableInfo: "Table info",
      infoCaption: "Game, rules preset and bots",
      hints: "Hints",
      hintsHint: "Adds a Hint button on your turn",
      timer: "Turn timer",
      timerHint: "When the bar runs out, a card is played for you",
      trackerNote: "Struck-through cards were played this hand; gold ones are yours. A card that returns to a hand is un-struck.",
      played: "played",
      mine: "in your hand",
      out: "still out",
    },
  },
  ur: {
    sep: "، ",
    seat: (n: number) => `نشست ${n}`,
    cards: (n: number) => (n === 1 ? "1 پتا" : `${n} پتے`),
    model: {
      notChosen: "ابھی نہیں چنا گیا",
      spokenCall: (call: number, won: number) => `کال ${call}، جیتے ${won}`,
      teamBadge: (team: string, tricks: number) => `ٹیم ${team} · ${tricks}`,
      teamSpoken: (team: string, tricks: number) => `ٹیم ${team}، ${tricks} ہاتھ`,
      awayBadge: (place: string) => `نکلے · ${place}`,
      awaySpoken: (place: string) => `نکل گئے، ${place}`,
      annulled: (reason: string) => `بازی منسوخ (${reason})۔ وہی دوبارہ بانٹے گا۔`,
      reasons: { redeal_request: "دوبارہ بانٹ کی درخواست", low_call_sum: "کالوں کا کل کم", guard: "حفاظتی حد" },
      handOf: (n: number, of: number) => `بازی ${n} از ${of}`,
      shuffling: "پتے پھینٹے جا رہے ہیں",
      trumpAlways: (suit: string, glyph: string) => `${suit} ترپ ہے ${glyph}`,
      sir: (double: boolean, target: number) => `${double ? "ڈبل" : "سنگل"} سر · ${target} تک`,
      pointsAB: (a: number, b: number) => `پوائنٹس A ${a} · B ${b}`,
      trumpIs: (suit: string) => `ترپ: ${suit}`,
      pile: (n: number) => `ڈھیر ${n}`,
      waitingTrump: "ترپ چنے جانے کا انتظار",
      pickedUpTrick: (name: string) => `${name} نے ہاتھ اٹھا لیا`,
      trickAside: "ہاتھ الگ رکھ دیا گیا",
      pts: (n: number) => `${n} پوائنٹس`,
      timesBhabhi: (n: number) => `${n} بار بھابھی`,
    },
    say: {
      matchOver: "میچ ختم",
      dealingFull: "پتے پھینٹے اور بانٹے جا رہے ہیں",
      handOver: "بازی ختم",
      weakHand: "پتے کمزور ہیں؟ دوبارہ بانٹ مانگیں",
      redealOpen: "دوبارہ بانٹ کا موقع کھلا ہے",
      chooseCall: "کتنے ہاتھ جیتیں گے؟",
      isCalling: (name: string) => `${name} کال کر رہے ہیں`,
      youNameTrump: "ترپ آپ چنیں",
      mayTake: "اگلے کھلاڑی کے پتے لے سکتے ہیں",
      isPlaying: (name: string) => `${name} کی باری`,
      leadAceSpades: "حکم کے اِکے سے شروع کریں",
      lead: "آپ کی چال: کوئی بھی پتا چلیں",
      leadShort: "کوئی بھی پتا چلیں",
      follow: (glyph: string, suit: string) => `${glyph} ${suit} ہی چلیں`,
      noSuitBreaks: (glyph: string) => `${glyph} نہیں: جو چلیں، ٹھلا ہوگا`,
      noSuitTrump: (glyph: string) => `${glyph} نہیں: ترپ یا کوئی بھی پتا`,
      yourTurn: (what: string) => `آپ کی باری: ${what}`,
      dealing: "پتے بانٹے جا رہے ہیں",
      redealWindow: "دوبارہ بانٹ کا موقع",
      waiting: "انتظار",
      breakWarn: (glyph: string, name: string, n: number) => `${glyph} نہیں: جو بھی چلیں، ${name} ${n} پتے اٹھائیں گے`,
      voidTag: (glyph: string) => `${glyph} نہیں`,
      nobodyTook: "کسی نے نہیں لیا۔",
      took: (name: string) => `${name} نے لیا۔`,
      pickedUpBroken: (name: string) => `${name} نے اٹھائے: ٹھلا لگا۔`,
      putAside: (name: string) => `الگ رکھا۔ اب ${name} کی چال۔`,
    },
    phase: {
      over: "میچ ختم",
      dealing: "بانٹ",
      handOver: "بازی ختم",
      window: "دوبارہ بانٹ کا موقع",
      calling: "کال",
      trump: "ترپ کا انتخاب",
      following: (glyph: string) => `${glyph} کی چال`,
      open: "کھلی چال",
    },
    hint: {
      none: "ابھی چلنے کو کچھ نہیں",
      noneWhy: "آپ کی باری پر مشورہ ملے گا۔",
      steadyLead: "ان پتوں سے محفوظ شروعات۔",
      follows: "رنگ ملاتا ہے، بڑا پتا بچا کر۔",
      trumpWins: "رنگ نہیں، ترپ ہاتھ جیت سکتا ہے۔",
      shed: "رنگ نہیں؛ سب سے بے کار پتا نکلتا ہے۔",
      least: "رنگ نہیں؛ اس میں سب سے کم نقصان۔",
      call: (n: number) => `کال ${n}`,
      callWhy: "آپ کے پتوں کی طاقت سے اندازہ۔",
      trump: (glyph: string, suit: string) => `${glyph} ${suit} ترپ`,
      trumpWhy: "آپ کا سب سے لمبا اور مضبوط رنگ۔",
      take: "اگلے کھلاڑی کے پتے لیں",
      takeWhy: "وہ نکل جاتے ہیں، چال آپ کے ہاتھ رہتی ہے۔",
      redeal: "دوبارہ بانٹنے کا کہیں",
      redealWhy: "پتے کافی کمزور ہیں، دوبارہ بانٹ لیں۔",
    },
    rules: {
      trump: "ترپ",
      trumpText: (suit: string, glyph: string) => `${suit} ${glyph} ہمیشہ ترپ ہے۔`,
      calls: "کال",
      callsText: (min: number, max: number) => `${min} سے ${max} ہاتھ تک کال کریں۔`,
      mustBeat: "جب ہو سکے ہاتھ جیتیں",
      mustBeatOn: "جیت سکتے ہیں تو جیتنا لازم۔",
      mustBeatOff: "رنگ کا کوئی بھی پتا چلیں۔",
      trumpIfWinning: "رنگ نہ ہو تو ترپ",
      trumpIfWinningOn: "رنگ نہ ہو تو جیتنے والا ترپ لازم۔",
      trumpIfWinningOff: "رنگ نہ ہو تو کچھ بھی چلیں۔",
      overtrick: "زائد ہاتھوں کے پوائنٹس",
      overtrickOn: "کال سے اوپر ہر ہاتھ 0.1 بڑھاتا ہے۔",
      overtrickOff: "کال سے اوپر کے ہاتھ کچھ نہیں بڑھاتے۔",
      redeal: "درخواست پر دوبارہ بانٹ",
      redealOn: "کمزور پتوں پر دوبارہ بانٹ مانگ سکتے ہیں۔",
      redealOff: "دوبارہ بانٹ کی درخواست نہیں۔",
      noSpade: "بغیر حکم کے پتے",
      noSpadeOn: "وہی کھلاڑی خود دوبارہ بانٹتا ہے۔",
      noSpadeOff: "جیسے بٹے، ویسے کھیلیں۔",
      firstLead: "پہلی چال",
      firstLeadNoTrump: "پہلی چال حکم سے نہیں۔",
      firstLeadAny: "کسی بھی پتے سے شروع کریں۔",
      direction: "سمت",
      clockwise: "کھیل گھڑی کی سمت چلتا ہے۔",
      counter: "کھیل گھڑی کی الٹی سمت چلتا ہے۔",
      length: "لمبائی",
      hands: (n: number) => (n === 1 ? "1 بازی۔" : `${n} بازیاں۔`),
      rounds: (n: number) => `${n} راؤنڈ۔`,
      variant: "قسم",
      double: "ڈبل سر: ڈھیر لینے کے لیے لگاتار دو ہاتھ جیتیں۔",
      single: "سنگل سر: پہلے سات ہاتھ، اسی ٹیم کی بازی۔",
      aces: "اِکے ڈھیر نہیں لیتے",
      acesOn: "لگاتار دو اِکوں سے ڈھیر نہیں ملتا۔",
      acesOff: "اِکے باقی پتوں کی طرح گنے جاتے ہیں۔",
      target: "جیت کے پوائنٹس",
      targetText: (n: number) => `پہلے ${n} تک۔`,
      handCourt: "بازی اور کوٹ",
      handCourtText: (hand: number, court: number) => `بازی کے ${hand}، کوٹ کے ${court}۔`,
      nextDealer: "اگلا بانٹنے والا",
      pagat: "ہارنے والی ٹیم اگلی بار بانٹتی ہے۔",
      rotate: "ہر بازی میں بانٹ اگلی نشست پر۔",
      thulla: "ٹھلا ہاتھ ختم کرتا ہے",
      thullaOn: "دوسرا رنگ آتے ہی ہاتھ ختم۔",
      thullaOff: "سب چلیں، پھر پتے اٹھائے جائیں۔",
      firstAside: "پہلا ہاتھ الگ",
      firstAsideOn: "حکم کے اِکے والا ہاتھ ہمیشہ الگ۔",
      firstAsideOff: "پہلا ہاتھ بھی اٹھایا جا سکتا ہے۔",
      lastCard: "آخری پتا",
      empty: {
        drawFromWaste: "آخری پتے سے جیتیں تو ڈھیر سے پتا لیں۔",
        drawFromNext: "آخری پتے سے جیتیں تو اگلے کھلاڑی سے پتا لیں۔",
        escapeIfThreePlus: "آخری پتے سے جیتیں اور تین یا زیادہ باقی ہوں تو آپ نکل گئے۔",
        passToNext: "آخری پتے سے جیتیں تو چال آگے چلی جاتی ہے۔",
      },
      takeHand: "پتے لینا",
      takeHandOn: "ہاتھ سے پہلے آپ اگلے کھلاڑی کے پتے لے سکتے ہیں۔",
      takeHandOff: "پتے نہیں لیے جا سکتے۔",
      twoLeft: "دو کھلاڑی باقی",
      twoLeftOn: "ڈھیر سے نکلا پتا چلا اور کاٹا جاتا ہے۔",
      twoLeftOff: "باقی ہاتھوں کی طرح کھیلا جاتا ہے۔",
      decks: "گڈیاں",
      twoDecks: "دو گڈیاں؛ ایک جیسے پتوں میں پہلے چلا ہوا جیتتا ہے۔",
      oneDeck: "ایک گڈی۔",
      upTo: (rounds: number, limit: number) => `${rounds} بازیاں، یا جب تک کوئی ${limit} بار بھابھی نہ بنے۔`,
      deal: "بانٹ",
      even: "برابر بانٹ۔",
      extra: (n: number) => `آپ ${n} زائد پتوں سے شروع کرتے ہیں۔`,
    },
    screen: {
      menu: "میز کا مینو",
      tracker: "کون سے پتے جا چکے",
      undo: "آخری پتا واپس لیں",
      last: "پچھلا ہاتھ",
      hint: "مشورہ",
      inTrick: (list: string) => `ہاتھ میں: ${list}`,
      trickEmpty: "ہاتھ میں کوئی پتا نہیں",
      waitingDeal: "بانٹ کا انتظار",
      tableInfo: "میز کی معلومات",
      leaveTitle: "یہ میچ چھوڑیں؟",
      leave: "میچ چھوڑیں",
      stay: "میز پر رہیں",
      inHand: (n: number) => `ہاتھ میں ${n}`,
      seats: (n: number) => `${n} نشستیں`,
      endsTitle: "یہ کھیل یہیں ختم",
      endsBody: "بوٹس والا کھیل رُکتا نہیں: چھوڑنے سے میز بند ہو جائے گی۔",
      droppedTitle: "جاری بازی ختم ہو جائے گی",
      droppedBody: "نتیجہ درج نہیں ہوگا، چلتا اسکور بھی ختم۔",
      idleTitle: "کچھ جاری نہیں",
      idleBody: "چھوڑنے سے کچھ نہیں کھوئیں گے۔",
    },
    controls: {
      chooseCall: "اپنی کال چنیں",
      makeCall: "اپنی کال کریں",
      suggested: (what: string) => `مشورہ: ${what}`,
      callN: (n: number, suggested: boolean) => `کال ${n}${suggested ? "، مشورہ" : ""}`,
      suitSuggested: (suit: string, suggested: boolean) => `${suit}${suggested ? "، مشورہ" : ""}`,
      redealRequested: "درخواست ہو گئی۔ انتظار کریں…",
      redealOpen: "دوبارہ بانٹ کا موقع کھلا ہے",
      requestRedeal: "دوبارہ بانٹ مانگیں",
      chooseTrump: "ترپ چنیں",
      takeLine: "اگلے کھلاڑی کے پتے لیں؟ وہ نکل جائیں گے۔",
      takeSpoken: "اگلے کھلاڑی کے پتے لیں",
      takeCards: "پتے لیں",
    },
    seatUi: {
      bot: "بوٹ",
      auto: "خودکار",
      offline: "آف لائن",
      theirTurn: "ان کی باری",
      yourTurn: "آپ کی باری",
      inHand: (n: number) => (n === 1 ? "ہاتھ میں 1 پتا" : `ہاتھ میں ${n} پتے`),
      timeLeft: (s: number) => `باقی وقت: ${s} سیکنڈ`,
      hand: (n: number) => (n === 1 ? "آپ کے پتے، 1 پتا" : `آپ کے پتے، ${n} پتے`),
      faceDown: "الٹا پتا",
      tapAgain: "چلنے کے لیے دوبارہ ٹیپ کریں",
      tapToRaise: "اٹھانے کو ٹیپ، چلنے کو دوبارہ ٹیپ",
    },
    sheets: {
      done: "ہو گیا",
      close: "بند کریں",
      backToGame: "کھیل پر واپس",
      arrange: "پتے ترتیب دیں",
      layout: "انداز",
      fan: "پنکھا",
      spread: "پھیلاؤ",
      spreadHint: "ہر پتا پورا، قطاروں میں۔",
      fanHint: "روایتی انداز؛ چلنے والے پتے اوپر۔",
      order: "ترتیب",
      bySuit: "رنگ وار",
      byRank: "بڑے سے چھوٹا",
      rankHint: "بڑا پہلے، رنگ کوئی بھی۔",
      suitHint: "رنگ وار، لال کالے باری باری۔",
      suggestion: "ایک مشورہ",
      hintNote: "مشورہ وہی دیکھتا ہے جو آپ دیکھتے ہیں، کسی کے پتے نہیں۔",
      lastTrick: "پچھلا ہاتھ",
      houseRules: "کھیل کے اصول",
      rulesFixed: "اس میچ کے اصول طے ہیں۔ بدلنے کو نئی میز لگائیں۔",
      on: "آن",
      off: "آف",
      table: "میز",
      leaveMatch: "یہ میچ چھوڑیں",
      rulesCaption: "یہ میز کیا کھیلتی ہے",
      arrangeCaption: "پنکھا یا پھیلاؤ، رنگ وار یا بڑے سے چھوٹا",
      tracker: "کون سے پتے جا چکے",
      trackerCaption: "اس بازی میں چلے ہوئے پتے",
      lastCaption: "کس نے کیا چلا",
      tableInfo: "میز کی معلومات",
      infoCaption: "کھیل، اصول اور بوٹس",
      hints: "مشورے",
      hintsHint: "باری پر مشورے کا بٹن",
      timer: "باری کا ٹائمر",
      timerHint: "پٹی ختم ہو تو آپ کی جگہ پتا چل دیا جائے گا",
      trackerNote: "کٹے پتے اس بازی میں چل چکے، سنہری آپ کے ہیں۔ ہاتھ میں لوٹا پتا پھر کھل جاتا ہے۔",
      played: "چل چکا",
      mine: "آپ کے ہاتھ میں",
      out: "ابھی باہر",
    },
  },
  hi: {
    sep: ", ",
    seat: (n: number) => `सीट ${n}`,
    cards: (n: number) => (n === 1 ? "1 पत्ता" : `${n} पत्ते`),
    model: {
      notChosen: "अभी नहीं चुना",
      spokenCall: (call: number, won: number) => `कॉल ${call}, जीते ${won}`,
      teamBadge: (team: string, tricks: number) => `टीम ${team} · ${tricks}`,
      teamSpoken: (team: string, tricks: number) => `टीम ${team}, ${tricks} हाथ`,
      awayBadge: (place: string) => `निकले · ${place}`,
      awaySpoken: (place: string) => `निकल गए, ${place}`,
      annulled: (reason: string) => `बाज़ी रद्द (${reason})। वही फिर बाँटेगा।`,
      reasons: { redeal_request: "फिर से बाँटने की माँग", low_call_sum: "कुल कॉल कम", guard: "सुरक्षा सीमा" },
      handOf: (n: number, of: number) => `बाज़ी ${n} / ${of}`,
      shuffling: "पत्ते फेंटे जा रहे हैं",
      trumpAlways: (suit: string, glyph: string) => `${suit} तुरुप है ${glyph}`,
      sir: (double: boolean, target: number) => `${double ? "डबल" : "सिंगल"} सर · ${target} तक`,
      pointsAB: (a: number, b: number) => `पॉइंट A ${a} · B ${b}`,
      trumpIs: (suit: string) => `तुरुप: ${suit}`,
      pile: (n: number) => `ढेर ${n}`,
      waitingTrump: "तुरुप चुने जाने का इंतज़ार",
      pickedUpTrick: (name: string) => `${name} ने हाथ उठा लिया`,
      trickAside: "हाथ अलग रख दिया गया",
      pts: (n: number) => `${n} पॉइंट`,
      timesBhabhi: (n: number) => `${n} बार भाभी`,
    },
    say: {
      matchOver: "मैच खत्म",
      dealingFull: "पत्ते फेंटे और बाँटे जा रहे हैं",
      handOver: "बाज़ी खत्म",
      weakHand: "पत्ते कमज़ोर? फिर से बँटाई माँगें",
      redealOpen: "फिर से बाँटने का मौका खुला है",
      chooseCall: "कितने हाथ जीतेंगे?",
      isCalling: (name: string) => `${name} कॉल कर रहे हैं`,
      youNameTrump: "तुरुप आप चुनें",
      mayTake: "अगले खिलाड़ी के पत्ते ले सकते हैं",
      isPlaying: (name: string) => `${name} की बारी`,
      leadAceSpades: "हुकुम के इक्के से शुरू करें",
      lead: "आपकी चाल: कोई भी पत्ता चलें",
      leadShort: "कोई भी पत्ता चलें",
      follow: (glyph: string, suit: string) => `${glyph} ${suit} ही चलें`,
      noSuitBreaks: (glyph: string) => `${glyph} नहीं: जो चलें, ठुल्ला होगा`,
      noSuitTrump: (glyph: string) => `${glyph} नहीं: तुरुप या कोई भी पत्ता`,
      yourTurn: (what: string) => `आपकी बारी: ${what}`,
      dealing: "पत्ते बँट रहे हैं",
      redealWindow: "फिर से बाँटने का मौका",
      waiting: "इंतज़ार",
      breakWarn: (glyph: string, name: string, n: number) => `${glyph} नहीं: कुछ भी चलें, ${name} ${n} पत्ते उठाएँगे`,
      voidTag: (glyph: string) => `${glyph} नहीं`,
      nobodyTook: "किसी ने नहीं लिया।",
      took: (name: string) => `${name} ने लिया।`,
      pickedUpBroken: (name: string) => `${name} ने उठाए: ठुल्ला लगा।`,
      putAside: (name: string) => `अलग रखा। अब ${name} की चाल।`,
    },
    phase: {
      over: "मैच खत्म",
      dealing: "बँटाई",
      handOver: "बाज़ी खत्म",
      window: "फिर से बाँटने का मौका",
      calling: "कॉल",
      trump: "तुरुप का चुनाव",
      following: (glyph: string) => `${glyph} की चाल`,
      open: "खुली चाल",
    },
    hint: {
      none: "अभी चलने को कुछ नहीं",
      noneWhy: "आपकी बारी पर सुझाव मिलेंगे।",
      steadyLead: "इन पत्तों से सुरक्षित शुरुआत।",
      follows: "रंग मिलाता है, बड़ा पत्ता बचाकर।",
      trumpWins: "रंग नहीं, तुरुप हाथ जीत सकता है।",
      shed: "रंग नहीं; सबसे बेकार पत्ता निकलता है।",
      least: "रंग नहीं; इसमें सबसे कम नुकसान।",
      call: (n: number) => `कॉल ${n}`,
      callWhy: "आपके पत्तों की ताकत से अंदाज़ा।",
      trump: (glyph: string, suit: string) => `${glyph} ${suit} तुरुप`,
      trumpWhy: "आपका सबसे लंबा और मज़बूत रंग।",
      take: "अगले खिलाड़ी के पत्ते लें",
      takeWhy: "वे निकलते हैं, चाल आपके हाथ रहती है।",
      redeal: "फिर से बाँटने को कहें",
      redealWhy: "पत्ते काफ़ी कमज़ोर हैं, फिर से बँटवा लें।",
    },
    rules: {
      trump: "तुरुप",
      trumpText: (suit: string, glyph: string) => `${suit} ${glyph} हमेशा तुरुप है।`,
      calls: "कॉल",
      callsText: (min: number, max: number) => `${min} से ${max} हाथ तक कॉल करें।`,
      mustBeat: "जब हो सके हाथ जीतें",
      mustBeatOn: "जीत सकें तो जीतना ज़रूरी।",
      mustBeatOff: "रंग का कोई भी पत्ता चलें।",
      trumpIfWinning: "रंग न हो तो तुरुप",
      trumpIfWinningOn: "रंग न हो तो जीतने वाला तुरुप ज़रूरी।",
      trumpIfWinningOff: "रंग न हो तो कुछ भी चलें।",
      overtrick: "ज़्यादा हाथों के पॉइंट",
      overtrickOn: "कॉल से ऊपर हर हाथ 0.1 जोड़ता है।",
      overtrickOff: "कॉल से ऊपर के हाथ कुछ नहीं जोड़ते।",
      redeal: "माँगने पर फिर से बँटाई",
      redealOn: "कमज़ोर पत्तों पर फिर से बँटाई माँग सकते हैं।",
      redealOff: "फिर से बँटाई की माँग नहीं।",
      noSpade: "बिना हुकुम के पत्ते",
      noSpadeOn: "वही खिलाड़ी अपने आप फिर बाँटता है।",
      noSpadeOff: "जैसे बँटे, वैसे खेलें।",
      firstLead: "पहली चाल",
      firstLeadNoTrump: "पहली चाल हुकुम से नहीं।",
      firstLeadAny: "किसी भी पत्ते से शुरू करें।",
      direction: "दिशा",
      clockwise: "खेल घड़ी की दिशा में चलता है।",
      counter: "खेल घड़ी की उल्टी दिशा में चलता है।",
      length: "लंबाई",
      hands: (n: number) => `${n} बाज़ी।`,
      rounds: (n: number) => `${n} राउंड।`,
      variant: "प्रकार",
      double: "डबल सर: ढेर लेने के लिए लगातार दो हाथ जीतें।",
      single: "सिंगल सर: पहले सात हाथ, उसी टीम की बाज़ी।",
      aces: "इक्के ढेर नहीं लेते",
      acesOn: "लगातार दो इक्कों से ढेर नहीं मिलता।",
      acesOff: "इक्के बाकी पत्तों की तरह गिने जाते हैं।",
      target: "जीत के पॉइंट",
      targetText: (n: number) => `पहले ${n} तक।`,
      handCourt: "बाज़ी और कोट",
      handCourtText: (hand: number, court: number) => `बाज़ी के ${hand}, कोट के ${court}।`,
      nextDealer: "अगला बाँटने वाला",
      pagat: "हारने वाली टीम अगली बार बाँटती है।",
      rotate: "हर बाज़ी में बँटाई अगली सीट पर।",
      thulla: "ठुल्ला से हाथ खत्म",
      thullaOn: "दूसरा रंग आते ही हाथ खत्म।",
      thullaOff: "सब चलें, फिर पत्ते उठाए जाएँ।",
      firstAside: "पहला हाथ अलग",
      firstAsideOn: "हुकुम के इक्के वाला हाथ हमेशा अलग।",
      firstAsideOff: "पहला हाथ भी उठाया जा सकता है।",
      lastCard: "आखिरी पत्ता",
      empty: {
        drawFromWaste: "आखिरी पत्ते से जीतें तो ढेर से पत्ता लें।",
        drawFromNext: "आखिरी पत्ते से जीतें तो अगले खिलाड़ी से पत्ता लें।",
        escapeIfThreePlus: "आखिरी पत्ते से जीतें और तीन या ज़्यादा बचे हों तो आप निकल जाते हैं।",
        passToNext: "आखिरी पत्ते से जीतें तो चाल आगे चली जाती है।",
      },
      takeHand: "पत्ते लेना",
      takeHandOn: "हाथ से पहले आप अगले खिलाड़ी के पत्ते ले सकते हैं।",
      takeHandOff: "पत्ते नहीं लिए जा सकते।",
      twoLeft: "दो खिलाड़ी बचे",
      twoLeftOn: "ढेर से निकला पत्ता चला और काटा जाता है।",
      twoLeftOff: "बाकी हाथों की तरह खेला जाता है।",
      decks: "गड्डियाँ",
      twoDecks: "दो गड्डियाँ; एक जैसे पत्तों में पहले चला हुआ जीतता है।",
      oneDeck: "एक गड्डी।",
      upTo: (rounds: number, limit: number) => `${rounds} बाज़ी, या जब तक कोई ${limit} बार भाभी न बने।`,
      deal: "बँटाई",
      even: "बराबर बँटाई।",
      extra: (n: number) => `आप ${n} ज़्यादा पत्तों से शुरू करते हैं।`,
    },
    screen: {
      menu: "टेबल मेनू",
      tracker: "कौन से पत्ते जा चुके",
      undo: "आखिरी पत्ता वापस लें",
      last: "पिछला हाथ",
      hint: "सुझाव",
      inTrick: (list: string) => `हाथ में: ${list}`,
      trickEmpty: "हाथ में कोई पत्ता नहीं",
      waitingDeal: "बँटाई का इंतज़ार",
      tableInfo: "टेबल की जानकारी",
      leaveTitle: "यह मैच छोड़ें?",
      leave: "मैच छोड़ें",
      stay: "टेबल पर रहें",
      inHand: (n: number) => `हाथ में ${n}`,
      seats: (n: number) => `${n} सीटें`,
      endsTitle: "यह खेल यहीं खत्म",
      endsBody: "बॉट वाला खेल रुकता नहीं: छोड़ते ही टेबल बंद।",
      droppedTitle: "चल रही बाज़ी खत्म हो जाएगी",
      droppedBody: "नतीजा दर्ज नहीं होगा, चालू स्कोर भी जाएगा।",
      idleTitle: "कुछ चल नहीं रहा",
      idleBody: "छोड़ने पर कुछ नहीं खोएँगे।",
    },
    controls: {
      chooseCall: "अपनी कॉल चुनें",
      makeCall: "अपनी कॉल करें",
      suggested: (what: string) => `सुझाव: ${what}`,
      callN: (n: number, suggested: boolean) => `कॉल ${n}${suggested ? ", सुझाव" : ""}`,
      suitSuggested: (suit: string, suggested: boolean) => `${suit}${suggested ? ", सुझाव" : ""}`,
      redealRequested: "माँग हो गई। इंतज़ार करें…",
      redealOpen: "फिर से बाँटने का मौका खुला है",
      requestRedeal: "फिर से बँटाई माँगें",
      chooseTrump: "तुरुप चुनें",
      takeLine: "अगले खिलाड़ी के पत्ते लें? वे निकल जाएँगे।",
      takeSpoken: "अगले खिलाड़ी के पत्ते लें",
      takeCards: "पत्ते लें",
    },
    seatUi: {
      bot: "बॉट",
      auto: "ऑटो-प्ले",
      offline: "ऑफ़लाइन",
      theirTurn: "उनकी बारी",
      yourTurn: "आपकी बारी",
      inHand: (n: number) => (n === 1 ? "हाथ में 1 पत्ता" : `हाथ में ${n} पत्ते`),
      timeLeft: (s: number) => `बचा समय: ${s} सेकंड`,
      hand: (n: number) => (n === 1 ? "आपके पत्ते, 1 पत्ता" : `आपके पत्ते, ${n} पत्ते`),
      faceDown: "उल्टा पत्ता",
      tapAgain: "चलने के लिए फिर से टैप करें",
      tapToRaise: "उठाने को टैप, चलने को फिर टैप",
    },
    sheets: {
      done: "हो गया",
      close: "बंद करें",
      backToGame: "खेल पर वापस",
      arrange: "पत्ते सजाएँ",
      layout: "ढंग",
      fan: "पंखा",
      spread: "फैलाव",
      spreadHint: "हर पत्ता पूरा, कतारों में।",
      fanHint: "पुराना तरीका; चलने लायक पत्ते ऊपर।",
      order: "क्रम",
      bySuit: "रंग से",
      byRank: "बड़े से छोटा",
      rankHint: "बड़ा पहले, रंग कोई भी।",
      suitHint: "रंग से, लाल-काले बारी-बारी।",
      suggestion: "एक सुझाव",
      hintNote: "सुझाव वही देखता है जो आप देखते हैं, किसी के पत्ते नहीं।",
      lastTrick: "पिछला हाथ",
      houseRules: "खेल के नियम",
      rulesFixed: "इस मैच के नियम तय हैं। बदलने को नई टेबल लगाएँ।",
      on: "चालू",
      off: "बंद",
      table: "टेबल",
      leaveMatch: "यह मैच छोड़ें",
      rulesCaption: "यह टेबल क्या खेलती है",
      arrangeCaption: "पंखा या फैलाव, रंग से या बड़े से छोटा",
      tracker: "कौन से पत्ते जा चुके",
      trackerCaption: "इस बाज़ी में चले गए पत्ते",
      lastCaption: "किसने क्या चला",
      tableInfo: "टेबल की जानकारी",
      infoCaption: "खेल, नियम और बॉट्स",
      hints: "सुझाव",
      hintsHint: "बारी पर सुझाव का बटन",
      timer: "बारी का टाइमर",
      timerHint: "पट्टी खत्म होते ही आपकी जगह पत्ता चल जाएगा",
      trackerNote: "कटे पत्ते इस बाज़ी में चल चुके, सुनहरे आपके हैं। हाथ में लौटा पत्ता फिर खुल जाता है।",
      played: "चल चुका",
      mine: "आपके हाथ में",
      out: "अभी बाहर",
    },
  },
  ne: {
    sep: ", ",
    seat: (n: number) => `सिट ${n}`,
    cards: (n: number) => `${n} पत्ती`,
    model: {
      notChosen: "अझै छानिएको छैन",
      spokenCall: (call: number, won: number) => `कल ${call}, जितेको ${won}`,
      teamBadge: (team: string, tricks: number) => `टिम ${team} · ${tricks}`,
      teamSpoken: (team: string, tricks: number) => `टिम ${team}, ${tricks} हात`,
      awayBadge: (place: string) => `उम्क्यो · ${place}`,
      awaySpoken: (place: string) => `${place} भएर उम्क्यो`,
      annulled: (reason: string) => `बाजी रद्द (${reason})। उही खेलाडीले फेरि बाँड्छ।`,
      reasons: { redeal_request: "फेरि बाँड्ने अनुरोध", low_call_sum: "कुल कल कम", guard: "सुरक्षा सीमा" },
      handOf: (n: number, of: number) => `बाजी ${n} / ${of}`,
      shuffling: "पत्ती फिटिँदै छ",
      trumpAlways: (suit: string, glyph: string) => `${suit} तुरुप हो ${glyph}`,
      sir: (double: boolean, target: number) => `${double ? "डबल" : "सिंगल"} सर · ${target} सम्म`,
      pointsAB: (a: number, b: number) => `अङ्क A ${a} · B ${b}`,
      trumpIs: (suit: string) => `तुरुप: ${suit}`,
      pile: (n: number) => `थुप्रो ${n}`,
      waitingTrump: "तुरुप छानिने पर्खाइमा",
      pickedUpTrick: (name: string) => `${name}ले हात उठाए`,
      trickAside: "हात छुट्टै राखियो",
      pts: (n: number) => `${n} अङ्क`,
      timesBhabhi: (n: number) => `${n} पटक भाभी`,
    },
    say: {
      matchOver: "म्याच सकियो",
      dealingFull: "पत्ती फिटेर बाँडिँदै छ",
      handOver: "बाजी सकियो",
      weakHand: "पत्ती कमजोर? फेरि बाँड्न माग्नुहोस्",
      redealOpen: "फेरि बाँड्ने मौका खुला छ",
      chooseCall: "कति हात जित्नुहुन्छ?",
      isCalling: (name: string) => `${name} कल गर्दै`,
      youNameTrump: "तुरुप तपाईं छान्नुहोस्",
      mayTake: "अर्को खेलाडीका पत्ती लिन सक्नुहुन्छ",
      isPlaying: (name: string) => `${name}को पालो`,
      leadAceSpades: "हुकुमको एक्काबाट सुरु गर्नुहोस्",
      lead: "तपाईंको चाल: जुनसुकै पत्ती खेल्नुहोस्",
      leadShort: "जुनसुकै पत्ती खेल्नुहोस्",
      follow: (glyph: string, suit: string) => `${glyph} ${suit} नै खेल्नुहोस्`,
      noSuitBreaks: (glyph: string) => `${glyph} छैन: जे खेले पनि ठुल्ला`,
      noSuitTrump: (glyph: string) => `${glyph} छैन: तुरुप वा जुनसुकै पत्ती`,
      yourTurn: (what: string) => `तपाईंको पालो: ${what}`,
      dealing: "पत्ती बाँडिँदै",
      redealWindow: "फेरि बाँड्ने मौका",
      waiting: "पर्खाइ",
      breakWarn: (glyph: string, name: string, n: number) => `${glyph} छैन: जे खेले पनि ${name}ले ${n} पत्ती उठाउँछन्`,
      voidTag: (glyph: string) => `${glyph} छैन`,
      nobodyTook: "कसैले लिएन।",
      took: (name: string) => `${name}ले लिए।`,
      pickedUpBroken: (name: string) => `${name}ले उठाए: ठुल्ला पर्‍यो।`,
      putAside: (name: string) => `छुट्टै राखियो। अब ${name}को चाल।`,
    },
    phase: {
      over: "म्याच सकियो",
      dealing: "बाँडाइ",
      handOver: "बाजी सकियो",
      window: "फेरि बाँड्ने मौका",
      calling: "कल",
      trump: "तुरुप छनोट",
      following: (glyph: string) => `${glyph}को चाल`,
      open: "खुला चाल",
    },
    hint: {
      none: "अहिले खेल्ने केही छैन",
      noneWhy: "तपाईंको पालोमा सुझाव आउँछ।",
      steadyLead: "यी पत्तीबाट सुरक्षित सुरुवात।",
      follows: "रङ मिलाउँछ, ठूलो पत्ती जोगाएर।",
      trumpWins: "रङ छैन, तुरुपले हात जित्न सक्छ।",
      shed: "रङ छैन; सबैभन्दा बेकामको पत्ती फाल्छ।",
      least: "रङ छैन; यसमा सबैभन्दा कम घाटा।",
      call: (n: number) => `कल ${n}`,
      callWhy: "तपाईंका पत्तीको बलअनुसार अनुमान।",
      trump: (glyph: string, suit: string) => `${glyph} ${suit} तुरुप`,
      trumpWhy: "तपाईंको सबैभन्दा लामो र बलियो रङ।",
      take: "अर्को खेलाडीका पत्ती लिनुहोस्",
      takeWhy: "उनी उम्कन्छन्, चाल तपाईंकै हातमा।",
      redeal: "फेरि बाँड्न भन्नुहोस्",
      redealWhy: "पत्ती निकै कमजोर छन्, फेरि बँडाउनुहोस्।",
    },
    rules: {
      trump: "तुरुप",
      trumpText: (suit: string, glyph: string) => `${suit} ${glyph} सधैँ तुरुप हो।`,
      calls: "कल",
      callsText: (min: number, max: number) => `${min} देखि ${max} हातसम्म कल गर्नुहोस्।`,
      mustBeat: "सकेसम्म हात जित्नुहोस्",
      mustBeatOn: "जित्न सके जित्नैपर्छ।",
      mustBeatOff: "रङको जुनसुकै पत्ती खेल्नुहोस्।",
      trumpIfWinning: "रङ नभए तुरुप",
      trumpIfWinningOn: "रङ नभए जित्ने तुरुप खेल्नैपर्छ।",
      trumpIfWinningOff: "रङ नभए जे पनि खेल्नुहोस्।",
      overtrick: "बढी हातको अङ्क",
      overtrickOn: "कलभन्दा माथिको हरेक हातले 0.1 थप्छ।",
      overtrickOff: "कलभन्दा माथिका हातले केही थप्दैनन्।",
      redeal: "अनुरोधमा फेरि बाँड्ने",
      redealOn: "कमजोर पत्तीमा फेरि बाँड्न माग्न सकिन्छ।",
      redealOff: "फेरि बाँड्ने अनुरोध छैन।",
      noSpade: "हुकुम नभएको पत्ती",
      noSpadeOn: "उही खेलाडीले आफैँ फेरि बाँड्छ।",
      noSpadeOff: "जस्तो बाँडियो, त्यस्तै खेलिन्छ।",
      firstLead: "पहिलो चाल",
      firstLeadNoTrump: "पहिलो चाल हुकुमबाट हुँदैन।",
      firstLeadAny: "जुनसुकै पत्तीबाट सुरु गर्नुहोस्।",
      direction: "दिशा",
      clockwise: "खेल घडीको दिशामा चल्छ।",
      counter: "खेल घडीको उल्टो दिशामा चल्छ।",
      length: "लम्बाइ",
      hands: (n: number) => `${n} बाजी।`,
      rounds: (n: number) => `${n} राउन्ड।`,
      variant: "प्रकार",
      double: "डबल सर: थुप्रो लिन लगातार दुई हात जित्नुहोस्।",
      single: "सिंगल सर: पहिले सात हात जित्ने टिमको बाजी।",
      aces: "एक्काले थुप्रो लिँदैन",
      acesOn: "लगातार दुई एक्काले थुप्रो पाउँदैन।",
      acesOff: "एक्का अरू पत्तीजस्तै गनिन्छ।",
      target: "जित्ने अङ्क",
      targetText: (n: number) => `पहिले ${n} पुग्ने।`,
      handCourt: "बाजी र कोट",
      handCourtText: (hand: number, court: number) => `बाजीको ${hand}, कोटको ${court}।`,
      nextDealer: "अर्को बाँड्ने",
      pagat: "हार्ने टिमले अर्को पटक बाँड्छ।",
      rotate: "हरेक बाजीमा बाँड्ने पालो अर्को सिटमा।",
      thulla: "ठुल्लाले हात टुङ्गिन्छ",
      thullaOn: "अर्को रङ आउनेबित्तिकै हात टुङ्गिन्छ।",
      thullaOff: "सबैले खेलेपछि पत्ती उठाइन्छ।",
      firstAside: "पहिलो हात छुट्टै",
      firstAsideOn: "हुकुमको एक्काको हात सधैँ छुट्टै।",
      firstAsideOff: "पहिलो हात पनि उठाउन सकिन्छ।",
      lastCard: "अन्तिम पत्ती",
      empty: {
        drawFromWaste: "अन्तिम पत्तीले जिते थुप्रोबाट पत्ती लिनुहुन्छ।",
        drawFromNext: "अन्तिम पत्तीले जिते अर्को खेलाडीबाट पत्ती लिनुहुन्छ।",
        escapeIfThreePlus: "अन्तिम पत्तीले जिते र तीन वा बढी बाँकी भए तपाईं उम्कनुहुन्छ।",
        passToNext: "अन्तिम पत्तीले जिते चाल अर्कोलाई सर्छ।",
      },
      takeHand: "पत्ती लिने",
      takeHandOn: "हात अघि तपाईं अर्को खेलाडीका पत्ती लिन सक्नुहुन्छ।",
      takeHandOff: "पत्ती लिन मिल्दैन।",
      twoLeft: "दुई खेलाडी बाँकी",
      twoLeftOn: "थुप्रोबाट निकालेको पत्ती चालिन्छ र काटिन्छ।",
      twoLeftOff: "अरू हातजस्तै खेलिन्छ।",
      decks: "गड्डी",
      twoDecks: "दुई गड्डी; उस्तै पत्तीमा पहिले खेलिएकोले जित्छ।",
      oneDeck: "एक गड्डी।",
      upTo: (rounds: number, limit: number) => `${rounds} बाजी, वा कोही ${limit} पटक भाभी नबनेसम्म।`,
      deal: "बाँडाइ",
      even: "बराबर बाँडाइ।",
      extra: (n: number) => `तपाईं ${n} वटा बढी पत्तीसहित सुरु गर्नुहुन्छ।`,
    },
    screen: {
      menu: "टेबल मेनु",
      tracker: "कुन पत्ती गइसके",
      undo: "अन्तिम पत्ती फिर्ता लिनुहोस्",
      last: "अघिल्लो हात",
      hint: "सुझाव",
      inTrick: (list: string) => `हातमा: ${list}`,
      trickEmpty: "हातमा कुनै पत्ती छैन",
      waitingDeal: "बाँडाइको पर्खाइ",
      tableInfo: "टेबलको जानकारी",
      leaveTitle: "यो म्याच छोड्ने?",
      leave: "म्याच छोड्नुहोस्",
      stay: "टेबलमै बस्नुहोस्",
      inHand: (n: number) => `हातमा ${n}`,
      seats: (n: number) => `${n} सिट`,
      endsTitle: "यो खेल यहीँ सकिन्छ",
      endsBody: "बोटसँगको खेल रोकिँदैन: छोड्दा टेबल बन्द हुन्छ।",
      droppedTitle: "चलिरहेको बाजी हट्छ",
      droppedBody: "नतिजा दर्ता हुँदैन, चलिरहेको स्कोर पनि जान्छ।",
      idleTitle: "केही चलिरहेको छैन",
      idleBody: "छोड्दा केही गुम्दैन।",
    },
    controls: {
      chooseCall: "आफ्नो कल छान्नुहोस्",
      makeCall: "आफ्नो कल गर्नुहोस्",
      suggested: (what: string) => `सुझाव: ${what}`,
      callN: (n: number, suggested: boolean) => `कल ${n}${suggested ? ", सुझाव" : ""}`,
      suitSuggested: (suit: string, suggested: boolean) => `${suit}${suggested ? ", सुझाव" : ""}`,
      redealRequested: "अनुरोध गरियो। पर्खनुहोस्…",
      redealOpen: "फेरि बाँड्ने मौका खुला छ",
      requestRedeal: "फेरि बाँड्न माग्नुहोस्",
      chooseTrump: "तुरुप छान्नुहोस्",
      takeLine: "अर्को खेलाडीका पत्ती लिने? उनी उम्कन्छन्।",
      takeSpoken: "अर्को खेलाडीका पत्ती लिनुहोस्",
      takeCards: "पत्ती लिनुहोस्",
    },
    seatUi: {
      bot: "बोट",
      auto: "आफैँ खेल्दै",
      offline: "अफलाइन",
      theirTurn: "उनको पालो",
      yourTurn: "तपाईंको पालो",
      inHand: (n: number) => `हातमा ${n} पत्ती`,
      timeLeft: (s: number) => `बाँकी समय: ${s} सेकेन्ड`,
      hand: (n: number) => `तपाईंका पत्ती, ${n} वटा`,
      faceDown: "घोप्टो पत्ती",
      tapAgain: "खेल्न फेरि ट्याप गर्नुहोस्",
      tapToRaise: "उठाउन ट्याप, खेल्न फेरि ट्याप",
    },
    sheets: {
      done: "भयो",
      close: "बन्द गर्नुहोस्",
      backToGame: "खेलमा फर्कनुहोस्",
      arrange: "पत्ती मिलाउनुहोस्",
      layout: "ढाँचा",
      fan: "पङ्खा",
      spread: "फैलाउने",
      spreadHint: "हरेक पत्ती पूरै, लहरमा।",
      fanHint: "पुरानो तरिका; खेल्न मिल्ने पत्ती माथि।",
      order: "क्रम",
      bySuit: "रङअनुसार",
      byRank: "ठूलोदेखि सानो",
      rankHint: "ठूलो पहिले, रङ जुनसुकै।",
      suitHint: "रङअनुसार, रातो-कालो पालैपालो।",
      suggestion: "एउटा सुझाव",
      hintNote: "सुझावले तपाईंले देख्ने मात्र हेर्छ, कसैको पत्ती होइन।",
      lastTrick: "अघिल्लो हात",
      houseRules: "खेलका नियम",
      rulesFixed: "यो म्याचका नियम तय छन्। बदल्न नयाँ टेबल खोल्नुहोस्।",
      on: "खुला",
      off: "बन्द",
      table: "टेबल",
      leaveMatch: "यो म्याच छोड्नुहोस्",
      rulesCaption: "यो टेबलमा के खेलिन्छ",
      arrangeCaption: "पङ्खा वा फैलाउने, रङ वा ठूलोदेखि सानो",
      tracker: "कुन पत्ती गइसके",
      trackerCaption: "यो बाजीमा खेलिसकेका पत्ती",
      lastCaption: "कसले के खेल्यो",
      tableInfo: "टेबलको जानकारी",
      infoCaption: "खेल, नियम र बोट",
      hints: "सुझाव",
      hintsHint: "पालोमा सुझाव बटन",
      timer: "पालोको टाइमर",
      timerHint: "पट्टी सकिएपछि तपाईंको सट्टा पत्ती खेलिन्छ",
      trackerNote: "काटिएका पत्ती यो बाजीमा खेलिसकिए, सुनौला तपाईंका हुन्। हातमा फर्केको पत्ती फेरि खुल्छ।",
      played: "खेलिसकियो",
      mine: "तपाईंको हातमा",
      out: "अझै बाहिर",
    },
  },
  bn: {
    sep: ", ",
    seat: (n: number) => `আসন ${n}`,
    cards: (n: number) => `${n}টি তাস`,
    model: {
      notChosen: "এখনও বাছা হয়নি",
      spokenCall: (call: number, won: number) => `ডাক ${call}, জিতেছে ${won}`,
      teamBadge: (team: string, tricks: number) => `দল ${team} · ${tricks}`,
      teamSpoken: (team: string, tricks: number) => `দল ${team}, ${tricks}টি পিঠ`,
      awayBadge: (place: string) => `বেরিয়েছে · ${place}`,
      awaySpoken: (place: string) => `${place} হয়ে বেরিয়ে গেছে`,
      annulled: (reason: string) => `দান বাতিল (${reason})। একই জন আবার বাঁটবে।`,
      reasons: { redeal_request: "আবার বাঁটার অনুরোধ", low_call_sum: "মোট ডাক কম", guard: "নিরাপত্তা সীমা" },
      handOf: (n: number, of: number) => `দান ${n} / ${of}`,
      shuffling: "তাস ফেটানো হচ্ছে",
      trumpAlways: (suit: string, glyph: string) => `${suit} তুরুপ ${glyph}`,
      sir: (double: boolean, target: number) => `${double ? "ডাবল" : "সিঙ্গল"} সর · ${target} পর্যন্ত`,
      pointsAB: (a: number, b: number) => `পয়েন্ট A ${a} · B ${b}`,
      trumpIs: (suit: string) => `তুরুপ: ${suit}`,
      pile: (n: number) => `স্তূপ ${n}`,
      waitingTrump: "তুরুপ বাছার অপেক্ষা",
      pickedUpTrick: (name: string) => `${name} পিঠ তুলে নিয়েছে`,
      trickAside: "পিঠ সরিয়ে রাখা হলো",
      pts: (n: number) => `${n} পয়েন্ট`,
      timesBhabhi: (n: number) => `${n} বার ভাবি`,
    },
    say: {
      matchOver: "ম্যাচ শেষ",
      dealingFull: "তাস ফেটানো ও বাঁটা হচ্ছে",
      handOver: "দান শেষ",
      weakHand: "তাস দুর্বল? আবার বাঁটতে বলুন",
      redealOpen: "আবার বাঁটার সুযোগ খোলা",
      chooseCall: "কয়টি পিঠ জিতবেন?",
      isCalling: (name: string) => `${name} ডাকছে`,
      youNameTrump: "তুরুপ আপনি বাছুন",
      mayTake: "পরের জনের তাস নিতে পারেন",
      isPlaying: (name: string) => `${name}-এর পালা`,
      leadAceSpades: "ইস্কাপনের টেক্কা দিয়ে শুরু করুন",
      lead: "আপনার চাল: যেকোনো তাস খেলুন",
      leadShort: "যেকোনো তাস খেলুন",
      follow: (glyph: string, suit: string) => `${glyph} ${suit}ই খেলুন`,
      noSuitBreaks: (glyph: string) => `${glyph} নেই: যা খেলবেন, ঠুল্লা`,
      noSuitTrump: (glyph: string) => `${glyph} নেই: তুরুপ বা যেকোনো তাস`,
      yourTurn: (what: string) => `আপনার পালা: ${what}`,
      dealing: "তাস বাঁটা হচ্ছে",
      redealWindow: "আবার বাঁটার সুযোগ",
      waiting: "অপেক্ষা",
      breakWarn: (glyph: string, name: string, n: number) => `${glyph} নেই: যা-ই খেলুন, ${name} ${n}টি তাস তুলবে`,
      voidTag: (glyph: string) => `${glyph} নেই`,
      nobodyTook: "কেউ নেয়নি।",
      took: (name: string) => `${name} নিয়েছে।`,
      pickedUpBroken: (name: string) => `${name} তুলে নিল: ঠুল্লা পড়েছে।`,
      putAside: (name: string) => `সরিয়ে রাখা হলো। এবার ${name}-এর চাল।`,
    },
    phase: {
      over: "ম্যাচ শেষ",
      dealing: "বাঁটা",
      handOver: "দান শেষ",
      window: "আবার বাঁটার সুযোগ",
      calling: "ডাক",
      trump: "তুরুপ বাছাই",
      following: (glyph: string) => `${glyph}-এর চাল`,
      open: "খোলা চাল",
    },
    hint: {
      none: "এখন খেলার কিছু নেই",
      noneWhy: "আপনার পালায় পরামর্শ দেখা যাবে।",
      steadyLead: "এই তাস থেকে নিরাপদ শুরু।",
      follows: "রং মেলায়, বড় তাস বাঁচিয়ে।",
      trumpWins: "রং নেই, তুরুপে পিঠ জেতা যায়।",
      shed: "রং নেই; সবচেয়ে অকাজের তাসটা যায়।",
      least: "রং নেই; এতে ক্ষতি সবচেয়ে কম।",
      call: (n: number) => `ডাক ${n}`,
      callWhy: "আপনার তাসের জোর দেখে আন্দাজ।",
      trump: (glyph: string, suit: string) => `${glyph} ${suit} তুরুপ`,
      trumpWhy: "আপনার সবচেয়ে লম্বা ও জোরালো রং।",
      take: "পরের জনের তাস নিন",
      takeWhy: "সে বেরিয়ে যায়, চাল আপনার হাতে থাকে।",
      redeal: "আবার বাঁটতে বলুন",
      redealWhy: "তাস বেশ দুর্বল, আবার বাঁটান।",
    },
    rules: {
      trump: "তুরুপ",
      trumpText: (suit: string, glyph: string) => `${suit} ${glyph} সবসময় তুরুপ।`,
      calls: "ডাক",
      callsText: (min: number, max: number) => `${min} থেকে ${max} পিঠ পর্যন্ত ডাকুন।`,
      mustBeat: "পারলে পিঠ জিতুন",
      mustBeatOn: "জিততে পারলে জিততেই হবে।",
      mustBeatOff: "রঙের যেকোনো তাস খেলুন।",
      trumpIfWinning: "রং না থাকলে তুরুপ",
      trumpIfWinningOn: "রং না থাকলে জেতার তুরুপ দিতেই হবে।",
      trumpIfWinningOff: "রং না থাকলে যা খুশি খেলুন।",
      overtrick: "বাড়তি পিঠের পয়েন্ট",
      overtrickOn: "ডাকের বেশি প্রতিটি পিঠে 0.1 যোগ হয়।",
      overtrickOff: "ডাকের বেশি পিঠে কিছু যোগ হয় না।",
      redeal: "অনুরোধে আবার বাঁটা",
      redealOn: "দুর্বল তাসে আবার বাঁটতে বলা যায়।",
      redealOff: "আবার বাঁটার অনুরোধ নেই।",
      noSpade: "ইস্কাপন ছাড়া তাস",
      noSpadeOn: "একই জন নিজে থেকেই আবার বাঁটে।",
      noSpadeOff: "যেমন বাঁটা, তেমন খেলা।",
      firstLead: "প্রথম চাল",
      firstLeadNoTrump: "প্রথম চাল ইস্কাপনে নয়।",
      firstLeadAny: "যেকোনো তাসে শুরু করা যায়।",
      direction: "দিক",
      clockwise: "খেলা ঘড়ির কাঁটার দিকে চলে।",
      counter: "খেলা ঘড়ির কাঁটার উল্টো দিকে চলে।",
      length: "দৈর্ঘ্য",
      hands: (n: number) => `${n} দান।`,
      rounds: (n: number) => `${n} রাউন্ড।`,
      variant: "ধরন",
      double: "ডাবল সর: স্তূপ নিতে পরপর দুটি পিঠ জিতুন।",
      single: "সিঙ্গল সর: আগে সাত পিঠ যে দলের, দান তাদের।",
      aces: "টেক্কায় স্তূপ মেলে না",
      acesOn: "পরপর দুটি টেক্কায় স্তূপ পাওয়া যায় না।",
      acesOff: "টেক্কা অন্য তাসের মতোই গোনা হয়।",
      target: "জেতার পয়েন্ট",
      targetText: (n: number) => `আগে ${n} পর্যন্ত।`,
      handCourt: "দান ও কোট",
      handCourtText: (hand: number, court: number) => `দানে ${hand}, কোটে ${court}।`,
      nextDealer: "পরের বাঁটিয়ে",
      pagat: "হেরে যাওয়া দল পরের বার বাঁটে।",
      rotate: "প্রতি দানে বাঁটার পালা পরের আসনে।",
      thulla: "ঠুল্লায় পিঠ শেষ",
      thullaOn: "অন্য রং পড়লেই পিঠ শেষ।",
      thullaOff: "সবাই খেলার পর তাস তোলা হয়।",
      firstAside: "প্রথম পিঠ সরিয়ে রাখা",
      firstAsideOn: "ইস্কাপনের টেক্কার পিঠ সবসময় আলাদা।",
      firstAsideOff: "প্রথম পিঠও তোলা যায়।",
      lastCard: "শেষ তাস",
      empty: {
        drawFromWaste: "শেষ তাসে জিতলে স্তূপ থেকে তাস নেবেন।",
        drawFromNext: "শেষ তাসে জিতলে পরের জনের কাছ থেকে তাস নেবেন।",
        escapeIfThreePlus: "শেষ তাসে জিতলে, তিন বা বেশি জন বাকি থাকলে বেরিয়ে যাবেন।",
        passToNext: "শেষ তাসে জিতলে চাল পরের জনের কাছে যায়।",
      },
      takeHand: "তাস নেওয়া",
      takeHandOn: "পিঠের আগে আপনি পরের জনের তাস নিতে পারেন।",
      takeHandOff: "তাস নেওয়া যায় না।",
      twoLeft: "দুজন বাকি",
      twoLeftOn: "স্তূপ থেকে তোলা তাস চালা ও কাটা হয়।",
      twoLeftOff: "অন্য পিঠের মতোই খেলা হয়।",
      decks: "প্যাকেট",
      twoDecks: "দুই প্যাকেট; একই তাসে আগে খেলা তাস জেতে।",
      oneDeck: "এক প্যাকেট।",
      upTo: (rounds: number, limit: number) => `${rounds} দান, বা কেউ ${limit} বার ভাবি হওয়া পর্যন্ত।`,
      deal: "বাঁটা",
      even: "সমান বাঁটা।",
      extra: (n: number) => `আপনি ${n}টি বাড়তি তাস নিয়ে শুরু করবেন।`,
    },
    screen: {
      menu: "টেবিল মেনু",
      tracker: "কোন তাস চলে গেছে",
      undo: "শেষ তাস ফিরিয়ে নিন",
      last: "আগের পিঠ",
      hint: "পরামর্শ",
      inTrick: (list: string) => `পিঠে: ${list}`,
      trickEmpty: "পিঠে কোনো তাস নেই",
      waitingDeal: "বাঁটার অপেক্ষা",
      tableInfo: "টেবিলের তথ্য",
      leaveTitle: "এই ম্যাচ ছাড়বেন?",
      leave: "ম্যাচ ছাড়ুন",
      stay: "টেবিলে থাকুন",
      inHand: (n: number) => `হাতে ${n}`,
      seats: (n: number) => `${n}টি আসন`,
      endsTitle: "এই খেলা এখানেই শেষ",
      endsBody: "বটের খেলা থেমে থাকে না: ছাড়লে টেবিল বন্ধ।",
      droppedTitle: "চলতি দান বাদ যাবে",
      droppedBody: "ফল লেখা হবে না, চলতি স্কোরও যাবে।",
      idleTitle: "কিছু চলছে না",
      idleBody: "ছাড়লে কিছুই হারাবেন না।",
    },
    controls: {
      chooseCall: "আপনার ডাক বেছে নিন",
      makeCall: "আপনার ডাক দিন",
      suggested: (what: string) => `পরামর্শ: ${what}`,
      callN: (n: number, suggested: boolean) => `ডাক ${n}${suggested ? ", পরামর্শ" : ""}`,
      suitSuggested: (suit: string, suggested: boolean) => `${suit}${suggested ? ", পরামর্শ" : ""}`,
      redealRequested: "অনুরোধ হয়েছে। অপেক্ষা করুন…",
      redealOpen: "আবার বাঁটার সুযোগ খোলা",
      requestRedeal: "আবার বাঁটতে বলুন",
      chooseTrump: "তুরুপ বাছুন",
      takeLine: "পরের জনের তাস নেবেন? সে বেরিয়ে যাবে।",
      takeSpoken: "পরের জনের তাস নিন",
      takeCards: "তাস নিন",
    },
    seatUi: {
      bot: "বট",
      auto: "অটো-খেলা",
      offline: "অফলাইন",
      theirTurn: "তার পালা",
      yourTurn: "আপনার পালা",
      inHand: (n: number) => `হাতে ${n}টি তাস`,
      timeLeft: (s: number) => `বাকি সময়: ${s} সেকেন্ড`,
      hand: (n: number) => `আপনার তাস, ${n}টি`,
      faceDown: "উল্টানো তাস",
      tapAgain: "খেলতে আবার ট্যাপ করুন",
      tapToRaise: "তুলতে ট্যাপ, খেলতে আবার ট্যাপ",
    },
    sheets: {
      done: "হয়ে গেছে",
      close: "বন্ধ করুন",
      backToGame: "খেলায় ফিরুন",
      arrange: "তাস সাজান",
      layout: "বিন্যাস",
      fan: "পাখা",
      spread: "ছড়ানো",
      spreadHint: "প্রতিটি তাস পুরো, সারিতে।",
      fanHint: "চেনা ভঙ্গি; খেলার তাস উঁচু।",
      order: "ক্রম",
      bySuit: "রং ধরে",
      byRank: "বড় থেকে ছোট",
      rankHint: "বড়টা আগে, যে রঙেরই হোক।",
      suitHint: "রং ধরে, লাল-কালো পালাক্রমে।",
      suggestion: "একটি পরামর্শ",
      hintNote: "পরামর্শ শুধু আপনার দেখা টেবিলই দেখে, কারও তাস নয়।",
      lastTrick: "আগের পিঠ",
      houseRules: "খেলার নিয়ম",
      rulesFixed: "এই ম্যাচের নিয়ম বাঁধা। বদলাতে নতুন টেবিল খুলুন।",
      on: "চালু",
      off: "বন্ধ",
      table: "টেবিল",
      leaveMatch: "এই ম্যাচ ছাড়ুন",
      rulesCaption: "এই টেবিলে কী খেলা হয়",
      arrangeCaption: "পাখা বা ছড়ানো, রং ধরে বা বড় থেকে ছোট",
      tracker: "কোন তাস চলে গেছে",
      trackerCaption: "এই দানে খেলা তাস",
      lastCaption: "কে কী খেলেছে",
      tableInfo: "টেবিলের তথ্য",
      infoCaption: "খেলা, নিয়ম ও বট",
      hints: "পরামর্শ",
      hintsHint: "পালায় পরামর্শের বোতাম",
      timer: "পালার টাইমার",
      timerHint: "দাগ ফুরোলে আপনার হয়ে তাস খেলা হবে",
      trackerNote: "কাটা তাস এই দানে খেলা হয়ে গেছে, সোনালিগুলো আপনার। হাতে ফেরা তাসের দাগ উঠে যায়।",
      played: "খেলা হয়েছে",
      mine: "আপনার হাতে",
      out: "এখনও বাইরে",
    },
  },
});
