import { localized } from "../../i18n";

export const T = localized("onboarding", {
  en: {
    tagline: "Subcontinent card games at one table. Real rules, fair deals.",
    start: "Start playing",
    continueAs: (n: string) => `Continue as ${n}`,
    privacy: "No sign-up. Everything stays on this phone.",
    langTitle: "Language",
    langNote: "Each language in its own script. Change it anytime in Settings.",
    selected: "Selected",
    cont: "Continue",
    yearTitle: "Birth year",
    yearBody: "What year were you born? It never leaves this phone.",
    pickYear: "Pick your birth year",
    pickHint: "Tap a year, or jump by 1 or 10.",
    noYear: "Birth year not chosen",
    yearLabel: (y: number) => `Birth year ${y}`,
    protect: "Skip this and TashZone uses Protected Mode: no typed chat, and online rooms stay off until a parent turns them on.",
    bornIn: (y: number) => `I was born in ${y}`,
    skip: "Skip for now",
    modeTitle: "How do you like to play?",
    easyT: "Easy", easyB: "Bigger cards and text, a four-colour deck, a Hint button, no turn timer, slower dealing.",
    stdT: "Standard", stdB: "Regular cards, a 14-second turn timer, hints off.",
    chosen: "Chosen",
    modeNote: "Nothing is permanent. Every switch here is also in Settings.",
    nameTitle: "Your table name",
    nameLabel: "Your name", namePh: "Type a name", suggest: "Suggest another", clear: "Clear",
    pickAvatar: "Pick an avatar",
    nameNote: "Any name you like. Avatars are drawings, never photos.",
    avatars: ["Lantern", "Kite", "Peacock", "Tabla", "Moon", "Parrot", "Truck", "Teapot"],
    nicks: ["Calm Sparrow", "Quiet Falcon", "Steady Heron", "Bright Koel", "Patient Crane", "Swift Bulbul", "Clever Myna", "Warm Lantern", "Still River", "Night Jasmine"],
  } as const,
  ur: {
    tagline: "برصغیر کے تاش کے کھیل، ایک میز پر۔ اصل قوانین، منصفانہ بانٹ۔",
    start: "کھیل شروع کریں",
    continueAs: (n: string) => `بطور ${n} جاری رکھیں`,
    privacy: "سائن اپ کی ضرورت نہیں۔ سب کچھ اسی فون پر رہتا ہے۔",
    langTitle: "زبان",
    langNote: "ہر زبان اپنے رسم الخط میں۔ بعد میں ترتیبات سے بدل سکتے ہیں۔",
    selected: "منتخب",
    cont: "جاری رکھیں",
    yearTitle: "سالِ پیدائش",
    yearBody: "آپ کس سال پیدا ہوئے؟ یہ اس فون سے باہر نہیں جاتا۔",
    pickYear: "سالِ پیدائش چنیں",
    pickHint: "سال پر ٹیپ کریں، یا 1 یا 10 سال آگے پیچھے جائیں۔",
    noYear: "سالِ پیدائش نہیں چنا گیا",
    yearLabel: (y: number) => `سالِ پیدائش ${y}`,
    protect: "اسے چھوڑیں تو TashZone محفوظ موڈ میں چلے گا: لکھ کر چیٹ بند، اور آن لائن روم تب تک بند جب تک والدین آن نہ کریں۔",
    bornIn: (y: number) => `میری پیدائش ${y} کی ہے`,
    skip: "ابھی چھوڑیں",
    modeTitle: "آپ کیسے کھیلنا چاہیں گے؟",
    easyT: "آسان", easyB: "بڑے پتے اور حروف، چار رنگوں والی گڈی، مشورے کا بٹن، ٹائمر نہیں، آہستہ بانٹ۔",
    stdT: "معیاری", stdB: "عام پتے، باری کا 14 سیکنڈ ٹائمر، مشورے بند۔",
    chosen: "منتخب",
    modeNote: "کچھ بھی مستقل نہیں۔ یہ سب سوئچ ترتیبات میں بھی ہیں۔",
    nameTitle: "میز پر آپ کا نام",
    nameLabel: "آپ کا نام", namePh: "نام لکھیں", suggest: "کوئی اور نام", clear: "صاف کریں",
    pickAvatar: "اوتار چنیں",
    nameNote: "جو نام چاہیں رکھیں۔ اوتار خاکے ہیں، تصویریں نہیں۔",
    avatars: ["لالٹین", "پتنگ", "مور", "طبلہ", "چاند", "طوطا", "ٹرک", "چائے دانی"],
    nicks: ["پُرسکون چڑیا", "خاموش شاہین", "ثابت قدم بگلا", "چمکتی کوئل", "صابر کونج", "تیز بلبل", "چالاک مینا", "روشن لالٹین", "ٹھہرا دریا", "رات کی رانی"],
  },
  hi: {
    tagline: "उपमहाद्वीप के ताश के खेल, एक टेबल पर। असली नियम, निष्पक्ष बँटाई।",
    start: "खेलना शुरू करें",
    continueAs: (n: string) => `${n} के रूप में जारी रखें`,
    privacy: "साइन-अप की ज़रूरत नहीं। सब कुछ इसी फ़ोन पर रहता है।",
    langTitle: "भाषा",
    langNote: "हर भाषा अपनी लिपि में। बाद में सेटिंग्स में बदल सकते हैं।",
    selected: "चुनी गई",
    cont: "जारी रखें",
    yearTitle: "जन्म का साल",
    yearBody: "आप किस साल पैदा हुए? यह जानकारी इस फ़ोन से बाहर नहीं जाती।",
    pickYear: "जन्म का साल चुनें",
    pickHint: "साल पर टैप करें, या 1 या 10 साल आगे-पीछे जाएँ।",
    noYear: "जन्म का साल नहीं चुना",
    yearLabel: (y: number) => `जन्म का साल ${y}`,
    protect: "इसे छोड़ने पर TashZone सुरक्षित मोड में चलेगा: लिखकर चैट बंद, और ऑनलाइन रूम तब तक बंद जब तक माता-पिता चालू न करें।",
    bornIn: (y: number) => `मेरा जन्म ${y} में हुआ`,
    skip: "अभी छोड़ें",
    modeTitle: "आप कैसे खेलना चाहेंगे?",
    easyT: "आसान", easyB: "बड़े पत्ते और अक्षर, चार रंगों वाली गड्डी, सुझाव बटन, टाइमर नहीं, धीमी बँटाई।",
    stdT: "सामान्य", stdB: "आम पत्ते, बारी का 14 सेकंड टाइमर, सुझाव बंद।",
    chosen: "चुना गया",
    modeNote: "कुछ भी पक्का नहीं। ये सारे स्विच सेटिंग्स में भी हैं।",
    nameTitle: "टेबल पर आपका नाम",
    nameLabel: "आपका नाम", namePh: "नाम लिखें", suggest: "कोई और नाम", clear: "साफ़ करें",
    pickAvatar: "अवतार चुनें",
    nameNote: "जो नाम चाहें रखें। अवतार चित्र हैं, कभी फ़ोटो नहीं।",
    avatars: ["लालटेन", "पतंग", "मोर", "तबला", "चाँद", "तोता", "ट्रक", "केतली"],
    nicks: ["शांत गौरैया", "मौन बाज़", "अटल बगुला", "चमकती कोयल", "धीर सारस", "फुर्तीली बुलबुल", "चतुर मैना", "रोशन लालटेन", "ठहरी नदी", "रात की रानी"],
  },
  ne: {
    tagline: "उपमहाद्वीपका तास खेल, एउटै टेबलमा। साँचो नियम, इमानदार बाँडाइ।",
    start: "खेल्न सुरु गर्नुहोस्",
    continueAs: (n: string) => `${n}का रूपमा जारी राख्नुहोस्`,
    privacy: "साइन-अप चाहिँदैन। सबै कुरा यही फोनमा रहन्छ।",
    langTitle: "भाषा",
    langNote: "हरेक भाषा आफ्नै लिपिमा। पछि सेटिङमा बदल्न सकिन्छ।",
    selected: "छानिएको",
    cont: "जारी राख्नुहोस्",
    yearTitle: "जन्म वर्ष",
    yearBody: "तपाईं कुन वर्ष जन्मनुभएको हो? यो यही फोनमा रहन्छ, कतै पठाइँदैन।",
    pickYear: "जन्म वर्ष छान्नुहोस्",
    pickHint: "वर्षमा ट्याप गर्नुहोस्, वा 1 वा 10 वर्ष अघि-पछि जानुहोस्।",
    noYear: "जन्म वर्ष छानिएको छैन",
    yearLabel: (y: number) => `जन्म वर्ष ${y}`,
    protect: "यो छोड्नुभयो भने TashZone सुरक्षित मोडमा चल्छ: लेखेर च्याट बन्द, र अभिभावकले नखोलेसम्म अनलाइन रुम बन्द।",
    bornIn: (y: number) => `मेरो जन्म ${y} मा भएको हो`,
    skip: "अहिलेलाई छोड्नुहोस्",
    modeTitle: "तपाईं कसरी खेल्न चाहनुहुन्छ?",
    easyT: "सजिलो", easyB: "ठूला पत्ती र अक्षर, चार रङको गड्डी, सुझाव बटन, टाइमर छैन, बिस्तारै बाँडाइ।",
    stdT: "सामान्य", stdB: "सामान्य पत्ती, पालोको 14 सेकेन्ड टाइमर, सुझाव बन्द।",
    chosen: "छानियो",
    modeNote: "केही पनि स्थायी छैन। यी सबै स्विच सेटिङमा पनि छन्।",
    nameTitle: "टेबलमा तपाईंको नाम",
    nameLabel: "तपाईंको नाम", namePh: "नाम लेख्नुहोस्", suggest: "अर्को नाम", clear: "मेटाउनुहोस्",
    pickAvatar: "अवतार छान्नुहोस्",
    nameNote: "मन पर्ने जुनसुकै नाम। अवतार चित्र हुन्, फोटो होइनन्।",
    avatars: ["लालटिन", "चङ्गा", "मयूर", "तबला", "जून", "सुगा", "ट्रक", "केतली"],
    nicks: ["शान्त भँगेरा", "मौन बाज", "अडिग बकुल्ला", "चम्किलो कोइली", "धैर्यवान सारस", "फुर्तिलो जुरेली", "चलाख डाँफे", "न्यानो लालटिन", "निर्मल खोला", "रातकी रानी"],
  },
  bn: {
    tagline: "উপমহাদেশের তাসের খেলা, এক টেবিলে। আসল নিয়ম, ন্যায্য বাঁটা।",
    start: "খেলা শুরু করুন",
    continueAs: (n: string) => `${n} হিসেবে চালিয়ে যান`,
    privacy: "সাইন-আপ লাগবে না। সবকিছু এই ফোনেই থাকে।",
    langTitle: "ভাষা",
    langNote: "প্রতিটি ভাষা নিজের লিপিতে। পরে সেটিংসে বদলাতে পারবেন।",
    selected: "নির্বাচিত",
    cont: "চালিয়ে যান",
    yearTitle: "জন্মসাল",
    yearBody: "আপনি কোন সালে জন্মেছেন? এটি এই ফোনের বাইরে যায় না।",
    pickYear: "জন্মসাল বেছে নিন",
    pickHint: "একটি সালে ট্যাপ করুন, বা 1 বা 10 বছর করে সরুন।",
    noYear: "জন্মসাল বাছা হয়নি",
    yearLabel: (y: number) => `জন্মসাল ${y}`,
    protect: "এটি বাদ দিলে TashZone সুরক্ষিত মোডে চলবে: লিখে চ্যাট বন্ধ, আর অভিভাবক চালু না করা পর্যন্ত অনলাইন রুম বন্ধ।",
    bornIn: (y: number) => `আমার জন্ম ${y} সালে`,
    skip: "এখন থাক",
    modeTitle: "কীভাবে খেলতে চান?",
    easyT: "সহজ", easyB: "বড় তাস ও লেখা, চার রঙের তাস, পরামর্শ বোতাম, টাইমার নেই, ধীরে বাঁটা।",
    stdT: "সাধারণ", stdB: "সাধারণ তাস, প্রতি পালায় 14 সেকেন্ডের টাইমার, পরামর্শ বন্ধ।",
    chosen: "নির্বাচিত",
    modeNote: "কিছুই স্থায়ী নয়। এখানকার সব সুইচ সেটিংসেও আছে।",
    nameTitle: "টেবিলে আপনার নাম",
    nameLabel: "আপনার নাম", namePh: "নাম লিখুন", suggest: "অন্য নাম", clear: "মুছুন",
    pickAvatar: "অবতার বেছে নিন",
    nameNote: "যে নাম খুশি। অবতারগুলো আঁকা, ছবি নয়।",
    avatars: ["লণ্ঠন", "ঘুড়ি", "ময়ূর", "তবলা", "চাঁদ", "টিয়া", "ট্রাক", "কেটলি"],
    nicks: ["শান্ত চড়ুই", "নীরব বাজ", "অটল বক", "উজ্জ্বল কোকিল", "ধৈর্যশীল সারস", "চটপটে বুলবুলি", "চালাক ময়না", "উষ্ণ লণ্ঠন", "স্থির নদী", "রাতের হাসনাহেনা"],
  },
});

export const LANGS = [
  { k: "en", native: "English", en: "English" }, { k: "ur", native: "اردو", en: "Urdu" }, { k: "hi", native: "हिन्दी", en: "Hindi" },
  { k: "ne", native: "नेपाली", en: "Nepali" }, { k: "bn", native: "বাংলা", en: "Bengali" },
] as const;

export const nick = () => T.nicks[Math.floor(Math.random() * T.nicks.length)]!;
export const MIN_YEAR = 1930;
export const clampYear = (y: number, now = new Date().getFullYear()) => Math.max(MIN_YEAR, Math.min(now, y));
export const isProtectedForBirth = (born: number, now = new Date().getFullYear()) => now - born < 13;
