import { localized } from "../../i18n";

export const T = localized("onboarding", {
  en: {
    tagline: "Card games from the subcontinent, on one table. Real rules, fair deals.",
    start: "Start playing",
    continueAs: (n: string) => `Continue as ${n}`,
    privacy: "No sign-up. Everything stays on this phone.",
    langTitle: "Language",
    langNote: "Each language is shown in its own script. You can change this later in Settings.",
    selected: "Selected",
    cont: "Continue",
    yearTitle: "Birth year",
    yearBody: "What year were you born? This stays on your phone and is never sent anywhere.",
    pickYear: "Pick your birth year",
    pickHint: "Tap a year, or jump by 1 or 10 years.",
    noYear: "Birth year, not chosen",
    yearLabel: (y: number) => `Birth year ${y}`,
    protect: "Skip this and TashZone uses Protected Mode: no typing to other players, and online rooms stay off until a parent turns them on.",
    bornIn: (y: number) => `I was born in ${y}`,
    skip: "Skip for now",
    modeTitle: "How do you like to play?",
    easyT: "Easy", easyB: "Bigger cards and letters, four colours for the suits, a Hint button, no turn clock, slower dealing.",
    stdT: "Standard", stdB: "Regular cards, a 14-second turn clock, hints off. Any of this can change later in Settings.",
    chosen: "Chosen",
    modeNote: "Nothing here is permanent. Settings holds every switch on this screen.",
    nameTitle: "Your table name",
    nameLabel: "Your name", namePh: "Type a name", suggest: "Suggest another", clear: "Clear",
    pickAvatar: "Pick an avatar",
    nameNote: "Any name you like. Avatars are drawn, never photographs.",
    avatars: ["Lantern", "Kite", "Peacock", "Tabla", "Moon", "Parrot", "Truck", "Teapot"],
    nicks: ["Calm Sparrow", "Quiet Falcon", "Steady Heron", "Bright Koel", "Patient Crane", "Swift Bulbul", "Clever Myna", "Warm Lantern", "Still River", "Night Jasmine"],
  } as const,
  ur: {
    tagline: "برصغیر کے تاش کے کھیل، ایک ہی میز پر۔ اصل قوانین، ایمانداری سے بانٹ۔",
    start: "کھیلنا شروع کریں",
    continueAs: (n: string) => `${n} کے طور پر جاری رکھیں`,
    privacy: "کوئی سائن اپ نہیں۔ سب کچھ اسی فون پر رہتا ہے۔",
    langTitle: "زبان",
    langNote: "ہر زبان اپنے رسم الخط میں دکھائی گئی ہے۔ آپ اسے بعد میں ترتیبات میں بدل سکتے ہیں۔",
    selected: "منتخب",
    cont: "آگے بڑھیں",
    yearTitle: "سالِ پیدائش",
    yearBody: "آپ کس سال پیدا ہوئے؟ یہ آپ کے فون پر ہی رہتا ہے اور کہیں نہیں بھیجا جاتا۔",
    pickYear: "اپنا سالِ پیدائش چنیں",
    pickHint: "کسی سال پر ٹیپ کریں، یا 1 یا 10 سال آگے پیچھے جائیں۔",
    noYear: "سالِ پیدائش، ابھی نہیں چنا",
    yearLabel: (y: number) => `سالِ پیدائش ${y}`,
    protect: "اسے چھوڑ دیں تو TashZone محفوظ موڈ استعمال کرے گا: دوسرے کھلاڑیوں کو لکھ کر پیغام نہیں، اور آن لائن کمرے تب تک بند رہیں گے جب تک والدین انہیں نہ کھولیں۔",
    bornIn: (y: number) => `میری پیدائش ${y} میں ہوئی`,
    skip: "ابھی چھوڑ دیں",
    modeTitle: "آپ کیسے کھیلنا پسند کرتے ہیں؟",
    easyT: "آسان", easyB: "بڑے پتے اور حروف، چاروں رنگوں کے الگ الگ رنگ، اشارے کا بٹن، باری کی گھڑی نہیں، آہستہ بانٹنا۔",
    stdT: "معیاری", stdB: "عام پتے، باری کے لیے 14 سیکنڈ کی گھڑی، اشارے بند۔ یہ سب بعد میں ترتیبات میں بدل سکتے ہیں۔",
    chosen: "منتخب",
    modeNote: "یہاں کچھ بھی مستقل نہیں۔ اس اسکرین کا ہر سوئچ ترتیبات میں موجود ہے۔",
    nameTitle: "میز پر آپ کا نام",
    nameLabel: "آپ کا نام", namePh: "نام لکھیں", suggest: "کوئی اور نام", clear: "مٹائیں",
    pickAvatar: "اوتار چنیں",
    nameNote: "جو نام چاہیں رکھیں۔ اوتار ہاتھ سے بنے ہیں، تصویریں کبھی نہیں۔",
    avatars: ["لالٹین", "پتنگ", "مور", "طبلہ", "چاند", "طوطا", "ٹرک", "چائے دانی"],
    nicks: ["پُرسکون چڑیا", "خاموش شاہین", "ثابت قدم بگلا", "چمکتی کوئل", "صابر کونج", "تیز بلبل", "چالاک مینا", "روشن لالٹین", "ٹھہرا دریا", "رات کی رانی"],
  },
  hi: {
    tagline: "उपमहाद्वीप के ताश के खेल, एक ही मेज़ पर। असली नियम, ईमानदार बँटवारा।",
    start: "खेलना शुरू करें",
    continueAs: (n: string) => `${n} के रूप में जारी रखें`,
    privacy: "कोई साइन-अप नहीं। सब कुछ इसी फ़ोन पर रहता है।",
    langTitle: "भाषा",
    langNote: "हर भाषा अपनी लिपि में दिखाई गई है। आप इसे बाद में सेटिंग्स में बदल सकते हैं।",
    selected: "चुनी गई",
    cont: "आगे बढ़ें",
    yearTitle: "जन्म का साल",
    yearBody: "आप किस साल पैदा हुए? यह आपके फ़ोन पर ही रहता है और कहीं नहीं भेजा जाता।",
    pickYear: "अपना जन्म का साल चुनें",
    pickHint: "किसी साल पर टैप करें, या 1 या 10 साल आगे-पीछे जाएँ।",
    noYear: "जन्म का साल, अभी नहीं चुना",
    yearLabel: (y: number) => `जन्म का साल ${y}`,
    protect: "इसे छोड़ने पर TashZone सुरक्षित मोड चलाएगा: दूसरे खिलाड़ियों को लिखकर संदेश नहीं, और ऑनलाइन कमरे तब तक बंद रहेंगे जब तक माता-पिता उन्हें चालू न करें।",
    bornIn: (y: number) => `मेरा जन्म ${y} में हुआ`,
    skip: "अभी छोड़ें",
    modeTitle: "आप कैसे खेलना पसंद करते हैं?",
    easyT: "आसान", easyB: "बड़े पत्ते और अक्षर, हर रंग के लिए अलग रंग, संकेत बटन, चाल की घड़ी नहीं, धीमा बँटवारा।",
    stdT: "सामान्य", stdB: "सामान्य पत्ते, हर चाल के लिए 14 सेकंड की घड़ी, संकेत बंद। यह सब बाद में सेटिंग्स में बदल सकते हैं।",
    chosen: "चुना गया",
    modeNote: "यहाँ कुछ भी पक्का नहीं है। इस स्क्रीन का हर स्विच सेटिंग्स में है।",
    nameTitle: "मेज़ पर आपका नाम",
    nameLabel: "आपका नाम", namePh: "नाम लिखें", suggest: "कोई और नाम", clear: "मिटाएँ",
    pickAvatar: "अवतार चुनें",
    nameNote: "जो नाम चाहें रखें। अवतार हाथ से बने हैं, कभी फ़ोटो नहीं।",
    avatars: ["लालटेन", "पतंग", "मोर", "तबला", "चाँद", "तोता", "ट्रक", "केतली"],
    nicks: ["शांत गौरैया", "चुप बाज़", "अटल बगुला", "चमकती कोयल", "धीरज सारस", "फुर्तीली बुलबुल", "चतुर मैना", "रोशन लालटेन", "ठहरी नदी", "रात की रानी"],
  },
  ne: {
    tagline: "उपमहाद्वीपका तासका खेलहरू, एउटै टेबलमा। साँचो नियम, इमानदार बाँडफाँड।",
    start: "खेल्न सुरु गर्नुहोस्",
    continueAs: (n: string) => `${n} का रूपमा जारी राख्नुहोस्`,
    privacy: "साइन-अप चाहिँदैन। सबै कुरा यही फोनमा रहन्छ।",
    langTitle: "भाषा",
    langNote: "हरेक भाषा आफ्नै लिपिमा देखाइएको छ। तपाईं यसलाई पछि सेटिङमा बदल्न सक्नुहुन्छ।",
    selected: "छानिएको",
    cont: "अगाडि बढ्नुहोस्",
    yearTitle: "जन्म वर्ष",
    yearBody: "तपाईं कुन वर्ष जन्मनुभयो? यो तपाईंको फोनमै रहन्छ र कतै पठाइँदैन।",
    pickYear: "आफ्नो जन्म वर्ष छान्नुहोस्",
    pickHint: "कुनै वर्षमा ट्याप गर्नुहोस्, वा 1 वा 10 वर्ष अगाडि-पछाडि जानुहोस्।",
    noYear: "जन्म वर्ष, छानिएको छैन",
    yearLabel: (y: number) => `जन्म वर्ष ${y}`,
    protect: "यो छोड्नुभयो भने TashZone ले सुरक्षित मोड चलाउँछ: अरू खेलाडीलाई लेखेर सन्देश पठाउन मिल्दैन, र अभिभावकले नखोलेसम्म अनलाइन कोठाहरू बन्द रहन्छन्।",
    bornIn: (y: number) => `मेरो जन्म ${y} मा भएको हो`,
    skip: "अहिलेलाई छोड्नुहोस्",
    modeTitle: "तपाईं कसरी खेल्न रुचाउनुहुन्छ?",
    easyT: "सजिलो", easyB: "ठूला पत्ती र अक्षर, हरेक रङको छुट्टै रङ, सङ्केत बटन, पालोको घडी छैन, बिस्तारै बाँड्ने।",
    stdT: "सामान्य", stdB: "सामान्य पत्ती, पालोका लागि 14 सेकेन्डको घडी, सङ्केत बन्द। यी सबै पछि सेटिङमा बदल्न सकिन्छ।",
    chosen: "छानियो",
    modeNote: "यहाँ केही पनि स्थायी छैन। यो स्क्रिनका सबै स्विच सेटिङमा छन्।",
    nameTitle: "टेबलमा तपाईंको नाम",
    nameLabel: "तपाईंको नाम", namePh: "नाम लेख्नुहोस्", suggest: "अर्को नाम", clear: "मेटाउनुहोस्",
    pickAvatar: "अवतार छान्नुहोस्",
    nameNote: "मन पर्ने जुनसुकै नाम। अवतारहरू हातले कोरिएका हुन्, फोटो होइनन्।",
    avatars: ["लालटिन", "चङ्गा", "मयूर", "तबला", "जून", "सुगा", "ट्रक", "केतली"],
    nicks: ["शान्त भँगेरा", "मौन बाज", "अडिग बकुल्ला", "चम्किलो कोइली", "धैर्यवान सारस", "फुर्तिलो जुरेली", "चलाख डाँफे", "न्यानो लालटिन", "निर्मल खोला", "रातकी रानी"],
  },
  bn: {
    tagline: "উপমহাদেশের তাসের খেলা, এক টেবিলে। আসল নিয়ম, ন্যায্য বাঁটা।",
    start: "খেলা শুরু করুন",
    continueAs: (n: string) => `${n} হিসেবে চালিয়ে যান`,
    privacy: "সাইন-আপ লাগবে না। সবকিছু এই ফোনেই থাকে।",
    langTitle: "ভাষা",
    langNote: "প্রতিটি ভাষা তার নিজের লিপিতে দেখানো হয়েছে। পরে সেটিংসে এটি বদলাতে পারবেন।",
    selected: "বেছে নেওয়া",
    cont: "এগিয়ে যান",
    yearTitle: "জন্মসাল",
    yearBody: "আপনি কোন সালে জন্মেছেন? এটি আপনার ফোনেই থাকে, কোথাও পাঠানো হয় না।",
    pickYear: "আপনার জন্মসাল বেছে নিন",
    pickHint: "একটি সালে ট্যাপ করুন, অথবা 1 বা 10 বছর করে এগোন-পিছোন।",
    noYear: "জন্মসাল, বেছে নেওয়া হয়নি",
    yearLabel: (y: number) => `জন্মসাল ${y}`,
    protect: "এটি বাদ দিলে TashZone সুরক্ষিত মোড চালু রাখবে: অন্য খেলোয়াড়দের লিখে বার্তা পাঠানো যাবে না, আর অভিভাবক চালু না করা পর্যন্ত অনলাইন রুম বন্ধ থাকবে।",
    bornIn: (y: number) => `আমার জন্ম ${y} সালে`,
    skip: "এখন থাক",
    modeTitle: "আপনি কীভাবে খেলতে পছন্দ করেন?",
    easyT: "সহজ", easyB: "বড় তাস ও অক্ষর, প্রতিটি রঙের আলাদা রং, ইঙ্গিত বোতাম, চালের ঘড়ি নেই, ধীরে বাঁটা।",
    stdT: "সাধারণ", stdB: "সাধারণ তাস, প্রতি চালে 14 সেকেন্ডের ঘড়ি, ইঙ্গিত বন্ধ। এসব পরে সেটিংসে বদলানো যায়।",
    chosen: "বেছে নেওয়া",
    modeNote: "এখানে কিছুই স্থায়ী নয়। এই স্ক্রিনের প্রতিটি সুইচ সেটিংসে আছে।",
    nameTitle: "টেবিলে আপনার নাম",
    nameLabel: "আপনার নাম", namePh: "একটি নাম লিখুন", suggest: "অন্য নাম", clear: "মুছুন",
    pickAvatar: "একটি অবতার বেছে নিন",
    nameNote: "যে নাম খুশি। অবতারগুলো আঁকা, কখনো ছবি নয়।",
    avatars: ["লণ্ঠন", "ঘুড়ি", "ময়ূর", "তবলা", "চাঁদ", "টিয়া", "ট্রাক", "কেটলি"],
    nicks: ["শান্ত চড়ুই", "নীরব বাজ", "অটল বক", "উজ্জ্বল কোকিল", "ধৈর্যশীল সারস", "চটপটে বুলবুলি", "চালাক ময়না", "উষ্ণ লণ্ঠন", "স্থির নদী", "রাতের হাসনাহেনা"],
  },
});

export const LANGS = [
  { k: "en", native: "English", en: "English" }, { k: "ur", native: "اردو", en: "Urdu" }, { k: "hi", native: "हिन्दी", en: "Hindi" },
  { k: "ne", native: "नेपाली", en: "Nepali" }, { k: "bn", native: "বাংলা", en: "Bengali" },
] as const;

export const nick = () => T.nicks[Math.floor(Math.random() * T.nicks.length)]!;
export const MIN_YEAR = 1930;
export const clampYear = (y: number, now = new Date().getFullYear()) => Math.max(MIN_YEAR, Math.min(now, y));
export const isProtectedForBirth = (born: number, now = new Date().getFullYear()) => now - born < 13;
