import { localized } from "../../i18n";

export const U = localized("ui", {
  en: {
    back: "Back",
    close: "Close",
    del: "Delete",
    code: "Code",
    digits: (label: string, n: number, of: number) => `${label}, ${n} of ${of} digits entered`,
    step: (n: number, title: string, body: string) => `Step ${n}. ${title}. ${body}`,
    stepOf: (at: number, n: number) => `Step ${at} of ${n}`,
    tabs: { index: "Play", games: "Games", me: "You", settings: "Settings" },
    crashTitle: (where?: string) => `Something went wrong${where ? ` in ${where}` : ""}.`,
    crashBody: "Your profile and settings are safe. Try again, and if it keeps happening, restart the app.",
    tryAgain: "Try again",
    storageTitle: "Your progress can't be saved right now",
    storageBody: "Changes work until you close the app. Free up some space on your phone, then reopen TashZone.",
    ok: "OK",
    play: "Play",
  },
  ur: {
    back: "واپس",
    close: "بند کریں",
    del: "مٹائیں",
    code: "کوڈ",
    digits: (label: string, n: number, of: number) => `${label}، ${of} میں سے ${n} ہندسے درج`,
    step: (n: number, title: string, body: string) => `مرحلہ ${n}۔ ${title}۔ ${body}`,
    stepOf: (at: number, n: number) => `مرحلہ ${at} از ${n}`,
    tabs: { index: "کھیلیں", games: "کھیل", me: "آپ", settings: "ترتیبات" },
    crashTitle: (where?: string) => `${where ? `${where} میں ` : ""}کچھ غلط ہو گیا۔`,
    crashBody: "آپ کی پروفائل اور ترتیبات محفوظ ہیں۔ دوبارہ کوشش کریں، اور اگر یہ بار بار ہو تو ایپ دوبارہ کھولیں۔",
    tryAgain: "دوبارہ کوشش کریں",
    storageTitle: "آپ کی پیش رفت ابھی محفوظ نہیں ہو سکتی",
    storageBody: "ایپ بند کرنے تک تبدیلیاں کام کریں گی۔ فون میں کچھ جگہ خالی کریں، پھر TashZone دوبارہ کھولیں۔",
    ok: "ٹھیک ہے",
    play: "کھیلیں",
  },
  hi: {
    back: "वापस",
    close: "बंद करें",
    del: "मिटाएँ",
    code: "कोड",
    digits: (label: string, n: number, of: number) => `${label}, ${of} में से ${n} अंक डाले गए`,
    step: (n: number, title: string, body: string) => `चरण ${n}. ${title}. ${body}`,
    stepOf: (at: number, n: number) => `चरण ${at} / ${n}`,
    tabs: { index: "खेलें", games: "खेल", me: "आप", settings: "सेटिंग्स" },
    crashTitle: (where?: string) => `${where ? `${where} में ` : ""}कुछ गड़बड़ हो गई।`,
    crashBody: "आपकी प्रोफ़ाइल और सेटिंग्स सुरक्षित हैं। फिर से कोशिश करें, और अगर यह बार-बार हो तो ऐप दोबारा खोलें।",
    tryAgain: "फिर से कोशिश करें",
    storageTitle: "आपकी प्रगति अभी सहेजी नहीं जा सकती",
    storageBody: "ऐप बंद करने तक बदलाव काम करेंगे। फ़ोन में थोड़ी जगह खाली करें, फिर TashZone दोबारा खोलें।",
    ok: "ठीक है",
    play: "खेलें",
  },
  ne: {
    back: "फर्कनुहोस्",
    close: "बन्द गर्नुहोस्",
    del: "मेटाउनुहोस्",
    code: "कोड",
    digits: (label: string, n: number, of: number) => `${label}, ${of} मध्ये ${n} अङ्क हालियो`,
    step: (n: number, title: string, body: string) => `चरण ${n}. ${title}. ${body}`,
    stepOf: (at: number, n: number) => `चरण ${at} / ${n}`,
    tabs: { index: "खेल्नुहोस्", games: "खेलहरू", me: "तपाईं", settings: "सेटिङ" },
    crashTitle: (where?: string) => `${where ? `${where} मा ` : ""}केही गडबड भयो।`,
    crashBody: "तपाईंको प्रोफाइल र सेटिङ सुरक्षित छन्। फेरि प्रयास गर्नुहोस्, र यस्तो भइरहेमा एप फेरि खोल्नुहोस्।",
    tryAgain: "फेरि प्रयास गर्नुहोस्",
    storageTitle: "तपाईंको प्रगति अहिले सुरक्षित गर्न सकिँदैन",
    storageBody: "एप बन्द नगरेसम्म परिवर्तनहरू चल्छन्। फोनमा केही ठाउँ खाली गर्नुहोस्, अनि TashZone फेरि खोल्नुहोस्।",
    ok: "ठिक छ",
    play: "खेल्नुहोस्",
  },
  bn: {
    back: "ফিরে যান",
    close: "বন্ধ করুন",
    del: "মুছুন",
    code: "কোড",
    digits: (label: string, n: number, of: number) => `${label}, ${of}টির মধ্যে ${n}টি সংখ্যা দেওয়া হয়েছে`,
    step: (n: number, title: string, body: string) => `ধাপ ${n}. ${title}. ${body}`,
    stepOf: (at: number, n: number) => `ধাপ ${at} / ${n}`,
    tabs: { index: "খেলুন", games: "খেলা", me: "আপনি", settings: "সেটিংস" },
    crashTitle: (where?: string) => `${where ? `${where}-এ ` : ""}কিছু একটা ভুল হয়েছে।`,
    crashBody: "আপনার প্রোফাইল ও সেটিংস নিরাপদ আছে। আবার চেষ্টা করুন, আর বারবার হলে অ্যাপটি আবার খুলুন।",
    tryAgain: "আবার চেষ্টা করুন",
    storageTitle: "আপনার অগ্রগতি এখন সংরক্ষণ করা যাচ্ছে না",
    storageBody: "অ্যাপ বন্ধ না করা পর্যন্ত পরিবর্তনগুলো কাজ করবে। ফোনে কিছু জায়গা খালি করে TashZone আবার খুলুন।",
    ok: "ঠিক আছে",
    play: "খেলুন",
  },
});
