import { localized } from "../../i18n";

export const U = localized("ui", {
  en: {
    avatar: "Avatar",
    back: "Back",
    close: "Close",
    del: "Delete",
    code: "Code",
    digits: (label: string, n: number, of: number) => `${label}, ${n} of ${of} digits`,
    step: (n: number, title: string, body: string) => `Step ${n}. ${title}. ${body}`,
    stepOf: (at: number, n: number) => `Step ${at} of ${n}`,
    tabs: { index: "Play", games: "Games", me: "You", settings: "Settings" },
    crashTitle: (where?: string) => `Something went wrong${where ? ` in ${where}` : ""}`,
    crashBody: "Your profile and settings are safe. Try again, or restart the app.",
    tryAgain: "Try again",
    storageTitle: "Progress can't be saved",
    storageBody: "Changes last until you close the app. Free up space, then reopen TashZone.",
    ok: "OK",
    play: "Play",
  },
  ur: {
    avatar: "اوتار",
    back: "واپس",
    close: "بند کریں",
    del: "مٹائیں",
    code: "کوڈ",
    digits: (label: string, n: number, of: number) => `${label}، ${of} میں سے ${n} ہندسے`,
    step: (n: number, title: string, body: string) => `مرحلہ ${n}۔ ${title}۔ ${body}`,
    stepOf: (at: number, n: number) => `${n} میں سے مرحلہ ${at}`,
    tabs: { index: "کھیلیں", games: "کھیل", me: "آپ", settings: "ترتیبات" },
    crashTitle: (where?: string) => `${where ? `${where} میں ` : ""}کچھ گڑبڑ ہو گئی`,
    crashBody: "آپ کی پروفائل اور ترتیبات محفوظ ہیں۔ دوبارہ کوشش کریں، یا ایپ ری اسٹارٹ کریں۔",
    tryAgain: "دوبارہ کوشش کریں",
    storageTitle: "پیش رفت محفوظ نہیں ہو رہی",
    storageBody: "ایپ بند ہونے تک تبدیلیاں برقرار رہیں گی۔ فون میں جگہ خالی کر کے TashZone دوبارہ کھولیں۔",
    ok: "ٹھیک ہے",
    play: "کھیلیں",
  },
  hi: {
    avatar: "अवतार",
    back: "वापस",
    close: "बंद करें",
    del: "मिटाएँ",
    code: "कोड",
    digits: (label: string, n: number, of: number) => `${label}, ${of} में से ${n} अंक`,
    step: (n: number, title: string, body: string) => `चरण ${n}. ${title}. ${body}`,
    stepOf: (at: number, n: number) => `चरण ${at}/${n}`,
    tabs: { index: "खेलें", games: "खेल", me: "आप", settings: "सेटिंग्स" },
    crashTitle: (where?: string) => `${where ? `${where} में ` : ""}कुछ गड़बड़ हो गई`,
    crashBody: "आपकी प्रोफ़ाइल और सेटिंग्स सुरक्षित हैं। फिर कोशिश करें, या ऐप रीस्टार्ट करें।",
    tryAgain: "फिर कोशिश करें",
    storageTitle: "प्रोग्रेस सेव नहीं हो रही",
    storageBody: "ऐप बंद होने तक बदलाव बने रहेंगे। फ़ोन में जगह खाली करके TashZone फिर खोलें।",
    ok: "ठीक है",
    play: "खेलें",
  },
  ne: {
    avatar: "अवतार",
    back: "पछाडि",
    close: "बन्द गर्नुहोस्",
    del: "मेटाउनुहोस्",
    code: "कोड",
    digits: (label: string, n: number, of: number) => `${label}, ${of} मध्ये ${n} अङ्क`,
    step: (n: number, title: string, body: string) => `चरण ${n}. ${title}. ${body}`,
    stepOf: (at: number, n: number) => `चरण ${at}/${n}`,
    tabs: { index: "खेलौं", games: "खेलहरू", me: "तपाईं", settings: "सेटिङ" },
    crashTitle: (where?: string) => `${where ? `${where}मा ` : ""}केही गडबड भयो`,
    crashBody: "तपाईंको प्रोफाइल र सेटिङ सुरक्षित छन्। फेरि प्रयास गर्नुहोस्, नभए एप फेरि खोल्नुहोस्।",
    tryAgain: "फेरि प्रयास गर्नुहोस्",
    storageTitle: "प्रगति सेभ भइरहेको छैन",
    storageBody: "एप बन्द नगरेसम्म परिवर्तन रहन्छन्। फोनमा ठाउँ खाली गरेर TashZone फेरि खोल्नुहोस्।",
    ok: "ठिक छ",
    play: "खेल्नुहोस्",
  },
  bn: {
    avatar: "অবতার",
    back: "ফিরুন",
    close: "বন্ধ করুন",
    del: "মুছুন",
    code: "কোড",
    digits: (label: string, n: number, of: number) => `${label}, ${of}টির মধ্যে ${n}টি সংখ্যা`,
    step: (n: number, title: string, body: string) => `ধাপ ${n}. ${title}. ${body}`,
    stepOf: (at: number, n: number) => `ধাপ ${at}/${n}`,
    tabs: { index: "খেলুন", games: "খেলা", me: "আপনি", settings: "সেটিংস" },
    crashTitle: (where?: string) => `${where ? `${where}-এ ` : ""}কিছু একটা গোলমাল হয়েছে`,
    crashBody: "আপনার প্রোফাইল ও সেটিংস নিরাপদ। আবার চেষ্টা করুন, না হলে অ্যাপটি আবার চালু করুন।",
    tryAgain: "আবার চেষ্টা করুন",
    storageTitle: "অগ্রগতি সেভ হচ্ছে না",
    storageBody: "অ্যাপ বন্ধ না করা পর্যন্ত পরিবর্তন থাকবে। ফোনে জায়গা খালি করে TashZone আবার খুলুন।",
    ok: "ঠিক আছে",
    play: "খেলুন",
  },
});
