"""Profile Bundles (C-22): the room settings FastAPI accepts, validated with the same JSON Schema the engine
compiler agrees with (bundles generated by shared/engine/scripts/bundle-profiles.mjs into app/Schemas/contracts)."""

import json
from functools import lru_cache
from pathlib import Path

from jsonschema import Draft202012Validator

BUNDLE_DIR = Path(__file__).resolve().parents[1] / "Schemas" / "contracts" / "profile_bundles"


@lru_cache
def bundles() -> dict[str, dict]:
    out = {}
    for p in sorted(BUNDLE_DIR.glob("*.json")):
        b = json.loads(p.read_text())
        out[b["profile_id"]] = b
    return out


def validate_settings(profile_id: str, preset: str, settings: dict) -> str | None:
    b = bundles().get(profile_id)
    if b is None:
        return "unknown_profile"
    if preset not in b["presets"]:
        return "unknown_preset"
    errors = list(Draft202012Validator(b["settings_schema"]).iter_errors(settings))
    if errors:
        return "invalid_settings"
    if settings.get("handicap", 0):
        return "handicap_offline_only"  # L39: handicap deals are for tables against bots only
    return None


def seat_count(profile_id: str, settings: dict) -> int:
    """Seats at the table: Bhabhi's `players` setting (3–8), otherwise 4."""
    props = bundles()[profile_id]["settings_schema"]["properties"]
    if "players" in props:
        return int(settings.get("players", props["players"]["default"]))
    return 4
