TASHZONE_UPLOAD_STORE_FILE=tashzone-release.keystore
TASHZONE_UPLOAD_KEY_ALIAS=tashzone
TASHZONE_UPLOAD_STORE_PASSWORD=JZt7tggRrrlbuNGuMMCCvuHzWTLT
TASHZONE_UPLOAD_KEY_PASSWORD=JZt7tggRrrlbuNGuMMCCvuHzWTLT
