import { localized } from "../../i18n";

export const I = localized("info", {
  en: {
    howto: { title: "How to play", brief: "Each game in brief", rules: "Rules", play: "Play" },
    rules: {
      title: "Rules and terms",
      soonChip: (name: string) => `${name} · soon`,
      terms: "What the words mean",
      varies: "Varies by region",
      variesNote: "Nothing is picked for you: every table shows which style is on.",
      play: (name: string) => `Play ${name}`,
      deal: (d: string) => `The deal: ${d}`,
      term: (term: string, meaning: string) => `${term}: ${meaning}`,
      teaserNote: "Full rules arrive when the game is playable.",
      missing: "Rules for this game are still being written.",
    },
    atlas: {
      title: "All screens",
      count: (n: number, all: number) => `${n} of ${all}`,
      dialog: "Dialog",
      open: (label: string) => `Open ${label}`,
      note: "Tap a screen to open it. Dialogs sit over other screens, so they're listed with their wording.",
    },
  },
  ur: {
    howto: { title: "کیسے کھیلیں", brief: "ہر کھیل مختصر میں", rules: "قوانین", play: "کھیلیں" },
    rules: {
      title: "قوانین اور اصطلاحات",
      soonChip: (name: string) => `${name} · جلد`,
      terms: "الفاظ کے معنی",
      varies: "علاقے کے حساب سے فرق",
      variesNote: "کچھ پہلے سے طے نہیں: ہر میز پر چلتا انداز دکھتا ہے۔",
      play: (name: string) => `${name} کھیلیں`,
      deal: (d: string) => `بانٹ: ${d}`,
      term: (term: string, meaning: string) => `${term}: ${meaning}`,
      teaserNote: "کھیل تیار ہوتے ہی پورے قوانین آئیں گے۔",
      missing: "اس کھیل کے قوانین ابھی لکھے جا رہے ہیں۔",
    },
    atlas: {
      title: "تمام اسکرینیں",
      count: (n: number, all: number) => `${all} میں سے ${n}`,
      dialog: "ڈائیلاگ",
      open: (label: string) => `${label} کھولیں`,
      note: "کھولنے کے لیے اسکرین پر ٹیپ کریں۔ ڈائیلاگ دوسری اسکرینوں پر آتے ہیں، اس لیے عبارت کے ساتھ دیے گئے ہیں۔",
    },
  },
  hi: {
    howto: { title: "कैसे खेलें", brief: "हर खेल संक्षेप में", rules: "नियम", play: "खेलें" },
    rules: {
      title: "नियम और शब्द",
      soonChip: (name: string) => `${name} · जल्द`,
      terms: "शब्दों के मतलब",
      varies: "इलाके के हिसाब से अलग",
      variesNote: "कुछ पहले से तय नहीं: हर टेबल पर चल रहा अंदाज़ दिखता है।",
      play: (name: string) => `${name} खेलें`,
      deal: (d: string) => `बँटाई: ${d}`,
      term: (term: string, meaning: string) => `${term}: ${meaning}`,
      teaserNote: "खेल तैयार होते ही पूरे नियम आएँगे।",
      missing: "इस खेल के नियम अभी लिखे जा रहे हैं।",
    },
    atlas: {
      title: "सभी स्क्रीन",
      count: (n: number, all: number) => `${all} में से ${n}`,
      dialog: "डायलॉग",
      open: (label: string) => `${label} खोलें`,
      note: "खोलने के लिए स्क्रीन पर टैप करें। डायलॉग दूसरी स्क्रीन के ऊपर आते हैं, इसलिए उनके शब्दों के साथ दिए गए हैं।",
    },
  },
  ne: {
    howto: { title: "कसरी खेल्ने", brief: "हरेक खेल छोटकरीमा", rules: "नियम", play: "खेल्नुहोस्" },
    rules: {
      title: "नियम र शब्द",
      soonChip: (name: string) => `${name} · छिट्टै`,
      terms: "शब्दका अर्थ",
      varies: "ठाउँअनुसार फरक",
      variesNote: "केही पहिल्यै तोकिँदैन: हरेक टेबलमा चलिरहेको शैली देखिन्छ।",
      play: (name: string) => `${name} खेल्नुहोस्`,
      deal: (d: string) => `बाँडाइ: ${d}`,
      term: (term: string, meaning: string) => `${term}: ${meaning}`,
      teaserNote: "खेल तयार भएपछि पूरा नियम आउनेछन्।",
      missing: "यो खेलका नियम अझै लेखिँदैछन्।",
    },
    atlas: {
      title: "सबै स्क्रिन",
      count: (n: number, all: number) => `${all} मध्ये ${n}`,
      dialog: "संवाद",
      open: (label: string) => `${label} खोल्नुहोस्`,
      note: "स्क्रिन खोल्न ट्याप गर्नुहोस्। संवाद अरू स्क्रिनमाथि आउँछन्, त्यसैले शब्दसहित राखिएका छन्।",
    },
  },
  bn: {
    howto: { title: "কীভাবে খেলবেন", brief: "এক নজরে প্রতিটি খেলা", rules: "নিয়ম", play: "খেলুন" },
    rules: {
      title: "নিয়ম ও শব্দ",
      soonChip: (name: string) => `${name} · শিগগিরই`,
      terms: "শব্দের মানে",
      varies: "অঞ্চলভেদে আলাদা",
      variesNote: "আগে থেকে কিছু ঠিক করা নেই: প্রতিটি টেবিলে কোন ধরন চলছে দেখা যায়।",
      play: (name: string) => `${name} খেলুন`,
      deal: (d: string) => `বাঁটা: ${d}`,
      term: (term: string, meaning: string) => `${term}: ${meaning}`,
      teaserNote: "খেলা তৈরি হলে পুরো নিয়ম আসবে।",
      missing: "এই খেলার নিয়ম এখনো লেখা হচ্ছে।",
    },
    atlas: {
      title: "সব স্ক্রিন",
      count: (n: number, all: number) => `${all}টির মধ্যে ${n}টি`,
      dialog: "ডায়ালগ",
      open: (label: string) => `${label} খুলুন`,
      note: "স্ক্রিন খুলতে ট্যাপ করুন। ডায়ালগ অন্য স্ক্রিনের ওপর আসে, তাই লেখাসহ দেখানো হলো।",
    },
  },
});
