/** English strings for every multiplayer screen, one block per screen (mockup copy). */
export const copy = {
  hostWifi: {
    title: "Same Wi-Fi table",
    lead: "Friends on this Wi-Fi join with the PIN or the code. No internet is used.",
    open: "Open the table",
    opening: "Opening the table…",
    pin: "PIN",
    pinHint: "Say it aloud, or let them scan the code.",
    address: "Address",
    addressHint: "If nobody sees your table, they can type this on Join a table.",
    qrLabel: "QR code to join this table. Scanning it also fills in the PIN.",
    seatsNote: "Keep this screen open and the phone awake. Guests only ever see their own cards.",
    start: "Start · bots take the empty seats",
    stop: "Close the table",
    you: "You (host)",
    openSeat: "Open seat",
    away: "Away",
    remove: (name: string) => `Remove ${name}`,
    removed: (name: string) => `${name} was removed. The PIN changed, so share the new one with anyone still to join.`,
    seats: "Seats",
    qrShort: "Scan to join",
    locked: { title: "Table locked", body: "Too many wrong PINs were tried. Nobody new can join. Close the table and open a new one for a fresh PIN." },
    ending: { title: "Close this table?", body: "Everyone playing on your Wi-Fi table is disconnected and the match ends.", stay: "Keep playing" },
  },
  joinWifi: {
    title: "Join a table",
    looking: "Looking for tables on this network…",
    none: "No tables found yet. The host must have opened a table on the same Wi-Fi.",
    nearby: "Tables nearby",
    rescan: "Look again",
    scan: "Scan the host's code",
    enterPin: "Type the PIN and address",
    notListed: "Not listed? Scan the host's code, or ask for the four-digit PIN and the address on their screen.",
    hotspot: "No Wi-Fi? Use a hotspot",
    scanBad: "That code is not a TashZone table on this network. Ask the host to show the table code again.",
    dismiss: "OK",
    dropped: {
      HOST_GONE: { title: "The table ended", body: "The host's phone stopped answering. It may have gone to sleep, left the Wi-Fi or closed TashZone." },
      KICKED: { title: "The host removed you", body: "You can no longer join this table. Ask the host if you would like to play again." },
      UNREACHABLE: { title: "Could not reach the table", body: "Check that you and the host are on the same Wi-Fi, and that the table is still open." },
      UPDATE_REQUIRED: { title: "Different versions of TashZone", body: "Update TashZone on the older phone, then join again." },
      TABLE_FULL: { title: "The table is full", body: "Every seat is taken, or the match has already started." },
    } as Record<string, { title: string; body: string }>,
  },
  pin: {
    title: "Enter PIN",
    lead: "The host's phone is showing four digits.",
    lockout: "Ten wrong tries across all phones lock the table for everyone. The host then opens a new table.",
    label: "Table PIN",
    join: "Join this table",
    joining: "Joining the table…",
    addressLabel: "Host address",
    addressPlaceholder: "192.168.1.20:41234",
    addressHint: "Shown on the host's screen under the PIN.",
    addressFirst: "Type the host address first, then the PIN.",
    tryAgain: "Wrong PIN or the table is locked. Check the four digits on the host's screen.",
    tryLocked: "Still no luck. If the host sees “Table locked”, they must close it and open a new table.",
  },
  hotspot: {
    title: "Hotspot table",
    lead: "No Wi-Fi router? One phone can make the network. This works without mobile data, but the phones must be close together.",
    steps: [
      { t: "Host: turn on your hotspot", b: "Phone settings → Network → Hotspot. Note its name and password." },
      { t: "Everyone else: join it", b: "Pick the host's hotspot in Wi-Fi settings and enter the password." },
      { t: "Then open TashZone", b: "Host taps Host a table, guests tap Join a table." },
    ],
    hostNote: "Some phones do not report their own hotspot address to apps. If the host sees “no Wi-Fi”, use a shared Wi-Fi network instead, or let a friend host.",
    privacy: "TashZone never reads your network name and needs no location permission.",
    host: "Host a table",
    join: "Join a table",
  },
  room: {
    title: "Private room",
    lead: "Needs internet. Share the code privately with the people you want at the table.",
    game: "Game",
    preset: "Rules",
    length: "Match length",
    create: "Create a room",
    or: "or join one",
    codePlaceholder: "BK7Q2M",
    codeLabel: "Room code",
    codeHint: "Codes skip the vowels, so they never spell a word.",
    join: "Join this room",
    quick: "Quick match",
    quickHint: "Play with whoever is waiting. Bots fill empty seats after a short wait.",
    noGames: "No game here can be played online yet.",
    working: "Connecting…",
    modes: { join: "Join", create: "Create", quick: "Quick" },
    modesLabel: "What would you like to do?",
    summary: (game: string, rules: string, length: string, players?: number) => [game, rules, length, players ? `${players} players` : ""].filter(Boolean).join(" · "),
    change: "Change",
    done: "Done",
    setupTitle: "Table setup",
  },
  lobby: {
    titlePrefix: "Room ",
    share: "Share",
    shareLabel: "Share this code",
    shareMessage: (code: string, game: string) => `Join my ${game} table on TashZone. Room code: ${code}`,
    hostState: "Host",
    ready: "Ready",
    openState: "Bot fills",
    openName: "Open seat",
    chat: "Quick chat only until the game starts.",
    chatOff: "Typing to other players is turned off.",
    start: "Start the game",
    startBots: "Start · bots take the empty seats",
    guestWaiting: "Waiting for the host to start.",
    leave: "Leave the room",
    wifiTitle: "Wi-Fi table",
    wifiLeave: "Leave the table",
    wifiGuestChat: "Quick chat only. Typing to other players is never available on a Wi-Fi table.",
    connecting: { title: "Connecting…", body: "Taking your seat at the table." },
    leaveTitle: "Leave this table?",
    leaveFacts: (wifi: boolean) => [
      { mark: "1", title: "Your seat opens up", body: "A bot or another player can take it." },
      { mark: "2", title: "You can join again", body: wifi ? "Use the host's PIN while the table is still open." : "Use the same code while the room is still open." },
    ],
    stay: "Stay",
  },
  queue: {
    title: "Quick match",
    finding: "Finding players",
    position: (n: number) => `You are number ${n} in line.`,
    backfill: (s: number) => (s > 0 ? `Bots join in about ${s} seconds if nobody else does.` : "Bots are joining now."),
    cancel: "Cancel",
  },
  match: {
    over: "Match over",
    interrupted: "Match interrupted",
    interruptedTitle: "Stopped by a server update",
    interruptedBody: "This match counts as neither a win nor a loss. Your room is still open. Start again with the same players.",
    winner: "Winner",
    standings: "Standings",
    you: "You",
    back: "Back to Play",
    placed: (place: number, of: number) => `You placed ${ordinal(place)} of ${of}`,
    interruptedWifiTitle: "The table stopped early",
    interruptedWifiBody: "The match ended before a winner was decided, so it counts as neither a win nor a loss. The host can open a new table.",
    leaveTitle: "Leave the results?",
    leaveFacts: [{ mark: "1", title: "The table closes", body: "You go back to Play. Start a new table to play again." }],
    hostLeaveFacts: [{ mark: "1", title: "The table ends for everyone", body: "Your phone runs this table. Leaving disconnects every guest." }],
    leave: "Leave",
    stay: "Stay",
  },
  table: {
    leave: "Leave",
    leaveTitle: "Leave this match?",
    stay: "Stay",
    leaveFacts: (wifi: boolean) => [
      { mark: "1", title: "A bot plays your seat", body: "It plays for you until the match ends." },
      { mark: "2", title: "You can come back", body: `Rejoin while the ${wifi ? "table" : "room"} is live.` },
    ],
    hostFacts: [
      { mark: "1", title: "The table ends for everyone", body: "Your phone runs this table. Closing it disconnects every guest and ends the match." },
    ],
    tryAgain: "Try again",
    openStore: "Open the store",
    leaveNow: "Leave the table",
  },
  scanner: {
    camera: "Camera view. Point it at the table QR code.",
    point: "Point the camera at the QR code on the host's screen.",
    cancel: "Cancel",
    off: "Camera access is turned off for TashZone. Turn it on in your phone's settings to scan, or type the table code instead.",
    why: "TashZone needs the camera only to scan the table QR code. You can allow it, or type the table code instead.",
    privacy: "The camera is used only to scan the QR code. Nothing is recorded or saved.",
    settings: "Open settings",
    scan: "Scan QR code",
  },
  reconnecting: { title: "Reconnecting…", body: "Your seat is kept while the connection comes back. If it takes long, tap Try again." },
  offline: { title: "You are offline", body: "The connection could not be restored. Check your internet or Wi-Fi, then tap Try again." },
  paused: { title: "Table paused", body: "The server is catching up. Every clock is frozen and restarts in full." },
  update: { title: "Update to play online", body: "This table uses newer rules than your copy of TashZone. Update, then open the table again.", back: "Back" },
  locked: {
    header: "Turned off by a parent",
    back: "Back",
    online: { title: "Online rooms are turned off", body: "A parent can turn them back on in Parent Settings with the PIN.", action: "Open Parent Settings" },
    wifi: { title: "Wi-Fi tables are turned off", body: "A parent can turn them back on in Parent Settings with the PIN.", action: "Open Parent Settings" },
  },
  pass: {
    lead: "Pass the phone to",
    body: (name: string) => `The cards are hidden. Only ${name} should look.`,
    ready: (name: string) => `I'm ${name}`,
    fallbackName: "the next player",
  },
  errors: {
    NETWORK: "Could not reach the server. Check your connection and try again.",
    ROOM_NOT_FOUND: "That code did not match an open room. Check it and try again.",
    ROOM_FULL: "That room is full.",
    ROOM_CLOSED: "This room has closed.",
    ROOM_EXPIRED: "That code has expired. Rooms close once they have been idle for a while.",
    ONLINE_ROOMS_OFF: "Online rooms are turned off in Parent Settings.",
    ONLINE_DISABLED: "Online play is paused for maintenance. Try again later.",
    GAME_DISABLED: "This game is not available online right now.",
    BLOCKED: "You cannot join this room.",
    KICKED: "The host removed you from this room.",
    TICKET_EXPIRED: "No table was found in time. Try again.",
    UNAUTHORIZED: "Your online session ended. Try again.",
    RATE_LIMITED: "Too many tries. Wait a moment and try again.",
    ERROR: "Something went wrong. Try again.",
    NO_WIFI: "No Wi-Fi connection found. Connect this phone to the same Wi-Fi as your friends, or turn on a hotspot, then try again.",
    SERVER_FAILED: "The table could not be opened on this phone. Close other apps that use the network and try again.",
    DISCOVERY_FAILED: "Nearby tables cannot be listed right now. Scan the host's code or type the address instead.",
    UNREACHABLE: "Could not reach that table. Check that you and the host are on the same Wi-Fi, and that the table is still open.",
    HOST_GONE: "The host's phone is no longer reachable, so this table has ended.",
    WRONG_PIN: "Wrong PIN, or the table is locked. Check the four digits on the host's screen.",
    TABLE_FULL: "That table is full, or its match has already started.",
    UPDATE_REQUIRED: "This table uses a different version of TashZone. Update on the older phone, then join again.",
    ADDRESS_INVALID: "That address does not look right. It should read like 192.168.1.20:41234, as shown on the host's screen.",
    QR_INVALID: "That code is not a TashZone table on this network.",
  } as Record<string, string>,
};

export function errorMessage(code: string | null | undefined): string {
  return (code && copy.errors[code]) || copy.errors.ERROR!;
}

function ordinal(n: number): string {
  const v = n % 100;
  return `${n}${["th", "st", "nd", "rd"][(v - 20) % 10] ?? ["th", "st", "nd", "rd"][v] ?? "th"}`;
}
