import { isRTL, localized } from "../../i18n";

export const ltr = (s: string): string => (isRTL() ? `⁦${s}⁩` : s);

export const copy = localized("multiplayer", {
  en: {
    hostWifi: {
      title: "Same Wi-Fi table",
      lead: "Friends on this Wi-Fi join with the PIN or QR code. No internet needed.",
      open: "Open table",
      opening: "Opening table…",
      pin: "PIN",
      pinHint: "Read it out, or let them scan.",
      addressLine: (address: string) => `Address: ${address}. Can't see your table? Friends can type this in Join a table.`,
      qrLabel: "QR code to join. It fills in the PIN too.",
      seatsNote: "Keep this screen open and the phone awake. Guests see only their own cards.",
      start: "Start · bots fill empty seats",
      stop: "Close table",
      you: "You (host)",
      openSeat: "Open seat",
      away: "Away",
      remove: (name: string) => `Remove ${name}`,
      removed: (name: string) => `${name} removed. The PIN changed, so share the new one.`,
      seats: "Seats",
      qrShort: "Scan to join",
      locked: { title: "Table locked", body: "Too many wrong PINs. No one new can join. Close and reopen the table for a new PIN." },
      ending: { title: "Close this table?", body: "Everyone is disconnected and the match ends.", stay: "Keep playing" },
    },
    joinWifi: {
      title: "Join a table",
      looking: "Looking for tables…",
      none: "No tables yet. The host must open one on this Wi-Fi.",
      nearby: "Tables nearby",
      rescan: "Look again",
      scan: "Scan host's code",
      enterPin: "Enter PIN and address",
      notListed: "Not listed? Scan the host's code, or enter the PIN and address from their screen.",
      hotspot: "No Wi-Fi? Use a hotspot",
      scanBad: "Not a TashZone table on this network. Ask the host to show the code again.",
      dismiss: "OK",
      hostTable: (name: string) => `${name}'s table`,
      dropped: {
        HOST_GONE: { title: "Table ended", body: "The host's phone stopped responding. It may have slept, left the Wi-Fi or closed TashZone." },
        KICKED: { title: "The host removed you", body: "You can't rejoin this table. To play again, ask the host." },
        UNREACHABLE: { title: "Can't reach the table", body: "Check you're both on the same Wi-Fi and the table is open." },
        UPDATE_REQUIRED: { title: "TashZone versions differ", body: "Update TashZone on the older phone, then rejoin." },
        TABLE_FULL: { title: "Table full", body: "All seats are taken, or the match has started." },
      } as Record<string, { title: string; body: string }>,
    },
    pin: {
      title: "Enter PIN",
      lead: "The 4 digits on the host's phone.",
      lockout: "10 wrong tries in total lock the table. The host then opens a new one.",
      label: "Table PIN",
      join: "Join table",
      joining: "Joining…",
      addressLabel: "Host address",
      addressHint: "Shown under the PIN on the host's screen.",
      addressFirst: "Enter the host address first, then the PIN.",
      tryAgain: "Wrong PIN, or the table is locked. Check the host's screen.",
      tryLocked: "If the host sees “Table locked”, they must open a new table.",
    },
    hotspot: {
      title: "Hotspot table",
      lead: "No router? One phone can be the network. No data used, just keep phones close.",
      steps: [
        { t: "Host: turn on hotspot", b: "Settings → Network → Hotspot. Note its name and password." },
        { t: "Others: join it", b: "In Wi-Fi settings, pick the host's hotspot and enter the password." },
        { t: "Open TashZone", b: "Host taps Host a table; guests tap Join a table." },
      ],
      hostNote: "Some phones hide their hotspot address. If the host sees “No Wi-Fi found”, use shared Wi-Fi or let a friend host.",
      privacy: "TashZone never reads your network name or asks for location.",
      host: "Host a table",
      join: "Join a table",
    },
    room: {
      title: "Private room",
      lead: "Needs internet. Share the code only with people you want to play.",
      game: "Game",
      preset: "Rules",
      length: "Match length",
      players: "Players",
      create: "Create room",
      or: "or join one",
      codeLabel: "Room code",
      codeSpoken: (spelled: string) => `Room code: ${spelled}`,
      codeHint: "Codes skip 0, O, 1, I and L, so they're easy to read out.",
      join: "Join room",
      quick: "Quick match",
      quickHint: "Play whoever's waiting. Bots fill empty seats after a moment.",
      noGames: "No games are online yet.",
      working: "Connecting…",
      modes: { join: "Join", create: "Create", quick: "Quick" },
      modesLabel: "What do you want to do?",
      summary: (game: string, rules: string, length: string, players?: number) => [game, rules, length, players ? `${players} players` : ""].filter(Boolean).join(" · "),
      lengthValue: (label: string, unit: string) => `${label} ${unit.toLowerCase()}`,
      setupLabel: (summary: string) => `Table setup: ${summary}. Change`,
      change: "Change",
      done: "Done",
      setupTitle: "Table setup",
    },
    lobby: {
      title: (code: string) => `Room ${code}`,
      share: "Share",
      shareLabel: "Share code",
      shareMessage: (code: string, game: string) => (game ? `Join my ${game} table on TashZone. Room code: ${code}` : `Join my table on TashZone. Room code: ${code}`),
      hostState: "Host",
      ready: "Ready",
      openState: "Bot fills",
      openName: "Open seat",
      chat: "Quick chat only until the game starts.",
      chatOff: "Typed chat is off.",
      start: "Start game",
      startBots: "Start · bots fill empty seats",
      guestWaiting: "Waiting for the host to start.",
      leave: "Leave room",
      wifiTitle: "Wi-Fi table",
      wifiLeave: "Leave table",
      wifiGuestChat: "Quick chat only. Wi-Fi tables have no typed chat.",
      connecting: { title: "Connecting…", body: "Taking your seat." },
      leaveTitle: "Leave this table?",
      leaveFacts: (wifi: boolean) => [
        { mark: "1", title: "Your seat opens up", body: "A bot or another player can take it." },
        { mark: "2", title: "You can rejoin", body: wifi ? "Use the host's PIN while the table is open." : "Use the same code while the room is open." },
      ],
      stay: "Stay",
    },
    queue: {
      title: "Quick match",
      finding: "Finding players",
      position: (n: number) => `You're #${n} in line.`,
      backfill: (s: number) => (s > 0 ? `Bots join in about ${s} ${s === 1 ? "second" : "seconds"} if no one else does.` : "Bots are joining."),
      cancel: "Cancel",
    },
    match: {
      over: "Match over",
      interrupted: "Match interrupted",
      interruptedTitle: "Stopped by a server update",
      interruptedBody: "It won't count as a win or loss. Your room is still open, so start again with the same players.",
      winner: "Winner",
      standings: "Standings",
      you: "You",
      back: "Back to Play",
      placed: (place: number, of: number) => `You placed ${ordinal(place)} of ${of}`,
      place: (n: number) => `Place ${n}`,
      interruptedWifiTitle: "Table stopped early",
      interruptedWifiBody: "No winner, so it won't count as a win or loss. The host can open a new table.",
      leaveTitle: "Leave results?",
      leaveFacts: [{ mark: "1", title: "The table closes", body: "You'll return to Play. Start a new table to play again." }],
      hostLeaveFacts: [{ mark: "1", title: "Table ends for everyone", body: "Your phone runs this table. Leaving disconnects all guests." }],
      leave: "Leave",
      stay: "Stay",
    },
    table: {
      leave: "Leave",
      leaveTitle: "Leave this match?",
      stay: "Stay",
      leaveFacts: (wifi: boolean) => [
        { mark: "1", title: "A bot takes your seat", body: "It plays your turns until the match ends." },
        { mark: "2", title: "You can come back", body: `Rejoin while the ${wifi ? "table" : "room"} is live.` },
      ],
      hostFacts: [
        { mark: "1", title: "Table ends for everyone", body: "Your phone runs this table. Closing it disconnects all guests and ends the match." },
      ],
      tryAgain: "Try again",
      openStore: "Open store",
      leaveNow: "Leave table",
    },
    scanner: {
      camera: "Camera view. Point it at the table's QR code.",
      point: "Point the camera at the host's QR code.",
      cancel: "Cancel",
      off: "Camera is off for TashZone. Turn it on in phone settings, or type the code.",
      why: "TashZone uses the camera only to scan the table's QR code. Allow it, or type the code.",
      privacy: "The camera only scans the QR code. Nothing is recorded or saved.",
      settings: "Open settings",
      scan: "Scan QR code",
      qr: "QR code to join the table",
    },
    seat: (name: string, status: string) => `${name}, ${status}`,
    seatName: (n: number) => `Seat ${n}`,
    score: { bhabhi: (n: number) => `${n}× Bhabhi`, points: (n: number) => `${n} pts` },
    defaultName: "Player",
    reconnecting: { title: "Reconnecting…", body: "Your seat is held. Taking too long? Tap Try again." },
    offline: { title: "You're offline", body: "Couldn't reconnect. Check your internet or Wi-Fi, then tap Try again." },
    paused: { title: "Table paused", body: "The server is catching up. Clocks are frozen and restart in full." },
    update: { title: "Update to play online", body: "This table uses newer rules. Update TashZone, then reopen the table.", back: "Back" },
    locked: {
      header: "Turned off by a parent",
      back: "Back",
      online: { title: "Online rooms are off", body: "A parent can turn them on in Parent controls with the PIN.", action: "Open Parent controls" },
      wifi: { title: "Wi-Fi tables are off", body: "A parent can turn them on in Parent controls with the PIN.", action: "Open Parent controls" },
    },
    pass: {
      lead: "Pass the phone to",
      body: (name: string) => `Cards are hidden. Only ${name} should look.`,
      ready: (name: string) => `I'm ${name}`,
      fallbackName: "the next player",
    },
    errors: {
      NETWORK: "Can't reach the server. Check your connection and try again.",
      ROOM_NOT_FOUND: "No open room with that code. Check it and try again.",
      ROOM_FULL: "That room is full.",
      ROOM_CLOSED: "This room has closed.",
      ROOM_EXPIRED: "That code has expired. Idle rooms close after a while.",
      ONLINE_ROOMS_OFF: "Online rooms are off in Parent controls.",
      ONLINE_DISABLED: "Online play is down for maintenance. Try again later.",
      GAME_DISABLED: "This game isn't online right now.",
      BLOCKED: "You can't join this room.",
      KICKED: "The host removed you from this room.",
      TICKET_EXPIRED: "Couldn't find a table in time. Try again.",
      UNAUTHORIZED: "Your online session ended. Try again.",
      RATE_LIMITED: "Too many tries. Wait a moment, then try again.",
      ERROR: "Something went wrong. Try again.",
      NO_WIFI: "No Wi-Fi found. Join your friends' Wi-Fi or turn on a hotspot, then try again.",
      SERVER_FAILED: "Couldn't open the table on this phone. Close other network apps and try again.",
      DISCOVERY_FAILED: "Can't list nearby tables. Scan the host's code or enter the address.",
      UNREACHABLE: "Can't reach that table. Check you're both on the same Wi-Fi and it's open.",
      HOST_GONE: "Lost contact with the host's phone, so the table has ended.",
      WRONG_PIN: "Wrong PIN, or the table is locked. Check the host's screen.",
      TABLE_FULL: "That table is full, or the match has started.",
      UPDATE_REQUIRED: "TashZone versions differ. Update the older phone, then rejoin.",
      ADDRESS_INVALID: "That address doesn't look right. Copy it from the host's screen, like 192.168.1.20:41234.",
      QR_INVALID: "Not a TashZone table on this network.",
    } as Record<string, string>,
  },
  ur: {
    hostWifi: {
      title: "ایک ہی Wi-Fi پر میز",
      lead: "اسی Wi-Fi والے دوست PIN یا QR کوڈ سے شامل ہوں۔ انٹرنیٹ کی ضرورت نہیں۔",
      open: "میز کھولیں",
      opening: "میز کھل رہی ہے…",
      pin: "PIN",
      pinHint: "بول کر بتائیں، یا کوڈ اسکین کروائیں۔",
      addressLine: (address: string) => `پتہ: ${address}۔ میز نظر نہ آئے تو دوست “میز میں شامل ہوں” میں یہ لکھیں۔`,
      qrLabel: "شامل ہونے کا QR کوڈ۔ PIN بھی خود بھر جاتا ہے۔",
      seatsNote: "یہ اسکرین کھلی اور فون جاگتا رکھیں۔ مہمان صرف اپنے پتے دیکھتے ہیں۔",
      start: "شروع کریں · خالی جگہوں پر بوٹ",
      stop: "میز بند کریں",
      you: "آپ (میزبان)",
      openSeat: "خالی جگہ",
      away: "غیر حاضر",
      remove: (name: string) => `${name} کو ہٹائیں`,
      removed: (name: string) => `${name} کو ہٹا دیا۔ PIN بدل گیا ہے، نیا PIN بتائیں۔`,
      seats: "جگہیں",
      qrShort: "اسکین کر کے شامل ہوں",
      locked: { title: "میز لاک ہو گئی", body: "کئی بار غلط PIN۔ اب کوئی نیا شامل نہیں ہو سکتا۔ نئے PIN کے لیے میز بند کر کے دوبارہ کھولیں۔" },
      ending: { title: "میز بند کریں؟", body: "سب کا رابطہ ٹوٹ جائے گا اور میچ ختم ہو جائے گا۔", stay: "کھیلتے رہیں" },
    },
    joinWifi: {
      title: "میز میں شامل ہوں",
      looking: "میزیں ڈھونڈ رہے ہیں…",
      none: "ابھی کوئی میز نہیں۔ میزبان اسی Wi-Fi پر میز کھولے۔",
      nearby: "قریبی میزیں",
      rescan: "دوبارہ ڈھونڈیں",
      scan: "میزبان کا کوڈ اسکین کریں",
      enterPin: "PIN اور پتہ لکھیں",
      notListed: "فہرست میں نہیں؟ میزبان کا کوڈ اسکین کریں، یا ان کی اسکرین سے PIN اور پتہ لکھیں۔",
      hotspot: "Wi-Fi نہیں؟ ہاٹ اسپاٹ چلائیں",
      scanBad: "یہ اس نیٹ ورک کی TashZone میز نہیں۔ میزبان سے کوڈ دوبارہ دکھانے کو کہیں۔",
      dismiss: "ٹھیک ہے",
      hostTable: (name: string) => `${name} کی میز`,
      dropped: {
        HOST_GONE: { title: "میز ختم ہو گئی", body: "میزبان کا فون جواب نہیں دے رہا۔ شاید فون سو گیا، Wi-Fi چھوٹ گیا یا TashZone بند ہو گیا۔" },
        KICKED: { title: "میزبان نے آپ کو ہٹا دیا", body: "آپ اس میز پر واپس نہیں آ سکتے۔ دوبارہ کھیلنا ہو تو میزبان سے پوچھیں۔" },
        UNREACHABLE: { title: "میز سے رابطہ نہیں ہو سکا", body: "دیکھیں دونوں ایک ہی Wi-Fi پر ہوں اور میز کھلی ہو۔" },
        UPDATE_REQUIRED: { title: "TashZone کے ورژن مختلف ہیں", body: "پرانے فون پر TashZone اپ ڈیٹ کر کے دوبارہ شامل ہوں۔" },
        TABLE_FULL: { title: "میز بھر گئی", body: "سب جگہیں بھر گئیں، یا میچ شروع ہو چکا ہے۔" },
      },
    },
    pin: {
      title: "PIN ڈالیں",
      lead: "میزبان کے فون پر لکھے 4 ہندسے۔",
      lockout: "کل 10 غلط کوششوں پر میز لاک ہو جاتی ہے۔ پھر میزبان نئی میز کھولے۔",
      label: "میز کا PIN",
      join: "شامل ہوں",
      joining: "شامل ہو رہے ہیں…",
      addressLabel: "میزبان کا پتہ",
      addressHint: "میزبان کی اسکرین پر PIN کے نیچے۔",
      addressFirst: "پہلے میزبان کا پتہ، پھر PIN لکھیں۔",
      tryAgain: "غلط PIN، یا میز لاک ہے۔ میزبان کی اسکرین دیکھیں۔",
      tryLocked: "میزبان کو “میز لاک ہو گئی” دکھے تو وہ نئی میز کھولیں۔",
    },
    hotspot: {
      title: "ہاٹ اسپاٹ میز",
      lead: "راؤٹر نہیں؟ ایک فون نیٹ ورک بنا سکتا ہے۔ ڈیٹا خرچ نہیں ہوتا، بس فون قریب رکھیں۔",
      steps: [
        { t: "میزبان: ہاٹ اسپاٹ آن کریں", b: "ترتیبات ← نیٹ ورک ← ہاٹ اسپاٹ۔ نام اور پاس ورڈ یاد رکھیں۔" },
        { t: "باقی سب: اس سے جڑیں", b: "Wi-Fi ترتیبات میں میزبان کا ہاٹ اسپاٹ چن کر پاس ورڈ ڈالیں۔" },
        { t: "پھر TashZone کھولیں", b: "میزبان “میز لگائیں” دبائے، مہمان “میز میں شامل ہوں”۔" },
      ],
      hostNote: "کچھ فون ہاٹ اسپاٹ کا پتہ ایپس کو نہیں دیتے۔ میزبان کو “Wi-Fi نہیں ملا” دکھے تو عام Wi-Fi لیں یا کسی دوست کو میزبان بنائیں۔",
      privacy: "TashZone نہ نیٹ ورک کا نام پڑھتا ہے، نہ لوکیشن مانگتا ہے۔",
      host: "میز لگائیں",
      join: "میز میں شامل ہوں",
    },
    room: {
      title: "نجی روم",
      lead: "انٹرنیٹ چاہیے۔ کوڈ صرف انہیں دیں جن کے ساتھ کھیلنا ہے۔",
      game: "کھیل",
      preset: "قواعد",
      length: "میچ کی لمبائی",
      players: "کھلاڑی",
      create: "روم بنائیں",
      or: "یا روم میں شامل ہوں",
      codeLabel: "روم کوڈ",
      codeSpoken: (spelled: string) => `روم کوڈ: ${spelled}`,
      codeHint: "کوڈ میں 0، O، 1، I یا L نہیں ہوتے، اس لیے بولنا آسان ہے۔",
      join: "روم میں شامل ہوں",
      quick: "فوری میچ",
      quickHint: "جو انتظار میں ہیں ان سے کھیلیں۔ ذرا دیر میں خالی جگہوں پر بوٹ آ جاتے ہیں۔",
      noGames: "ابھی کوئی کھیل آن لائن نہیں۔",
      working: "جڑ رہے ہیں…",
      modes: { join: "شامل ہوں", create: "بنائیں", quick: "فوری" },
      modesLabel: "کیا کرنا ہے؟",
      summary: (game: string, rules: string, length: string, players?: number) => [game, rules, length, players ? `${players} کھلاڑی` : ""].filter(Boolean).join(" · "),
      lengthValue: (label: string, unit: string) => `${label} ${unit}`,
      setupLabel: (summary: string) => `میز کی ترتیب: ${summary}۔ بدلیں`,
      change: "بدلیں",
      done: "ہو گیا",
      setupTitle: "میز کی ترتیب",
    },
    lobby: {
      title: (code: string) => `روم ${code}`,
      share: "شیئر کریں",
      shareLabel: "کوڈ شیئر کریں",
      shareMessage: (code: string, game: string) => `TashZone پر میری ${game ? `${game} کی ` : ""}میز پر آئیں۔ روم کوڈ: ${code}`,
      hostState: "میزبان",
      ready: "تیار",
      openState: "بوٹ کھیلے گا",
      openName: "خالی جگہ",
      chat: "کھیل شروع ہونے تک صرف فوری چیٹ۔",
      chatOff: "لکھ کر چیٹ بند ہے۔",
      start: "کھیل شروع کریں",
      startBots: "شروع کریں · خالی جگہوں پر بوٹ",
      guestWaiting: "میزبان کے شروع کرنے کا انتظار۔",
      leave: "روم چھوڑیں",
      wifiTitle: "Wi-Fi میز",
      wifiLeave: "میز چھوڑیں",
      wifiGuestChat: "صرف فوری چیٹ۔ Wi-Fi میز پر لکھ کر چیٹ نہیں ہوتی۔",
      connecting: { title: "جڑ رہے ہیں…", body: "آپ کی جگہ لگ رہی ہے۔" },
      leaveTitle: "میز چھوڑیں؟",
      leaveFacts: (wifi: boolean) => [
        { mark: "1", title: "آپ کی جگہ خالی ہو جائے گی", body: "وہاں بوٹ یا کوئی اور کھلاڑی آ سکتا ہے۔" },
        { mark: "2", title: "آپ واپس آ سکتے ہیں", body: wifi ? "میز کھلی ہو تو میزبان کا PIN ڈالیں۔" : "روم کھلا ہو تو یہی کوڈ ڈالیں۔" },
      ],
      stay: "رکیں",
    },
    queue: {
      title: "فوری میچ",
      finding: "کھلاڑی ڈھونڈ رہے ہیں",
      position: (n: number) => `قطار میں آپ کا نمبر ${n} ہے۔`,
      backfill: (s: number) => (s > 0 ? `کوئی نہ آیا تو تقریباً ${s} سیکنڈ میں بوٹ آ جائیں گے۔` : "بوٹ آ رہے ہیں۔"),
      cancel: "منسوخ کریں",
    },
    match: {
      over: "میچ ختم",
      interrupted: "میچ رک گیا",
      interruptedTitle: "سرور اپ ڈیٹ سے رک گیا",
      interruptedBody: "یہ نہ جیت گنی جائے گی نہ ہار۔ روم ابھی کھلا ہے، انہی کھلاڑیوں سے پھر شروع کریں۔",
      winner: "فاتح",
      standings: "نتائج",
      you: "آپ",
      back: "واپس جائیں",
      placed: (place: number, of: number) => `${of} میں سے آپ کا نمبر ${place}`,
      place: (n: number) => `نمبر ${n}`,
      interruptedWifiTitle: "میز بیچ میں رک گئی",
      interruptedWifiBody: "کوئی فاتح نہیں، اس لیے نہ جیت گنی جائے گی نہ ہار۔ میزبان نئی میز کھول سکتا ہے۔",
      leaveTitle: "نتائج چھوڑیں؟",
      leaveFacts: [{ mark: "1", title: "میز بند ہو جائے گی", body: "آپ “کھیلیں” پر واپس جائیں گے۔ دوبارہ کھیلنے کو نئی میز لگائیں۔" }],
      hostLeaveFacts: [{ mark: "1", title: "میز سب کے لیے ختم", body: "یہ میز آپ کے فون پر چل رہی ہے۔ آپ نکلے تو سب مہمانوں کا رابطہ ٹوٹ جائے گا۔" }],
      leave: "چھوڑیں",
      stay: "رکیں",
    },
    table: {
      leave: "چھوڑیں",
      leaveTitle: "میچ چھوڑیں؟",
      stay: "رکیں",
      leaveFacts: (wifi: boolean) => [
        { mark: "1", title: "آپ کی جگہ بوٹ کھیلے گا", body: "میچ ختم ہونے تک بوٹ آپ کی باری کھیلے گا۔" },
        { mark: "2", title: "آپ واپس آ سکتے ہیں", body: wifi ? "میز چلتی رہے تو دوبارہ شامل ہوں۔" : "روم چلتا رہے تو دوبارہ شامل ہوں۔" },
      ],
      hostFacts: [
        { mark: "1", title: "میز سب کے لیے ختم", body: "یہ میز آپ کے فون پر چل رہی ہے۔ بند کرنے سے سب مہمانوں کا رابطہ ٹوٹے گا اور میچ ختم ہوگا۔" },
      ],
      tryAgain: "دوبارہ کوشش کریں",
      openStore: "اسٹور کھولیں",
      leaveNow: "میز چھوڑیں",
    },
    scanner: {
      camera: "کیمرہ۔ میز کے QR کوڈ کی طرف کریں۔",
      point: "کیمرہ میزبان کے QR کوڈ کی طرف کریں۔",
      cancel: "منسوخ کریں",
      off: "TashZone کے لیے کیمرہ بند ہے۔ فون کی ترتیبات میں آن کریں، یا کوڈ لکھیں۔",
      why: "TashZone کیمرہ صرف میز کا QR کوڈ اسکین کرنے کو مانگتا ہے۔ اجازت دیں، یا کوڈ لکھیں۔",
      privacy: "کیمرہ صرف QR کوڈ اسکین کرتا ہے۔ کچھ ریکارڈ یا محفوظ نہیں ہوتا۔",
      settings: "ترتیبات کھولیں",
      scan: "QR کوڈ اسکین کریں",
      qr: "میز میں شامل ہونے کا QR کوڈ",
    },
    seat: (name: string, status: string) => `${name}، ${status}`,
    seatName: (n: number) => `جگہ ${n}`,
    score: { bhabhi: (n: number) => `${n}× Bhabhi`, points: (n: number) => `${n} پوائنٹ` },
    defaultName: "کھلاڑی",
    reconnecting: { title: "دوبارہ جڑ رہے ہیں…", body: "آپ کی جگہ محفوظ ہے۔ دیر لگے تو “دوبارہ کوشش کریں” دبائیں۔" },
    offline: { title: "آپ آف لائن ہیں", body: "رابطہ نہیں ہو سکا۔ انٹرنیٹ یا Wi-Fi دیکھ کر “دوبارہ کوشش کریں” دبائیں۔" },
    paused: { title: "میز رکی ہوئی ہے", body: "سرور کام پورا کر رہا ہے۔ سب گھڑیاں رکی ہیں، پورے وقت سے دوبارہ چلیں گی۔" },
    update: { title: "آن لائن کھیلنے کو اپ ڈیٹ کریں", body: "اس میز کے قواعد نئے ہیں۔ TashZone اپ ڈیٹ کر کے میز دوبارہ کھولیں۔", back: "واپس" },
    locked: {
      header: "والدین نے بند کیا ہے",
      back: "واپس",
      online: { title: "آن لائن روم بند ہیں", body: "والدین PIN سے “والدین کے کنٹرول” میں انہیں آن کر سکتے ہیں۔", action: "والدین کے کنٹرول کھولیں" },
      wifi: { title: "Wi-Fi میزیں بند ہیں", body: "والدین PIN سے “والدین کے کنٹرول” میں انہیں آن کر سکتے ہیں۔", action: "والدین کے کنٹرول کھولیں" },
    },
    pass: {
      lead: "اب فون دیں",
      body: (name: string) => `پتے چھپے ہیں۔ صرف ${name} دیکھیں۔`,
      ready: (name: string) => `میں ${name} ہوں`,
      fallbackName: "اگلا کھلاڑی",
    },
    errors: {
      NETWORK: "سرور سے رابطہ نہیں ہو سکا۔ کنکشن دیکھ کر دوبارہ کوشش کریں۔",
      ROOM_NOT_FOUND: "اس کوڈ کا کوئی کھلا روم نہیں۔ کوڈ دیکھ کر دوبارہ کوشش کریں۔",
      ROOM_FULL: "روم بھر گیا ہے۔",
      ROOM_CLOSED: "روم بند ہو گیا ہے۔",
      ROOM_EXPIRED: "کوڈ کی میعاد ختم۔ خالی روم کچھ دیر بعد بند ہو جاتے ہیں۔",
      ONLINE_ROOMS_OFF: "والدین کے کنٹرول میں آن لائن روم بند ہیں۔",
      ONLINE_DISABLED: "مرمت کی وجہ سے آن لائن کھیل بند ہے۔ کچھ دیر بعد کوشش کریں۔",
      GAME_DISABLED: "یہ کھیل ابھی آن لائن نہیں۔",
      BLOCKED: "آپ اس روم میں شامل نہیں ہو سکتے۔",
      KICKED: "میزبان نے آپ کو روم سے ہٹا دیا۔",
      TICKET_EXPIRED: "وقت پر میز نہیں ملی۔ دوبارہ کوشش کریں۔",
      UNAUTHORIZED: "آن لائن سیشن ختم ہو گیا۔ دوبارہ کوشش کریں۔",
      RATE_LIMITED: "بہت زیادہ کوششیں۔ ذرا رک کر دوبارہ کوشش کریں۔",
      ERROR: "کچھ گڑبڑ ہو گئی۔ دوبارہ کوشش کریں۔",
      NO_WIFI: "Wi-Fi نہیں ملا۔ دوستوں کے Wi-Fi سے جڑیں یا ہاٹ اسپاٹ چلائیں، پھر دوبارہ کوشش کریں۔",
      SERVER_FAILED: "اس فون پر میز نہیں کھل سکی۔ نیٹ ورک والی دوسری ایپس بند کر کے دوبارہ کوشش کریں۔",
      DISCOVERY_FAILED: "قریبی میزیں نہیں دکھ رہیں۔ میزبان کا کوڈ اسکین کریں یا پتہ لکھیں۔",
      UNREACHABLE: "اس میز سے رابطہ نہیں ہو سکا۔ دیکھیں دونوں ایک ہی Wi-Fi پر ہوں اور میز کھلی ہو۔",
      HOST_GONE: "میزبان کے فون سے رابطہ ٹوٹ گیا، اس لیے میز ختم ہو گئی۔",
      WRONG_PIN: "غلط PIN، یا میز لاک ہے۔ میزبان کی اسکرین دیکھیں۔",
      TABLE_FULL: "میز بھر گئی ہے، یا میچ شروع ہو چکا ہے۔",
      UPDATE_REQUIRED: "TashZone کے ورژن مختلف ہیں۔ پرانا فون اپ ڈیٹ کر کے دوبارہ شامل ہوں۔",
      ADDRESS_INVALID: "پتہ درست نہیں۔ میزبان کی اسکرین سے لکھیں، جیسے ⁦192.168.1.20:41234⁩۔",
      QR_INVALID: "یہ اس نیٹ ورک کی TashZone میز نہیں۔",
    },
  },
  hi: {
    hostWifi: {
      title: "एक ही Wi-Fi पर टेबल",
      lead: "इसी Wi-Fi वाले दोस्त PIN या QR कोड से जुड़ें। इंटरनेट की ज़रूरत नहीं।",
      open: "टेबल खोलें",
      opening: "टेबल खुल रही है…",
      pin: "PIN",
      pinHint: "बोलकर बताएँ, या कोड स्कैन करवाएँ।",
      addressLine: (address: string) => `पता: ${address}। टेबल न दिखे तो दोस्त “टेबल से जुड़ें” में इसे डालें।`,
      qrLabel: "जुड़ने का QR कोड। PIN भी अपने-आप भर जाता है।",
      seatsNote: "यह स्क्रीन खुली और फ़ोन जागता रखें। मेहमान सिर्फ़ अपने पत्ते देखते हैं।",
      start: "शुरू करें · खाली सीटों पर बॉट",
      stop: "टेबल बंद करें",
      you: "आप (होस्ट)",
      openSeat: "खाली सीट",
      away: "गैरहाज़िर",
      remove: (name: string) => `${name} को हटाएँ`,
      removed: (name: string) => `${name} को हटा दिया। PIN बदल गया है, नया PIN बताएँ।`,
      seats: "सीटें",
      qrShort: "स्कैन करके जुड़ें",
      locked: { title: "टेबल लॉक हो गई", body: "कई बार गलत PIN। अब कोई नया नहीं जुड़ सकता। नए PIN के लिए टेबल बंद करके फिर खोलें।" },
      ending: { title: "टेबल बंद करें?", body: "सबका कनेक्शन टूट जाएगा और मैच खत्म हो जाएगा।", stay: "खेलते रहें" },
    },
    joinWifi: {
      title: "टेबल से जुड़ें",
      looking: "टेबल ढूँढ रहे हैं…",
      none: "अभी कोई टेबल नहीं। होस्ट इसी Wi-Fi पर टेबल खोलें।",
      nearby: "आस-पास की टेबलें",
      rescan: "फिर से ढूँढें",
      scan: "होस्ट का कोड स्कैन करें",
      enterPin: "PIN और पता डालें",
      notListed: "सूची में नहीं? होस्ट का कोड स्कैन करें, या उनकी स्क्रीन से PIN और पता डालें।",
      hotspot: "Wi-Fi नहीं? हॉटस्पॉट चलाएँ",
      scanBad: "यह इस नेटवर्क की TashZone टेबल नहीं है। होस्ट से कोड फिर दिखाने को कहें।",
      dismiss: "ठीक है",
      hostTable: (name: string) => `${name} की टेबल`,
      dropped: {
        HOST_GONE: { title: "टेबल खत्म हो गई", body: "होस्ट का फ़ोन जवाब नहीं दे रहा। शायद फ़ोन स्लीप में गया, Wi-Fi छूटा या TashZone बंद हुआ।" },
        KICKED: { title: "होस्ट ने आपको हटा दिया", body: "आप इस टेबल पर वापस नहीं आ सकते। फिर खेलना हो तो होस्ट से पूछें।" },
        UNREACHABLE: { title: "टेबल से कनेक्ट नहीं हुआ", body: "देखें कि दोनों एक ही Wi-Fi पर हों और टेबल खुली हो।" },
        UPDATE_REQUIRED: { title: "TashZone के वर्शन अलग हैं", body: "पुराने फ़ोन पर TashZone अपडेट करके फिर जुड़ें।" },
        TABLE_FULL: { title: "टेबल भर गई", body: "सभी सीटें भर गईं, या मैच शुरू हो चुका है।" },
      },
    },
    pin: {
      title: "PIN डालें",
      lead: "होस्ट के फ़ोन पर दिख रहे 4 अंक।",
      lockout: "कुल 10 गलत कोशिशों पर टेबल लॉक हो जाती है। फिर होस्ट नई टेबल खोलें।",
      label: "टेबल PIN",
      join: "जुड़ें",
      joining: "जुड़ रहे हैं…",
      addressLabel: "होस्ट का पता",
      addressHint: "होस्ट की स्क्रीन पर PIN के नीचे।",
      addressFirst: "पहले होस्ट का पता, फिर PIN डालें।",
      tryAgain: "गलत PIN, या टेबल लॉक है। होस्ट की स्क्रीन देखें।",
      tryLocked: "होस्ट को “टेबल लॉक हो गई” दिखे, तो वे नई टेबल खोलें।",
    },
    hotspot: {
      title: "हॉटस्पॉट टेबल",
      lead: "राउटर नहीं? एक फ़ोन से नेटवर्क बन जाता है। डेटा खर्च नहीं होता, बस फ़ोन पास रखें।",
      steps: [
        { t: "होस्ट: हॉटस्पॉट चालू करें", b: "सेटिंग्स → नेटवर्क → हॉटस्पॉट। नाम और पासवर्ड नोट करें।" },
        { t: "बाकी सब: उससे जुड़ें", b: "Wi-Fi सेटिंग्स में होस्ट का हॉटस्पॉट चुनकर पासवर्ड डालें।" },
        { t: "फिर TashZone खोलें", b: "होस्ट “टेबल होस्ट करें” दबाएँ, मेहमान “टेबल से जुड़ें”।" },
      ],
      hostNote: "कुछ फ़ोन हॉटस्पॉट का पता ऐप्स को नहीं देते। होस्ट को “Wi-Fi नहीं मिला” दिखे तो आम Wi-Fi लें या किसी दोस्त को होस्ट बनाएँ।",
      privacy: "TashZone न नेटवर्क का नाम पढ़ता है, न लोकेशन माँगता है।",
      host: "टेबल होस्ट करें",
      join: "टेबल से जुड़ें",
    },
    room: {
      title: "प्राइवेट रूम",
      lead: "इंटरनेट चाहिए। कोड सिर्फ़ उन्हें दें जिनके साथ खेलना है।",
      game: "खेल",
      preset: "नियम",
      length: "मैच की लंबाई",
      players: "खिलाड़ी",
      create: "रूम बनाएँ",
      or: "या रूम से जुड़ें",
      codeLabel: "रूम कोड",
      codeSpoken: (spelled: string) => `रूम कोड: ${spelled}`,
      codeHint: "कोड में 0, O, 1, I या L नहीं होते, इसलिए बोलना आसान है।",
      join: "रूम से जुड़ें",
      quick: "क्विक मैच",
      quickHint: "जो इंतज़ार में हैं, उनसे खेलें। थोड़ी देर में खाली सीटों पर बॉट आ जाते हैं।",
      noGames: "अभी कोई खेल ऑनलाइन नहीं है।",
      working: "कनेक्ट हो रहा है…",
      modes: { join: "जुड़ें", create: "बनाएँ", quick: "क्विक" },
      modesLabel: "क्या करना है?",
      summary: (game: string, rules: string, length: string, players?: number) => [game, rules, length, players ? `${players} खिलाड़ी` : ""].filter(Boolean).join(" · "),
      lengthValue: (label: string, unit: string) => `${label} ${unit}`,
      setupLabel: (summary: string) => `टेबल सेटअप: ${summary}। बदलें`,
      change: "बदलें",
      done: "हो गया",
      setupTitle: "टेबल सेटअप",
    },
    lobby: {
      title: (code: string) => `रूम ${code}`,
      share: "शेयर करें",
      shareLabel: "कोड शेयर करें",
      shareMessage: (code: string, game: string) => `TashZone पर मेरी ${game ? `${game} ` : ""}टेबल पर आइए। रूम कोड: ${code}`,
      hostState: "होस्ट",
      ready: "तैयार",
      openState: "बॉट खेलेगा",
      openName: "खाली सीट",
      chat: "खेल शुरू होने तक सिर्फ़ क्विक चैट।",
      chatOff: "टाइप करके चैट बंद है।",
      start: "खेल शुरू करें",
      startBots: "शुरू करें · खाली सीटों पर बॉट",
      guestWaiting: "होस्ट के शुरू करने का इंतज़ार।",
      leave: "रूम छोड़ें",
      wifiTitle: "Wi-Fi टेबल",
      wifiLeave: "टेबल छोड़ें",
      wifiGuestChat: "सिर्फ़ क्विक चैट। Wi-Fi टेबल पर टाइप करके चैट नहीं होती।",
      connecting: { title: "कनेक्ट हो रहा है…", body: "आपकी सीट लग रही है।" },
      leaveTitle: "टेबल छोड़ें?",
      leaveFacts: (wifi: boolean) => [
        { mark: "1", title: "आपकी सीट खाली हो जाएगी", body: "वहाँ बॉट या कोई और खिलाड़ी आ सकता है।" },
        { mark: "2", title: "आप फिर जुड़ सकते हैं", body: wifi ? "टेबल खुली हो तो होस्ट का PIN डालें।" : "रूम खुला हो तो यही कोड डालें।" },
      ],
      stay: "रुकें",
    },
    queue: {
      title: "क्विक मैच",
      finding: "खिलाड़ी ढूँढ रहे हैं",
      position: (n: number) => `कतार में आपका नंबर ${n} है।`,
      backfill: (s: number) => (s > 0 ? `कोई न आया तो करीब ${s} सेकंड में बॉट आ जाएँगे।` : "बॉट आ रहे हैं।"),
      cancel: "रद्द करें",
    },
    match: {
      over: "मैच खत्म",
      interrupted: "मैच रुक गया",
      interruptedTitle: "सर्वर अपडेट से रुका",
      interruptedBody: "यह न जीत गिनी जाएगी, न हार। रूम अभी खुला है, इन्हीं खिलाड़ियों से फिर शुरू करें।",
      winner: "विजेता",
      standings: "नतीजे",
      you: "आप",
      back: "वापस जाएँ",
      placed: (place: number, of: number) => `${of} में से आपका स्थान ${place}`,
      place: (n: number) => `स्थान ${n}`,
      interruptedWifiTitle: "टेबल बीच में रुक गई",
      interruptedWifiBody: "कोई विजेता नहीं, इसलिए न जीत गिनी जाएगी, न हार। होस्ट नई टेबल खोल सकते हैं।",
      leaveTitle: "नतीजे छोड़ें?",
      leaveFacts: [{ mark: "1", title: "टेबल बंद हो जाएगी", body: "आप “खेलें” पर लौटेंगे। फिर खेलने के लिए नई टेबल शुरू करें।" }],
      hostLeaveFacts: [{ mark: "1", title: "टेबल सबके लिए खत्म", body: "यह टेबल आपके फ़ोन पर चल रही है। आपके जाते ही सब मेहमानों का कनेक्शन टूट जाएगा।" }],
      leave: "छोड़ें",
      stay: "रुकें",
    },
    table: {
      leave: "छोड़ें",
      leaveTitle: "मैच छोड़ें?",
      stay: "रुकें",
      leaveFacts: (wifi: boolean) => [
        { mark: "1", title: "आपकी जगह बॉट खेलेगा", body: "मैच खत्म होने तक बॉट आपकी बारी खेलेगा।" },
        { mark: "2", title: "आप लौट सकते हैं", body: wifi ? "टेबल चलती रहे तो फिर जुड़ जाएँ।" : "रूम चलता रहे तो फिर जुड़ जाएँ।" },
      ],
      hostFacts: [
        { mark: "1", title: "टेबल सबके लिए खत्म", body: "यह टेबल आपके फ़ोन पर चल रही है। बंद करने से सबका कनेक्शन टूटेगा और मैच खत्म होगा।" },
      ],
      tryAgain: "फिर कोशिश करें",
      openStore: "स्टोर खोलें",
      leaveNow: "टेबल छोड़ें",
    },
    scanner: {
      camera: "कैमरा। टेबल के QR कोड की ओर करें।",
      point: "कैमरा होस्ट के QR कोड की ओर करें।",
      cancel: "रद्द करें",
      off: "TashZone के लिए कैमरा बंद है। फ़ोन की सेटिंग्स में चालू करें, या कोड डालें।",
      why: "TashZone को कैमरा सिर्फ़ टेबल का QR कोड स्कैन करने के लिए चाहिए। अनुमति दें, या कोड डालें।",
      privacy: "कैमरा सिर्फ़ QR कोड स्कैन करता है। कुछ भी रिकॉर्ड या सेव नहीं होता।",
      settings: "सेटिंग्स खोलें",
      scan: "QR कोड स्कैन करें",
      qr: "टेबल से जुड़ने का QR कोड",
    },
    seat: (name: string, status: string) => `${name}, ${status}`,
    seatName: (n: number) => `सीट ${n}`,
    score: { bhabhi: (n: number) => `${n}× Bhabhi`, points: (n: number) => `${n} अंक` },
    defaultName: "खिलाड़ी",
    reconnecting: { title: "फिर से कनेक्ट हो रहा है…", body: "आपकी सीट सुरक्षित है। देर लगे तो “फिर कोशिश करें” दबाएँ।" },
    offline: { title: "आप ऑफ़लाइन हैं", body: "कनेक्ट नहीं हो पाया। इंटरनेट या Wi-Fi देखकर “फिर कोशिश करें” दबाएँ।" },
    paused: { title: "टेबल रुकी है", body: "सर्वर काम निपटा रहा है। सब घड़ियाँ रुकी हैं, पूरे समय से फिर चलेंगी।" },
    update: { title: "ऑनलाइन खेलने के लिए अपडेट करें", body: "इस टेबल के नियम नए हैं। TashZone अपडेट करके टेबल फिर खोलें।", back: "वापस" },
    locked: {
      header: "माता-पिता ने बंद किया है",
      back: "वापस",
      online: { title: "ऑनलाइन रूम बंद हैं", body: "माता-पिता PIN डालकर पैरेंट कंट्रोल में इन्हें चालू कर सकते हैं।", action: "पैरेंट कंट्रोल खोलें" },
      wifi: { title: "Wi-Fi टेबलें बंद हैं", body: "माता-पिता PIN डालकर पैरेंट कंट्रोल में इन्हें चालू कर सकते हैं।", action: "पैरेंट कंट्रोल खोलें" },
    },
    pass: {
      lead: "अब फ़ोन दें",
      body: (name: string) => `पत्ते छिपे हैं। सिर्फ़ ${name} देखें।`,
      ready: (name: string) => `मैं ${name} हूँ`,
      fallbackName: "अगला खिलाड़ी",
    },
    errors: {
      NETWORK: "सर्वर से कनेक्ट नहीं हुआ। कनेक्शन देखकर फिर कोशिश करें।",
      ROOM_NOT_FOUND: "इस कोड का कोई खुला रूम नहीं। कोड देखकर फिर कोशिश करें।",
      ROOM_FULL: "रूम भर गया है।",
      ROOM_CLOSED: "रूम बंद हो गया है।",
      ROOM_EXPIRED: "कोड की मियाद खत्म। खाली रूम कुछ देर में बंद हो जाते हैं।",
      ONLINE_ROOMS_OFF: "पैरेंट कंट्रोल में ऑनलाइन रूम बंद हैं।",
      ONLINE_DISABLED: "मेंटेनेंस के लिए ऑनलाइन खेल बंद है। बाद में कोशिश करें।",
      GAME_DISABLED: "यह खेल अभी ऑनलाइन नहीं है।",
      BLOCKED: "आप इस रूम से नहीं जुड़ सकते।",
      KICKED: "होस्ट ने आपको रूम से हटा दिया।",
      TICKET_EXPIRED: "समय पर टेबल नहीं मिली। फिर कोशिश करें।",
      UNAUTHORIZED: "ऑनलाइन सेशन खत्म हो गया। फिर कोशिश करें।",
      RATE_LIMITED: "बहुत ज़्यादा कोशिशें। थोड़ा रुककर फिर कोशिश करें।",
      ERROR: "कुछ गड़बड़ हो गई। फिर कोशिश करें।",
      NO_WIFI: "Wi-Fi नहीं मिला। दोस्तों के Wi-Fi से जुड़ें या हॉटस्पॉट चलाएँ, फिर कोशिश करें।",
      SERVER_FAILED: "इस फ़ोन पर टेबल नहीं खुली। नेटवर्क वाले दूसरे ऐप बंद करके फिर कोशिश करें।",
      DISCOVERY_FAILED: "आस-पास की टेबलें नहीं दिख रहीं। होस्ट का कोड स्कैन करें या पता डालें।",
      UNREACHABLE: "उस टेबल से कनेक्ट नहीं हुआ। देखें कि दोनों एक ही Wi-Fi पर हों और टेबल खुली हो।",
      HOST_GONE: "होस्ट के फ़ोन से कनेक्शन टूट गया, इसलिए टेबल खत्म हो गई।",
      WRONG_PIN: "गलत PIN, या टेबल लॉक है। होस्ट की स्क्रीन देखें।",
      TABLE_FULL: "टेबल भर गई है, या मैच शुरू हो चुका है।",
      UPDATE_REQUIRED: "TashZone के वर्शन अलग हैं। पुराना फ़ोन अपडेट करके फिर जुड़ें।",
      ADDRESS_INVALID: "पता सही नहीं है। होस्ट की स्क्रीन से डालें, जैसे 192.168.1.20:41234।",
      QR_INVALID: "यह इस नेटवर्क की TashZone टेबल नहीं है।",
    },
  },
  ne: {
    hostWifi: {
      title: "एउटै Wi-Fi मा टेबल",
      lead: "यही Wi-Fi का साथीहरू PIN वा QR कोडले जोडिन्छन्। इन्टरनेट चाहिँदैन।",
      open: "टेबल खोल्नुहोस्",
      opening: "टेबल खुल्दै छ…",
      pin: "PIN",
      pinHint: "बोलेर भन्नुहोस्, वा कोड स्क्यान गर्न दिनुहोस्।",
      addressLine: (address: string) => `ठेगाना: ${address}। टेबल नदेखे साथीले “टेबलमा जोडिनुहोस्” मा यो हाल्न सक्छन्।`,
      qrLabel: "जोडिने QR कोड। PIN पनि आफैँ भरिन्छ।",
      seatsNote: "यो स्क्रिन खुला र फोन जागा राख्नुहोस्। पाहुनाले आफ्नै पत्ती मात्र देख्छन्।",
      start: "सुरु गर्नुहोस् · खाली सिटमा बोट",
      stop: "टेबल बन्द गर्नुहोस्",
      you: "तपाईं (होस्ट)",
      openSeat: "खाली सिट",
      away: "अनुपस्थित",
      remove: (name: string) => `${name} लाई हटाउनुहोस्`,
      removed: (name: string) => `${name} लाई हटाइयो। PIN फेरियो, नयाँ PIN दिनुहोस्।`,
      seats: "सिटहरू",
      qrShort: "स्क्यान गरेर जोडिनुहोस्",
      locked: { title: "टेबल लक भयो", body: "धेरै पटक गलत PIN। अब नयाँ कोही जोडिन सक्दैन। नयाँ PIN का लागि टेबल बन्द गरेर फेरि खोल्नुहोस्।" },
      ending: { title: "टेबल बन्द गर्ने?", body: "सबैको जडान टुट्छ र म्याच सकिन्छ।", stay: "खेलिरहनुहोस्" },
    },
    joinWifi: {
      title: "टेबलमा जोडिनुहोस्",
      looking: "टेबल खोज्दै…",
      none: "अहिलेसम्म टेबल छैन। होस्टले यही Wi-Fi मा टेबल खोल्नुपर्छ।",
      nearby: "नजिकका टेबल",
      rescan: "फेरि खोज्नुहोस्",
      scan: "होस्टको कोड स्क्यान गर्नुहोस्",
      enterPin: "PIN र ठेगाना हाल्नुहोस्",
      notListed: "सूचीमा छैन? होस्टको कोड स्क्यान गर्नुहोस्, वा उहाँको स्क्रिनबाट PIN र ठेगाना हाल्नुहोस्।",
      hotspot: "Wi-Fi छैन? हटस्पट चलाउनुहोस्",
      scanBad: "यो यस नेटवर्कको TashZone टेबल होइन। होस्टलाई कोड फेरि देखाउन भन्नुहोस्।",
      dismiss: "ठिक छ",
      hostTable: (name: string) => `${name} को टेबल`,
      dropped: {
        HOST_GONE: { title: "टेबल सकियो", body: "होस्टको फोनले जवाफ दिएन। फोन निदायो, Wi-Fi छुट्यो वा TashZone बन्द भयो होला।" },
        KICKED: { title: "होस्टले तपाईंलाई हटाउनुभयो", body: "यो टेबलमा फर्कन मिल्दैन। फेरि खेल्न होस्टलाई सोध्नुहोस्।" },
        UNREACHABLE: { title: "टेबलमा जोडिन सकिएन", body: "दुवै एउटै Wi-Fi मा हुनुहुन्छ र टेबल खुला छ, जाँच्नुहोस्।" },
        UPDATE_REQUIRED: { title: "TashZone को संस्करण फरक छ", body: "पुरानो फोनमा TashZone अपडेट गरेर फेरि जोडिनुहोस्।" },
        TABLE_FULL: { title: "टेबल भरियो", body: "सबै सिट भरिए, वा म्याच सुरु भइसक्यो।" },
      },
    },
    pin: {
      title: "PIN हाल्नुहोस्",
      lead: "होस्टको फोनमा देखिएका 4 अङ्क।",
      lockout: "जम्मा 10 पटक गलत भए टेबल लक हुन्छ। त्यसपछि होस्टले नयाँ टेबल खोल्नुपर्छ।",
      label: "टेबल PIN",
      join: "जोडिनुहोस्",
      joining: "जोडिँदै…",
      addressLabel: "होस्टको ठेगाना",
      addressHint: "होस्टको स्क्रिनमा PIN मुनि।",
      addressFirst: "पहिले होस्टको ठेगाना, अनि PIN हाल्नुहोस्।",
      tryAgain: "PIN मिलेन, वा टेबल लक छ। होस्टको स्क्रिन हेर्नुहोस्।",
      tryLocked: "होस्टले “टेबल लक भयो” देखे नयाँ टेबल खोल्नुपर्छ।",
    },
    hotspot: {
      title: "हटस्पट टेबल",
      lead: "राउटर छैन? एउटा फोनले नेटवर्क बनाउँछ। डाटा खर्च हुँदैन, फोन नजिकै राख्नुहोस्।",
      steps: [
        { t: "होस्ट: हटस्पट खोल्नुहोस्", b: "सेटिङ → नेटवर्क → हटस्पट। नाम र पासवर्ड टिप्नुहोस्।" },
        { t: "अरू सबै: त्यसमा जोडिनुहोस्", b: "Wi-Fi सेटिङमा होस्टको हटस्पट छानेर पासवर्ड हाल्नुहोस्।" },
        { t: "अनि TashZone खोल्नुहोस्", b: "होस्टले “टेबल होस्ट गर्नुहोस्”, पाहुनाले “टेबलमा जोडिनुहोस्” थिच्ने।" },
      ],
      hostNote: "केही फोनले हटस्पटको ठेगाना एपलाई दिँदैनन्। होस्टले “Wi-Fi भेटिएन” देखे साझा Wi-Fi चलाउनुहोस् वा अर्को साथीलाई होस्ट बनाउनुहोस्।",
      privacy: "TashZone ले नेटवर्कको नाम पढ्दैन, लोकेसन पनि माग्दैन।",
      host: "टेबल होस्ट गर्नुहोस्",
      join: "टेबलमा जोडिनुहोस्",
    },
    room: {
      title: "निजी रुम",
      lead: "इन्टरनेट चाहिन्छ। सँगै खेल्नेलाई मात्र कोड दिनुहोस्।",
      game: "खेल",
      preset: "नियम",
      length: "म्याचको लम्बाइ",
      players: "खेलाडी",
      create: "रुम बनाउनुहोस्",
      or: "वा रुममा जोडिनुहोस्",
      codeLabel: "रुम कोड",
      codeSpoken: (spelled: string) => `रुम कोड: ${spelled}`,
      codeHint: "कोडमा 0, O, 1, I वा L हुँदैन, त्यसैले बोल्न सजिलो छ।",
      join: "रुममा जोडिनुहोस्",
      quick: "छिटो म्याच",
      quickHint: "पर्खिरहेकासँग खेल्नुहोस्। केही बेरमा खाली सिटमा बोट आउँछन्।",
      noGames: "अहिले कुनै खेल अनलाइन छैन।",
      working: "जोडिँदै…",
      modes: { join: "जोडिने", create: "बनाउने", quick: "छिटो" },
      modesLabel: "के गर्ने?",
      summary: (game: string, rules: string, length: string, players?: number) => [game, rules, length, players ? `${players} खेलाडी` : ""].filter(Boolean).join(" · "),
      lengthValue: (label: string, unit: string) => `${label} ${unit}`,
      setupLabel: (summary: string) => `टेबल सेटअप: ${summary}। बदल्नुहोस्`,
      change: "बदल्नुहोस्",
      done: "भयो",
      setupTitle: "टेबल सेटअप",
    },
    lobby: {
      title: (code: string) => `रुम ${code}`,
      share: "सेयर गर्नुहोस्",
      shareLabel: "कोड सेयर गर्नुहोस्",
      shareMessage: (code: string, game: string) => `TashZone मा मेरो ${game ? `${game} ` : ""}टेबलमा आउनुहोस्। रुम कोड: ${code}`,
      hostState: "होस्ट",
      ready: "तयार",
      openState: "बोट खेल्छ",
      openName: "खाली सिट",
      chat: "खेल सुरु नभएसम्म छिटो च्याट मात्र।",
      chatOff: "टाइप गरेर च्याट बन्द छ।",
      start: "खेल सुरु गर्नुहोस्",
      startBots: "सुरु गर्नुहोस् · खाली सिटमा बोट",
      guestWaiting: "होस्टले सुरु गर्ने पर्खाइमा।",
      leave: "रुम छोड्नुहोस्",
      wifiTitle: "Wi-Fi टेबल",
      wifiLeave: "टेबल छोड्नुहोस्",
      wifiGuestChat: "छिटो च्याट मात्र। Wi-Fi टेबलमा टाइप गरेर च्याट हुँदैन।",
      connecting: { title: "जोडिँदै…", body: "तपाईंको सिट मिलाउँदै।" },
      leaveTitle: "टेबल छोड्ने?",
      leaveFacts: (wifi: boolean) => [
        { mark: "1", title: "तपाईंको सिट खाली हुन्छ", body: "त्यहाँ बोट वा अर्को खेलाडी बस्न सक्छ।" },
        { mark: "2", title: "फेरि जोडिन सक्नुहुन्छ", body: wifi ? "टेबल खुला रहुन्जेल होस्टको PIN हाल्नुहोस्।" : "रुम खुला रहुन्जेल यही कोड हाल्नुहोस्।" },
      ],
      stay: "बस्नुहोस्",
    },
    queue: {
      title: "छिटो म्याच",
      finding: "खेलाडी खोज्दै",
      position: (n: number) => `लाइनमा तपाईं ${n} नम्बरमा।`,
      backfill: (s: number) => (s > 0 ? `कोही नआए करिब ${s} सेकेन्डमा बोट आउँछन्।` : "बोट आउँदै छन्।"),
      cancel: "रद्द गर्नुहोस्",
    },
    match: {
      over: "म्याच सकियो",
      interrupted: "म्याच रोकियो",
      interruptedTitle: "सर्भर अपडेटले रोकियो",
      interruptedBody: "यो न जितमा गनिन्छ न हारमा। रुम अझै खुला छ, उही खेलाडीसँग फेरि सुरु गर्नुहोस्।",
      winner: "विजेता",
      standings: "नतिजा",
      you: "तपाईं",
      back: "फर्कनुहोस्",
      placed: (place: number, of: number) => `${of} मध्ये तपाईंको स्थान ${place}`,
      place: (n: number) => `स्थान ${n}`,
      interruptedWifiTitle: "टेबल बीचमै रोकियो",
      interruptedWifiBody: "विजेता छैन, त्यसैले न जितमा गनिन्छ न हारमा। होस्टले नयाँ टेबल खोल्न सक्नुहुन्छ।",
      leaveTitle: "नतिजा छोड्ने?",
      leaveFacts: [{ mark: "1", title: "टेबल बन्द हुन्छ", body: "तपाईं “खेल्नुहोस्” मा फर्कनुहुन्छ। फेरि खेल्न नयाँ टेबल सुरु गर्नुहोस्।" }],
      hostLeaveFacts: [{ mark: "1", title: "टेबल सबैका लागि सकिन्छ", body: "यो टेबल तपाईंको फोनमा चल्छ। तपाईं निस्किनासाथ सबै पाहुनाको जडान टुट्छ।" }],
      leave: "छोड्नुहोस्",
      stay: "बस्नुहोस्",
    },
    table: {
      leave: "छोड्नुहोस्",
      leaveTitle: "म्याच छोड्ने?",
      stay: "बस्नुहोस्",
      leaveFacts: (wifi: boolean) => [
        { mark: "1", title: "तपाईंको ठाउँमा बोट खेल्छ", body: "म्याच नसकिउन्जेल बोटले तपाईंको पालो खेल्छ।" },
        { mark: "2", title: "फर्कन सक्नुहुन्छ", body: wifi ? "टेबल चलुन्जेल फेरि जोडिनुहोस्।" : "रुम चलुन्जेल फेरि जोडिनुहोस्।" },
      ],
      hostFacts: [
        { mark: "1", title: "टेबल सबैका लागि सकिन्छ", body: "यो टेबल तपाईंको फोनमा चल्छ। बन्द गरे सबैको जडान टुट्छ र म्याच सकिन्छ।" },
      ],
      tryAgain: "फेरि प्रयास गर्नुहोस्",
      openStore: "स्टोर खोल्नुहोस्",
      leaveNow: "टेबल छोड्नुहोस्",
    },
    scanner: {
      camera: "क्यामेरा। टेबलको QR कोडतिर फर्काउनुहोस्।",
      point: "क्यामेरा होस्टको QR कोडतिर फर्काउनुहोस्।",
      cancel: "रद्द गर्नुहोस्",
      off: "TashZone का लागि क्यामेरा बन्द छ। फोनको सेटिङमा खोल्नुहोस्, वा कोड टाइप गर्नुहोस्।",
      why: "TashZone लाई क्यामेरा टेबलको QR कोड स्क्यान गर्न मात्र चाहिन्छ। अनुमति दिनुहोस्, वा कोड टाइप गर्नुहोस्।",
      privacy: "क्यामेराले QR कोड मात्र स्क्यान गर्छ। केही रेकर्ड वा सेभ हुँदैन।",
      settings: "सेटिङ खोल्नुहोस्",
      scan: "QR कोड स्क्यान गर्नुहोस्",
      qr: "टेबलमा जोडिने QR कोड",
    },
    seat: (name: string, status: string) => `${name}, ${status}`,
    seatName: (n: number) => `सिट ${n}`,
    score: { bhabhi: (n: number) => `${n}× Bhabhi`, points: (n: number) => `${n} अङ्क` },
    defaultName: "खेलाडी",
    reconnecting: { title: "फेरि जोडिँदै…", body: "तपाईंको सिट सुरक्षित छ। ढिलो भए “फेरि प्रयास गर्नुहोस्” थिच्नुहोस्।" },
    offline: { title: "तपाईं अफलाइन हुनुहुन्छ", body: "जडान भएन। इन्टरनेट वा Wi-Fi जाँचेर “फेरि प्रयास गर्नुहोस्” थिच्नुहोस्।" },
    paused: { title: "टेबल रोकिएको छ", body: "सर्भरले काम सक्दै छ। सबै घडी रोकिएका छन्, पूरा समयबाट फेरि चल्छन्।" },
    update: { title: "अनलाइन खेल्न अपडेट गर्नुहोस्", body: "यो टेबलका नियम नयाँ छन्। TashZone अपडेट गरेर टेबल फेरि खोल्नुहोस्।", back: "फर्कनुहोस्" },
    locked: {
      header: "अभिभावकले बन्द गर्नुभएको",
      back: "फर्कनुहोस्",
      online: { title: "अनलाइन रुम बन्द छन्", body: "अभिभावकले PIN हालेर अभिभावक नियन्त्रणबाट फेरि खोल्न सक्नुहुन्छ।", action: "अभिभावक नियन्त्रण खोल्नुहोस्" },
      wifi: { title: "Wi-Fi टेबल बन्द छन्", body: "अभिभावकले PIN हालेर अभिभावक नियन्त्रणबाट फेरि खोल्न सक्नुहुन्छ।", action: "अभिभावक नियन्त्रण खोल्नुहोस्" },
    },
    pass: {
      lead: "अब फोन दिनुहोस्",
      body: (name: string) => `पत्ती लुकाइएका छन्। ${name} ले मात्र हेर्नुहोस्।`,
      ready: (name: string) => `म ${name} हुँ`,
      fallbackName: "अर्को खेलाडी",
    },
    errors: {
      NETWORK: "सर्भरमा जोडिन सकिएन। जडान जाँचेर फेरि प्रयास गर्नुहोस्।",
      ROOM_NOT_FOUND: "यो कोडको कुनै खुला रुम छैन। कोड जाँचेर फेरि प्रयास गर्नुहोस्।",
      ROOM_FULL: "रुम भरियो।",
      ROOM_CLOSED: "रुम बन्द भयो।",
      ROOM_EXPIRED: "कोडको म्याद सकियो। खाली रुम केही बेरमा बन्द हुन्छन्।",
      ONLINE_ROOMS_OFF: "अभिभावक नियन्त्रणमा अनलाइन रुम बन्द छन्।",
      ONLINE_DISABLED: "मर्मतका लागि अनलाइन खेल बन्द छ। पछि प्रयास गर्नुहोस्।",
      GAME_DISABLED: "यो खेल अहिले अनलाइन छैन।",
      BLOCKED: "तपाईं यो रुममा जोडिन सक्नुहुन्न।",
      KICKED: "होस्टले तपाईंलाई रुमबाट हटाउनुभयो।",
      TICKET_EXPIRED: "समयमै टेबल भेटिएन। फेरि प्रयास गर्नुहोस्।",
      UNAUTHORIZED: "अनलाइन सत्र सकियो। फेरि प्रयास गर्नुहोस्।",
      RATE_LIMITED: "धेरै प्रयास भयो। एकछिन पर्खेर फेरि प्रयास गर्नुहोस्।",
      ERROR: "केही गडबड भयो। फेरि प्रयास गर्नुहोस्।",
      NO_WIFI: "Wi-Fi भेटिएन। साथीहरूको Wi-Fi मा जोडिनुहोस् वा हटस्पट चलाउनुहोस्, अनि फेरि प्रयास गर्नुहोस्।",
      SERVER_FAILED: "यो फोनमा टेबल खुलेन। नेटवर्क चलाउने अरू एप बन्द गरेर फेरि प्रयास गर्नुहोस्।",
      DISCOVERY_FAILED: "नजिकका टेबल देखिँदैनन्। होस्टको कोड स्क्यान गर्नुहोस् वा ठेगाना हाल्नुहोस्।",
      UNREACHABLE: "त्यो टेबलमा जोडिन सकिएन। दुवै एउटै Wi-Fi मा हुनुहुन्छ र टेबल खुला छ, जाँच्नुहोस्।",
      HOST_GONE: "होस्टको फोनसँग जडान टुट्यो, त्यसैले टेबल सकियो।",
      WRONG_PIN: "PIN मिलेन, वा टेबल लक छ। होस्टको स्क्रिन हेर्नुहोस्।",
      TABLE_FULL: "टेबल भरियो, वा म्याच सुरु भइसक्यो।",
      UPDATE_REQUIRED: "TashZone को संस्करण फरक छ। पुरानो फोन अपडेट गरेर फेरि जोडिनुहोस्।",
      ADDRESS_INVALID: "ठेगाना मिलेन। होस्टको स्क्रिनबाट हाल्नुहोस्, जस्तै 192.168.1.20:41234।",
      QR_INVALID: "यो यस नेटवर्कको TashZone टेबल होइन।",
    },
  },
  bn: {
    hostWifi: {
      title: "একই Wi-Fi-তে টেবিল",
      lead: "এই Wi-Fi-র বন্ধুরা PIN বা QR কোড দিয়ে যোগ দিন। ইন্টারনেট লাগবে না।",
      open: "টেবিল খুলুন",
      opening: "টেবিল খুলছে…",
      pin: "PIN",
      pinHint: "মুখে বলুন, বা কোড স্ক্যান করতে দিন।",
      addressLine: (address: string) => `ঠিকানা: ${address}। টেবিল না দেখলে বন্ধুরা “টেবিলে যোগ দিন”-এ এটা লিখুন।`,
      qrLabel: "যোগ দেওয়ার QR কোড। PIN-ও নিজে থেকে বসে যায়।",
      seatsNote: "স্ক্রিন খোলা রাখুন, ফোন যেন ঘুমিয়ে না পড়ে। অতিথিরা শুধু নিজের তাস দেখেন।",
      start: "শুরু করুন · খালি আসনে বট",
      stop: "টেবিল বন্ধ করুন",
      you: "আপনি (হোস্ট)",
      openSeat: "খালি আসন",
      away: "অনুপস্থিত",
      remove: (name: string) => `${name}-কে সরান`,
      removed: (name: string) => `${name}-কে সরানো হয়েছে। PIN বদলেছে, নতুন PIN জানান।`,
      seats: "আসন",
      qrShort: "স্ক্যান করে যোগ দিন",
      locked: { title: "টেবিল লক হয়েছে", body: "অনেকবার ভুল PIN। নতুন কেউ আর যোগ দিতে পারবেন না। নতুন PIN পেতে টেবিল বন্ধ করে আবার খুলুন।" },
      ending: { title: "টেবিল বন্ধ করবেন?", body: "সবার সংযোগ কেটে যাবে, ম্যাচও শেষ হবে।", stay: "খেলতে থাকুন" },
    },
    joinWifi: {
      title: "টেবিলে যোগ দিন",
      looking: "টেবিল খোঁজা হচ্ছে…",
      none: "এখনও কোনো টেবিল নেই। হোস্টকে এই Wi-Fi-তেই টেবিল খুলতে হবে।",
      nearby: "কাছের টেবিল",
      rescan: "আবার খুঁজুন",
      scan: "হোস্টের কোড স্ক্যান করুন",
      enterPin: "PIN আর ঠিকানা দিন",
      notListed: "তালিকায় নেই? হোস্টের কোড স্ক্যান করুন, বা তাঁর স্ক্রিন দেখে PIN আর ঠিকানা দিন।",
      hotspot: "Wi-Fi নেই? হটস্পট চালান",
      scanBad: "এটি এই নেটওয়ার্কের TashZone টেবিল নয়। হোস্টকে কোডটি আবার দেখাতে বলুন।",
      dismiss: "ঠিক আছে",
      hostTable: (name: string) => `${name}-এর টেবিল`,
      dropped: {
        HOST_GONE: { title: "টেবিল শেষ", body: "হোস্টের ফোন সাড়া দিচ্ছে না। হয়তো ঘুমিয়ে পড়েছে, Wi-Fi ছেড়েছে বা TashZone বন্ধ হয়েছে।" },
        KICKED: { title: "হোস্ট আপনাকে সরিয়েছেন", body: "এই টেবিলে আর ফিরতে পারবেন না। আবার খেলতে হোস্টকে বলুন।" },
        UNREACHABLE: { title: "টেবিলে যুক্ত হওয়া যায়নি", body: "দুজনেই একই Wi-Fi-তে আছেন আর টেবিল খোলা কি না দেখুন।" },
        UPDATE_REQUIRED: { title: "TashZone-এর সংস্করণ আলাদা", body: "পুরোনো ফোনে TashZone আপডেট করে আবার যোগ দিন।" },
        TABLE_FULL: { title: "টেবিল ভর্তি", body: "সব আসন ভরা, বা ম্যাচ শুরু হয়ে গেছে।" },
      },
    },
    pin: {
      title: "PIN দিন",
      lead: "হোস্টের ফোনে দেখানো 4টি সংখ্যা।",
      lockout: "সব মিলিয়ে 10 বার ভুল হলে টেবিল লক হয়। তখন হোস্টকে নতুন টেবিল খুলতে হবে।",
      label: "টেবিলের PIN",
      join: "যোগ দিন",
      joining: "যোগ দেওয়া হচ্ছে…",
      addressLabel: "হোস্টের ঠিকানা",
      addressHint: "হোস্টের স্ক্রিনে PIN-এর নিচে।",
      addressFirst: "আগে হোস্টের ঠিকানা, তারপর PIN দিন।",
      tryAgain: "ভুল PIN, বা টেবিল লক। হোস্টের স্ক্রিন দেখুন।",
      tryLocked: "হোস্ট “টেবিল লক হয়েছে” দেখলে নতুন টেবিল খুলতে হবে।",
    },
    hotspot: {
      title: "হটস্পট টেবিল",
      lead: "রাউটার নেই? একটা ফোনই নেটওয়ার্ক বানাতে পারে। ডেটা খরচ হয় না, শুধু ফোনগুলো কাছে রাখুন।",
      steps: [
        { t: "হোস্ট: হটস্পট চালু করুন", b: "সেটিংস → নেটওয়ার্ক → হটস্পট। নাম আর পাসওয়ার্ড মনে রাখুন।" },
        { t: "বাকিরা: তাতে যুক্ত হন", b: "Wi-Fi সেটিংসে হোস্টের হটস্পট বেছে পাসওয়ার্ড দিন।" },
        { t: "তারপর TashZone খুলুন", b: "হোস্ট চাপবেন “টেবিল হোস্ট করুন”, অতিথিরা “টেবিলে যোগ দিন”।" },
      ],
      hostNote: "কিছু ফোন হটস্পটের ঠিকানা অ্যাপকে দেয় না। হোস্ট “Wi-Fi পাওয়া যায়নি” দেখলে সাধারণ Wi-Fi নিন, বা অন্য বন্ধুকে হোস্ট করতে দিন।",
      privacy: "TashZone আপনার নেটওয়ার্কের নাম পড়ে না, লোকেশনের অনুমতিও চায় না।",
      host: "টেবিল হোস্ট করুন",
      join: "টেবিলে যোগ দিন",
    },
    room: {
      title: "প্রাইভেট রুম",
      lead: "ইন্টারনেট লাগবে। যাঁদের সাথে খেলবেন, শুধু তাঁদের কোড দিন।",
      game: "খেলা",
      preset: "নিয়ম",
      length: "ম্যাচের দৈর্ঘ্য",
      players: "খেলোয়াড়",
      create: "রুম বানান",
      or: "বা রুমে যোগ দিন",
      codeLabel: "রুম কোড",
      codeSpoken: (spelled: string) => `রুম কোড: ${spelled}`,
      codeHint: "কোডে 0, O, 1, I বা L থাকে না, তাই বলা সহজ।",
      join: "রুমে যোগ দিন",
      quick: "কুইক ম্যাচ",
      quickHint: "যাঁরা অপেক্ষায়, তাঁদের সাথে খেলুন। একটু পরে খালি আসনে বট আসে।",
      noGames: "এখন কোনো খেলা অনলাইনে নেই।",
      working: "যুক্ত হচ্ছে…",
      modes: { join: "যোগ দিন", create: "বানান", quick: "কুইক" },
      modesLabel: "কী করতে চান?",
      summary: (game: string, rules: string, length: string, players?: number) => [game, rules, length, players ? `${players} জন` : ""].filter(Boolean).join(" · "),
      lengthValue: (label: string, unit: string) => `${label} ${unit}`,
      setupLabel: (summary: string) => `টেবিল সেটআপ: ${summary}। বদলান`,
      change: "বদলান",
      done: "হয়ে গেছে",
      setupTitle: "টেবিল সেটআপ",
    },
    lobby: {
      title: (code: string) => `রুম ${code}`,
      share: "শেয়ার করুন",
      shareLabel: "কোড শেয়ার করুন",
      shareMessage: (code: string, game: string) => `TashZone-এ আমার ${game ? `${game} ` : ""}টেবিলে আসুন। রুম কোড: ${code}`,
      hostState: "হোস্ট",
      ready: "প্রস্তুত",
      openState: "বট খেলবে",
      openName: "খালি আসন",
      chat: "খেলা শুরুর আগে শুধু কুইক চ্যাট।",
      chatOff: "লিখে চ্যাট বন্ধ।",
      start: "খেলা শুরু করুন",
      startBots: "শুরু করুন · খালি আসনে বট",
      guestWaiting: "হোস্টের শুরু করার অপেক্ষা।",
      leave: "রুম ছাড়ুন",
      wifiTitle: "Wi-Fi টেবিল",
      wifiLeave: "টেবিল ছাড়ুন",
      wifiGuestChat: "শুধু কুইক চ্যাট। Wi-Fi টেবিলে লিখে চ্যাট হয় না।",
      connecting: { title: "যুক্ত হচ্ছে…", body: "আপনার আসন ঠিক করা হচ্ছে।" },
      leaveTitle: "টেবিল ছাড়বেন?",
      leaveFacts: (wifi: boolean) => [
        { mark: "1", title: "আপনার আসন খালি হবে", body: "সেখানে বট বা অন্য কেউ বসতে পারে।" },
        { mark: "2", title: "আবার যোগ দিতে পারবেন", body: wifi ? "টেবিল খোলা থাকলে হোস্টের PIN দিন।" : "রুম খোলা থাকলে একই কোড দিন।" },
      ],
      stay: "থাকুন",
    },
    queue: {
      title: "কুইক ম্যাচ",
      finding: "খেলোয়াড় খোঁজা হচ্ছে",
      position: (n: number) => `লাইনে আপনি ${n} নম্বরে।`,
      backfill: (s: number) => (s > 0 ? `কেউ না এলে প্রায় ${s} সেকেন্ডে বট আসবে।` : "বট আসছে।"),
      cancel: "বাতিল",
    },
    match: {
      over: "ম্যাচ শেষ",
      interrupted: "ম্যাচ থেমে গেছে",
      interruptedTitle: "সার্ভার আপডেটে থেমেছে",
      interruptedBody: "জয় বা হার কোনোটাই ধরা হবে না। রুম এখনও খোলা, একই খেলোয়াড়দের নিয়ে আবার শুরু করুন।",
      winner: "বিজয়ী",
      standings: "ফলাফল",
      you: "আপনি",
      back: "ফিরে যান",
      placed: (place: number, of: number) => `${of} জনের মধ্যে আপনি ${place} নম্বরে`,
      place: (n: number) => `${n} নম্বর`,
      interruptedWifiTitle: "টেবিল মাঝপথে থেমেছে",
      interruptedWifiBody: "কেউ জেতেনি, তাই জয় বা হার কোনোটাই ধরা হবে না। হোস্ট নতুন টেবিল খুলতে পারেন।",
      leaveTitle: "ফলাফল ছাড়বেন?",
      leaveFacts: [{ mark: "1", title: "টেবিল বন্ধ হবে", body: "আপনি “খেলুন”-এ ফিরবেন। আবার খেলতে নতুন টেবিল শুরু করুন।" }],
      hostLeaveFacts: [{ mark: "1", title: "সবার জন্য টেবিল শেষ", body: "এই টেবিল আপনার ফোনে চলছে। আপনি গেলেই সব অতিথির সংযোগ কেটে যাবে।" }],
      leave: "ছাড়ুন",
      stay: "থাকুন",
    },
    table: {
      leave: "ছাড়ুন",
      leaveTitle: "ম্যাচ ছাড়বেন?",
      stay: "থাকুন",
      leaveFacts: (wifi: boolean) => [
        { mark: "1", title: "আপনার জায়গায় বট খেলবে", body: "ম্যাচ শেষ পর্যন্ত বট আপনার পালা খেলবে।" },
        { mark: "2", title: "ফিরে আসতে পারবেন", body: wifi ? "টেবিল চলাকালীন আবার যোগ দিন।" : "রুম চলাকালীন আবার যোগ দিন।" },
      ],
      hostFacts: [
        { mark: "1", title: "সবার জন্য টেবিল শেষ", body: "এই টেবিল আপনার ফোনে চলছে। বন্ধ করলে সবার সংযোগ কাটবে, ম্যাচও শেষ হবে।" },
      ],
      tryAgain: "আবার চেষ্টা করুন",
      openStore: "স্টোর খুলুন",
      leaveNow: "টেবিল ছাড়ুন",
    },
    scanner: {
      camera: "ক্যামেরা। টেবিলের QR কোডের দিকে ধরুন।",
      point: "হোস্টের QR কোডের দিকে ক্যামেরা ধরুন।",
      cancel: "বাতিল",
      off: "TashZone-এর ক্যামেরা অনুমতি বন্ধ। ফোনের সেটিংসে চালু করুন, বা কোড লিখুন।",
      why: "TashZone শুধু টেবিলের QR কোড স্ক্যান করতে ক্যামেরা চায়। অনুমতি দিন, বা কোড লিখুন।",
      privacy: "ক্যামেরা শুধু QR কোড স্ক্যান করে। কিছুই রেকর্ড বা সেভ হয় না।",
      settings: "সেটিংস খুলুন",
      scan: "QR কোড স্ক্যান করুন",
      qr: "টেবিলে যোগ দেওয়ার QR কোড",
    },
    seat: (name: string, status: string) => `${name}, ${status}`,
    seatName: (n: number) => `আসন ${n}`,
    score: { bhabhi: (n: number) => `${n}× Bhabhi`, points: (n: number) => `${n} পয়েন্ট` },
    defaultName: "খেলোয়াড়",
    reconnecting: { title: "আবার যুক্ত হচ্ছে…", body: "আপনার আসন রাখা আছে। দেরি হলে “আবার চেষ্টা করুন” চাপুন।" },
    offline: { title: "আপনি অফলাইনে", body: "সংযোগ হয়নি। ইন্টারনেট বা Wi-Fi দেখে “আবার চেষ্টা করুন” চাপুন।" },
    paused: { title: "টেবিল থেমে আছে", body: "সার্ভার কাজ সারছে। সব ঘড়ি থেমে আছে, পুরো সময় নিয়ে আবার চলবে।" },
    update: { title: "অনলাইনে খেলতে আপডেট করুন", body: "এই টেবিলের নিয়ম নতুন। TashZone আপডেট করে টেবিলটি আবার খুলুন।", back: "ফিরে যান" },
    locked: {
      header: "অভিভাবক বন্ধ রেখেছেন",
      back: "ফিরে যান",
      online: { title: "অনলাইন রুম বন্ধ", body: "অভিভাবক PIN দিয়ে প্যারেন্ট কন্ট্রোল থেকে আবার চালু করতে পারেন।", action: "প্যারেন্ট কন্ট্রোল খুলুন" },
      wifi: { title: "Wi-Fi টেবিল বন্ধ", body: "অভিভাবক PIN দিয়ে প্যারেন্ট কন্ট্রোল থেকে আবার চালু করতে পারেন।", action: "প্যারেন্ট কন্ট্রোল খুলুন" },
    },
    pass: {
      lead: "এবার ফোনটি দিন",
      body: (name: string) => `তাস লুকানো আছে। শুধু ${name} দেখবেন।`,
      ready: (name: string) => `আমি ${name}`,
      fallbackName: "পরের খেলোয়াড়",
    },
    errors: {
      NETWORK: "সার্ভারে যুক্ত হওয়া যায়নি। সংযোগ দেখে আবার চেষ্টা করুন।",
      ROOM_NOT_FOUND: "এই কোডের কোনো খোলা রুম নেই। কোড দেখে আবার চেষ্টা করুন।",
      ROOM_FULL: "রুম ভর্তি।",
      ROOM_CLOSED: "রুম বন্ধ হয়ে গেছে।",
      ROOM_EXPIRED: "কোডের মেয়াদ শেষ। ফাঁকা রুম কিছুক্ষণ পরে বন্ধ হয়।",
      ONLINE_ROOMS_OFF: "প্যারেন্ট কন্ট্রোলে অনলাইন রুম বন্ধ।",
      ONLINE_DISABLED: "রক্ষণাবেক্ষণের জন্য অনলাইন খেলা বন্ধ। পরে চেষ্টা করুন।",
      GAME_DISABLED: "এই খেলা এখন অনলাইনে নেই।",
      BLOCKED: "এই রুমে যোগ দিতে পারবেন না।",
      KICKED: "হোস্ট আপনাকে রুম থেকে সরিয়েছেন।",
      TICKET_EXPIRED: "সময়মতো টেবিল পাওয়া যায়নি। আবার চেষ্টা করুন।",
      UNAUTHORIZED: "অনলাইন সেশন শেষ। আবার চেষ্টা করুন।",
      RATE_LIMITED: "অনেকবার চেষ্টা হয়েছে। একটু পরে আবার চেষ্টা করুন।",
      ERROR: "কিছু গোলমাল হয়েছে। আবার চেষ্টা করুন।",
      NO_WIFI: "Wi-Fi পাওয়া যায়নি। বন্ধুদের Wi-Fi-তে যুক্ত হন বা হটস্পট চালান, তারপর আবার চেষ্টা করুন।",
      SERVER_FAILED: "এই ফোনে টেবিল খোলা যায়নি। নেটওয়ার্ক ব্যবহার করা অন্য অ্যাপ বন্ধ করে আবার চেষ্টা করুন।",
      DISCOVERY_FAILED: "কাছের টেবিল দেখা যাচ্ছে না। হোস্টের কোড স্ক্যান করুন বা ঠিকানা দিন।",
      UNREACHABLE: "ওই টেবিলে যুক্ত হওয়া যায়নি। দুজনেই একই Wi-Fi-তে আছেন আর টেবিল খোলা কি না দেখুন।",
      HOST_GONE: "হোস্টের ফোনের সাথে সংযোগ কেটে গেছে, তাই টেবিল শেষ।",
      WRONG_PIN: "ভুল PIN, বা টেবিল লক। হোস্টের স্ক্রিন দেখুন।",
      TABLE_FULL: "টেবিল ভর্তি, বা ম্যাচ শুরু হয়ে গেছে।",
      UPDATE_REQUIRED: "TashZone-এর সংস্করণ আলাদা। পুরোনো ফোন আপডেট করে আবার যোগ দিন।",
      ADDRESS_INVALID: "ঠিকানা ঠিক নেই। হোস্টের স্ক্রিন দেখে দিন, যেমন 192.168.1.20:41234।",
      QR_INVALID: "এটি এই নেটওয়ার্কের TashZone টেবিল নয়।",
    },
  },
});

export function errorMessage(code: string | null | undefined): string {
  return (code && copy.errors[code]) || copy.errors.ERROR!;
}

function ordinal(n: number): string {
  const v = n % 100;
  return `${n}${["th", "st", "nd", "rd"][(v - 20) % 10] ?? ["th", "st", "nd", "rd"][v] ?? "th"}`;
}
