import { localized } from "../../i18n";

export const PLAY = localized("play.setup", {
  en: {
    newTable: "New table",
    deal: "Deal",
    couldNotStart: "Couldn't start the table",
    couldNotSetUp: "These rules don't combine. Change one and deal again.",
    rules: "Rules",
    players: "Players",
    bots: "Bots",
    dealRow: "Deal",
    game: "Game",
    levels: { easy: "Easy", medium: "Medium", hard: "Hard" },
    you: "You",
    autoPlayed: "Time's up: a card was played for you",
    handOver: "Hand over",
    dealNext: "Deal next hand",
    results: "Results",
    matchOver: "Match over",
  },
  ur: {
    newTable: "نئی میز",
    deal: "بانٹیں",
    couldNotStart: "میز شروع نہ ہو سکی",
    couldNotSetUp: "یہ اصول ساتھ نہیں چلتے۔ ایک بدل کر پھر بانٹیں۔",
    rules: "اصول",
    players: "کھلاڑی",
    bots: "بوٹس",
    dealRow: "بانٹ",
    game: "کھیل",
    levels: { easy: "آسان", medium: "درمیانہ", hard: "مشکل" },
    you: "آپ",
    autoPlayed: "وقت ختم: آپ کا پتا خود چل گیا",
    handOver: "بازی ختم",
    dealNext: "اگلی بازی بانٹیں",
    results: "نتائج",
    matchOver: "میچ ختم",
  },
  hi: {
    newTable: "नई टेबल",
    deal: "बाँटें",
    couldNotStart: "टेबल शुरू नहीं हुई",
    couldNotSetUp: "ये नियम साथ नहीं चलते। एक बदलकर फिर बाँटें।",
    rules: "नियम",
    players: "खिलाड़ी",
    bots: "बॉट",
    dealRow: "बँटाई",
    game: "खेल",
    levels: { easy: "आसान", medium: "मध्यम", hard: "कठिन" },
    you: "आप",
    autoPlayed: "समय खत्म: आपका पत्ता अपने आप चला",
    handOver: "बाज़ी खत्म",
    dealNext: "अगली बाज़ी बाँटें",
    results: "नतीजे",
    matchOver: "मैच खत्म",
  },
  ne: {
    newTable: "नयाँ टेबल",
    deal: "बाँड्नुहोस्",
    couldNotStart: "टेबल सुरु भएन",
    couldNotSetUp: "यी नियम मिल्दैनन्। एउटा बदलेर फेरि बाँड्नुहोस्।",
    rules: "नियम",
    players: "खेलाडी",
    bots: "बोट",
    dealRow: "बाँडाइ",
    game: "खेल",
    levels: { easy: "सजिलो", medium: "मध्यम", hard: "कठिन" },
    you: "तपाईं",
    autoPlayed: "समय सकियो: तपाईंको पत्ती आफैँ खेलियो",
    handOver: "बाजी सकियो",
    dealNext: "अर्को बाजी बाँड्नुहोस्",
    results: "नतिजा",
    matchOver: "म्याच सकियो",
  },
  bn: {
    newTable: "নতুন টেবিল",
    deal: "বাঁটুন",
    couldNotStart: "টেবিল চালু হলো না",
    couldNotSetUp: "এই নিয়মগুলো একসঙ্গে চলে না। একটা বদলে আবার বাঁটুন।",
    rules: "নিয়ম",
    players: "খেলোয়াড়",
    bots: "বট",
    dealRow: "বাঁটা",
    game: "খেলা",
    levels: { easy: "সহজ", medium: "মাঝারি", hard: "কঠিন" },
    you: "আপনি",
    autoPlayed: "সময় শেষ: আপনার হয়ে তাস খেলা হলো",
    handOver: "দান শেষ",
    dealNext: "পরের দান বাঁটুন",
    results: "ফলাফল",
    matchOver: "ম্যাচ শেষ",
  },
});
