import { localized } from "../../i18n";

export const PLAY = localized("play.setup", {
  en: {
    newTable: "New table",
    deal: "Deal",
    couldNotStart: "Couldn't start the table",
    couldNotSetUp: "These rules can't be combined. Change an option and deal again.",
    rules: "Rules",
    players: "Players",
    bots: "Bots",
    dealRow: "Deal",
    game: "Game",
    levels: { easy: "Easy", medium: "Medium", hard: "Hard" },
    you: "You",
    autoPlayed: "Time's up: a card was played for you",
    handOver: "Hand over",
    dealNext: "Deal next hand",
    results: "Results",
    matchOver: "Match over",
  },
  ur: {
    newTable: "نئی میز",
    deal: "پتے بانٹیں",
    couldNotStart: "میز شروع نہیں ہو سکی",
    couldNotSetUp: "یہ اصول ایک ساتھ نہیں چلتے۔ کچھ بدل کر دوبارہ بانٹیں۔",
    rules: "اصول",
    players: "کھلاڑی",
    bots: "بوٹس",
    dealRow: "بانٹ",
    game: "کھیل",
    levels: { easy: "آسان", medium: "درمیانہ", hard: "مشکل" },
    you: "آپ",
    autoPlayed: "وقت ختم: آپ کی جگہ پتا چل دیا",
    handOver: "بازی ختم",
    dealNext: "اگلی بازی بانٹیں",
    results: "نتائج",
    matchOver: "میچ ختم",
  },
  hi: {
    newTable: "नई टेबल",
    deal: "पत्ते बाँटें",
    couldNotStart: "टेबल शुरू नहीं हो सकी",
    couldNotSetUp: "ये नियम साथ नहीं चलते। कुछ बदलकर फिर बाँटें।",
    rules: "नियम",
    players: "खिलाड़ी",
    bots: "बॉट",
    dealRow: "बँटाई",
    game: "खेल",
    levels: { easy: "आसान", medium: "मध्यम", hard: "कठिन" },
    you: "आप",
    autoPlayed: "समय खत्म: आपकी जगह पत्ता चला",
    handOver: "बाज़ी खत्म",
    dealNext: "अगली बाज़ी बाँटें",
    results: "नतीजे",
    matchOver: "मैच खत्म",
  },
  ne: {
    newTable: "नयाँ टेबल",
    deal: "पत्ती बाँड्नुहोस्",
    couldNotStart: "टेबल सुरु हुन सकेन",
    couldNotSetUp: "यी नियम सँगै मिल्दैनन्। केही बदलेर फेरि बाँड्नुहोस्।",
    rules: "नियम",
    players: "खेलाडी",
    bots: "बोट",
    dealRow: "बाँडाइ",
    game: "खेल",
    levels: { easy: "सजिलो", medium: "मध्यम", hard: "कठिन" },
    you: "तपाईं",
    autoPlayed: "समय सकियो: तपाईंको सट्टा पत्ती खेलियो",
    handOver: "बाजी सकियो",
    dealNext: "अर्को बाजी बाँड्नुहोस्",
    results: "नतिजा",
    matchOver: "म्याच सकियो",
  },
  bn: {
    newTable: "নতুন টেবিল",
    deal: "তাস বাঁটুন",
    couldNotStart: "টেবিল শুরু করা গেল না",
    couldNotSetUp: "এই নিয়মগুলো একসঙ্গে চলে না। কিছু বদলে আবার বাঁটুন।",
    rules: "নিয়ম",
    players: "খেলোয়াড়",
    bots: "বট",
    dealRow: "বাঁটা",
    game: "খেলা",
    levels: { easy: "সহজ", medium: "মাঝারি", hard: "কঠিন" },
    you: "আপনি",
    autoPlayed: "সময় শেষ: আপনার হয়ে তাস খেলা হলো",
    handOver: "দান শেষ",
    dealNext: "পরের দান বাঁটুন",
    results: "ফলাফল",
    matchOver: "ম্যাচ শেষ",
  },
});
