import { localized } from "../../i18n";

export const T = localized("tutorial", {
  en: {
    coach: "Coach",
    gotIt: "Got it",
    next: "Next",
    skip: "Skip tutorial",
    tips: {
      welcome: { title: "Your first hand", body: "You hold 13 cards, sorted by suit. Three bots play with you." },
      call: { title: "Make your call", body: (n: number) => `How many tricks will you win? Try ${n}, the suggested call.` },
      follow: { title: "Follow suit", body: "Play the suit that was led if you can. Cards you can play are raised." },
      beat: { title: "Beat the top card", body: "If you can beat the winning card, you must. Only those cards are raised." },
      trump: { title: "Spades are trump", body: "No card of the led suit? Play a spade to win the trick." },
      won: { title: "Trick won!", body: (won: number, call: number) => `You have ${won} of the ${call} you called. The winner leads next.` },
    },
    end: {
      made: { title: "Call made!", body: (call: number, won: number, pts: string) => `You called ${call} and won ${won}: +${pts} points. Miss a call and you lose it.` },
      missed: { title: "Call missed", body: (call: number, won: number, pts: string) => `You called ${call} but won ${won}: −${pts} points. Make your call to score it.` },
    },
    summary: {
      title: "Nice first hand",
      learned: "What you learned",
      lessons: [
        { title: "The call", body: "Say how many tricks you will win." },
        { title: "Follow suit", body: "Play the led suit if you can." },
        { title: "Beat the top card", body: "If you can go higher, you must." },
        { title: "Spades are trump", body: "Out of the suit? A spade wins." },
        { title: "Scoring", body: "Make your call to score it. Miss it and lose it." },
      ],
      play: "Play a real game",
      home: "Back home",
    },
    home: { title: "Learn to play", time: "2 min", body: "A guided hand of Callbreak" },
  },
  ur: {
    coach: "رہنما",
    gotIt: "ٹھیک ہے",
    next: "آگے",
    skip: "سبق چھوڑیں",
    tips: {
      welcome: { title: "آپ کی پہلی بازی", body: "آپ کے پاس 13 پتے ہیں، سوٹ کے حساب سے لگے ہوئے۔ تین بوٹ آپ کے ساتھ کھیلیں گے۔" },
      call: { title: "اپنی کال دیں", body: (n: number) => `آپ کتنے ہاتھ جیتیں گے؟ تجویز ہے ${n}۔` },
      follow: { title: "وہی سوٹ ڈالیں", body: "جو سوٹ چلا ہے، ہو سکے تو وہی ڈالیں۔ جو پتے چل سکتے ہیں وہ اوپر اٹھے ہیں۔" },
      beat: { title: "بڑا پتا ڈالیں", body: "جیتتے پتے سے بڑا ہو تو وہی ڈالنا ہے۔ صرف وہی پتے اوپر اٹھے ہیں۔" },
      trump: { title: "حکم ترپ ہے", body: "چلا ہوا سوٹ نہیں؟ حکم ڈالیں اور ہاتھ جیتیں۔" },
      won: { title: "ہاتھ آپ کا!", body: (won: number, call: number) => `کال ${call} میں سے ${won} ہاتھ ہو گئے۔ جیتنے والا اگلا پتا چلتا ہے۔` },
    },
    end: {
      made: { title: "کال پوری!", body: (call: number, won: number, pts: string) => `کال ${call}، جیتے ${won}: ${pts} نمبر ملے۔ کال ٹوٹے تو اتنے ہی نمبر کٹتے ہیں۔` },
      missed: { title: "کال ٹوٹ گئی", body: (call: number, won: number, pts: string) => `کال ${call}، جیتے صرف ${won}: ${pts} نمبر کٹے۔ کال پوری ہو تو نمبر ملتے ہیں۔` },
    },
    summary: {
      title: "زبردست پہلی بازی",
      learned: "آپ نے سیکھا",
      lessons: [
        { title: "کال", body: "بتائیں کتنے ہاتھ جیتیں گے۔" },
        { title: "وہی سوٹ", body: "ہو سکے تو چلا ہوا سوٹ ڈالیں۔" },
        { title: "بڑا پتا", body: "بڑا پتا ہو تو ڈالنا ضروری ہے۔" },
        { title: "حکم ترپ ہے", body: "سوٹ نہ ہو تو حکم جیتتا ہے۔" },
        { title: "نمبر", body: "کال پوری تو نمبر ملیں، ٹوٹے تو کٹیں۔" },
      ],
      play: "اصل کھیل کھیلیں",
      home: "واپس ہوم",
    },
    home: { title: "کھیلنا سیکھیں", time: "2 منٹ", body: "رہنمائی کے ساتھ Callbreak کی ایک بازی" },
  },
  hi: {
    coach: "गाइड",
    gotIt: "ठीक है",
    next: "आगे",
    skip: "सीखना छोड़ें",
    tips: {
      welcome: { title: "आपकी पहली बाज़ी", body: "आपके पास 13 पत्ते हैं, सूट के हिसाब से लगे। तीन बॉट आपके साथ खेलेंगे।" },
      call: { title: "अपनी कॉल करें", body: (n: number) => `आप कितने हाथ जीतेंगे? सुझाव है ${n}।` },
      follow: { title: "वही सूट डालें", body: "जो सूट चला है, हो सके तो वही डालें। जो पत्ते चल सकते हैं, वे ऊपर उठे हैं।" },
      beat: { title: "बड़ा पत्ता डालें", body: "जीत रहे पत्ते से बड़ा हो, तो वही डालना है। सिर्फ़ वही पत्ते ऊपर उठे हैं।" },
      trump: { title: "हुकुम तुरुप है", body: "चला हुआ सूट नहीं है? हुकुम डालें और हाथ जीतें।" },
      won: { title: "हाथ आपका!", body: (won: number, call: number) => `कॉल ${call} में से ${won} हाथ हो गए। जीतने वाला अगला पत्ता चलता है।` },
    },
    end: {
      made: { title: "कॉल पूरी!", body: (call: number, won: number, pts: string) => `कॉल ${call}, जीते ${won}: ${pts} अंक मिले। कॉल टूटे तो उतने ही अंक कटते हैं।` },
      missed: { title: "कॉल टूट गई", body: (call: number, won: number, pts: string) => `कॉल ${call}, जीते सिर्फ़ ${won}: ${pts} अंक कटे। कॉल पूरी हो तो अंक मिलते हैं।` },
    },
    summary: {
      title: "बढ़िया पहली बाज़ी",
      learned: "आपने सीखा",
      lessons: [
        { title: "कॉल", body: "बताएँ कितने हाथ जीतेंगे।" },
        { title: "वही सूट", body: "हो सके तो चला हुआ सूट डालें।" },
        { title: "बड़ा पत्ता", body: "बड़ा पत्ता हो तो डालना ज़रूरी है।" },
        { title: "हुकुम तुरुप है", body: "सूट न हो तो हुकुम जीतता है।" },
        { title: "अंक", body: "कॉल पूरी तो अंक मिलें, टूटी तो कटें।" },
      ],
      play: "असली खेल खेलें",
      home: "होम पर लौटें",
    },
    home: { title: "खेलना सीखें", time: "2 मिनट", body: "गाइड के साथ Callbreak की एक बाज़ी" },
  },
  ne: {
    coach: "गाइड",
    gotIt: "बुझें",
    next: "अगाडि",
    skip: "सिकाइ छाड्नुहोस्",
    tips: {
      welcome: { title: "तपाईंको पहिलो खेल", body: "तपाईंसँग 13 पत्ती छन्, रङअनुसार मिलाइएका। तीन बोट तपाईंसँग खेल्छन्।" },
      call: { title: "आफ्नो कल गर्नुहोस्", body: (n: number) => `कति हात जित्नुहुन्छ? सुझाव: ${n}।` },
      follow: { title: "चलेकै रङ फाल्नुहोस्", body: "सके चलेकै रङ फाल्नुहोस्। फाल्न मिल्ने पत्ती माथि उठेका छन्।" },
      beat: { title: "ठूलो पत्ती फाल्नुहोस्", body: "जितिरहेको पत्तीभन्दा ठूलो छ भने त्यही फाल्नुपर्छ। ती पत्ती मात्र माथि उठेका छन्।" },
      trump: { title: "हुकुम तुरुप हो", body: "चलेको रङ छैन? हुकुम फालेर हात जित्नुहोस्।" },
      won: { title: "हात तपाईंको!", body: (won: number, call: number) => `कल ${call} मध्ये ${won} हात पुगे। जित्नेले अर्को पत्ती चल्छ।` },
    },
    end: {
      made: { title: "कल पुग्यो!", body: (call: number, won: number, pts: string) => `कल ${call}, जितेको ${won}: ${pts} अङ्क पाउनुभयो। कल नपुगे त्यति नै अङ्क घट्छ।` },
      missed: { title: "कल पुगेन", body: (call: number, won: number, pts: string) => `कल ${call}, जितेको ${won} मात्र: ${pts} अङ्क घट्यो। कल पुगे अङ्क पाइन्छ।` },
    },
    summary: {
      title: "राम्रो पहिलो खेल",
      learned: "तपाईंले सिक्नुभयो",
      lessons: [
        { title: "कल", body: "कति हात जित्ने, भन्नुहोस्।" },
        { title: "चलेकै रङ", body: "सके चलेकै रङ फाल्नुहोस्।" },
        { title: "ठूलो पत्ती", body: "ठूलो पत्ती छ भने फाल्नैपर्छ।" },
        { title: "हुकुम तुरुप हो", body: "रङ छैन भने हुकुमले जित्छ।" },
        { title: "अङ्क", body: "कल पुगे अङ्क पाइन्छ, नपुगे घट्छ।" },
      ],
      play: "खास खेल खेल्नुहोस्",
      home: "होममा फर्कनुहोस्",
    },
    home: { title: "खेल्न सिक्नुहोस्", time: "2 मिनेट", body: "गाइडसँग Callbreak को एउटा खेल" },
  },
  bn: {
    coach: "গাইড",
    gotIt: "বুঝেছি",
    next: "এগোন",
    skip: "শেখা বাদ দিন",
    tips: {
      welcome: { title: "আপনার প্রথম দান", body: "আপনার হাতে 13টি তাস, রং অনুযায়ী সাজানো। তিনটি বট আপনার সঙ্গে খেলবে।" },
      call: { title: "ডাক দিন", body: (n: number) => `কত পিঠ জিতবেন? প্রস্তাব: ${n}।` },
      follow: { title: "একই রং দিন", body: "পারলে চালা রংই দিন। যে তাস দেওয়া যায়, সেগুলো উঁচু করা আছে।" },
      beat: { title: "বড় তাস দিন", body: "জিতছে এমন তাসের চেয়ে বড় থাকলে সেটাই দিতে হবে। শুধু সেগুলোই উঁচু করা আছে।" },
      trump: { title: "ইস্কাপন তুরুপ", body: "চালা রং নেই? ইস্কাপন দিয়ে পিঠ জিতুন।" },
      won: { title: "পিঠ আপনার!", body: (won: number, call: number) => `ডাক ${call}-এর মধ্যে ${won} পিঠ হলো। যে জেতে, সে পরের তাস চালে।` },
    },
    end: {
      made: { title: "ডাক পূরণ!", body: (call: number, won: number, pts: string) => `ডাক ${call}, জিতেছেন ${won}: ${pts} পয়েন্ট পেলেন। ডাক ফসকালে তত পয়েন্ট কাটা যায়।` },
      missed: { title: "ডাক ফসকাল", body: (call: number, won: number, pts: string) => `ডাক ${call}, জিতেছেন মাত্র ${won}: ${pts} পয়েন্ট কাটা গেল। ডাক পূরণ হলে পয়েন্ট মেলে।` },
    },
    summary: {
      title: "দারুণ প্রথম দান",
      learned: "আপনি শিখলেন",
      lessons: [
        { title: "ডাক", body: "কত পিঠ জিতবেন, বলুন।" },
        { title: "একই রং", body: "পারলে চালা রংই দিন।" },
        { title: "বড় তাস", body: "বড় তাস থাকলে দিতেই হবে।" },
        { title: "ইস্কাপন তুরুপ", body: "রং না থাকলে ইস্কাপন জেতে।" },
        { title: "পয়েন্ট", body: "ডাক পূরণে পয়েন্ট, ফসকালে কাটা।" },
      ],
      play: "আসল খেলা খেলুন",
      home: "হোমে ফিরুন",
    },
    home: { title: "খেলা শিখুন", time: "2 মিনিট", body: "গাইডের সঙ্গে Callbreak-এর একটি দান" },
  },
});
